// Code generated by ent, DO NOT EDIT.

package devicecommand

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldTenantID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldDeviceID, v))
}

// CommandType applies equality check predicate on the "command_type" field. It's identical to CommandTypeEQ.
func CommandType(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldCommandType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldStatus, v))
}

// SentAt applies equality check predicate on the "sent_at" field. It's identical to SentAtEQ.
func SentAt(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldSentAt, v))
}

// AcknowledgedAt applies equality check predicate on the "acknowledged_at" field. It's identical to AcknowledgedAtEQ.
func AcknowledgedAt(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldAcknowledgedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldLTE(FieldTenantID, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...uuid.UUID) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNotIn(FieldDeviceID, vs...))
}

// CommandTypeEQ applies the EQ predicate on the "command_type" field.
func CommandTypeEQ(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldCommandType, v))
}

// CommandTypeNEQ applies the NEQ predicate on the "command_type" field.
func CommandTypeNEQ(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNEQ(FieldCommandType, v))
}

// CommandTypeIn applies the In predicate on the "command_type" field.
func CommandTypeIn(vs ...string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldIn(FieldCommandType, vs...))
}

// CommandTypeNotIn applies the NotIn predicate on the "command_type" field.
func CommandTypeNotIn(vs ...string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNotIn(FieldCommandType, vs...))
}

// CommandTypeGT applies the GT predicate on the "command_type" field.
func CommandTypeGT(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldGT(FieldCommandType, v))
}

// CommandTypeGTE applies the GTE predicate on the "command_type" field.
func CommandTypeGTE(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldGTE(FieldCommandType, v))
}

// CommandTypeLT applies the LT predicate on the "command_type" field.
func CommandTypeLT(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldLT(FieldCommandType, v))
}

// CommandTypeLTE applies the LTE predicate on the "command_type" field.
func CommandTypeLTE(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldLTE(FieldCommandType, v))
}

// CommandTypeContains applies the Contains predicate on the "command_type" field.
func CommandTypeContains(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldContains(FieldCommandType, v))
}

// CommandTypeHasPrefix applies the HasPrefix predicate on the "command_type" field.
func CommandTypeHasPrefix(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldHasPrefix(FieldCommandType, v))
}

// CommandTypeHasSuffix applies the HasSuffix predicate on the "command_type" field.
func CommandTypeHasSuffix(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldHasSuffix(FieldCommandType, v))
}

// CommandTypeEqualFold applies the EqualFold predicate on the "command_type" field.
func CommandTypeEqualFold(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEqualFold(FieldCommandType, v))
}

// CommandTypeContainsFold applies the ContainsFold predicate on the "command_type" field.
func CommandTypeContainsFold(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldContainsFold(FieldCommandType, v))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNotNull(FieldPayload))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldContainsFold(FieldStatus, v))
}

// SentAtEQ applies the EQ predicate on the "sent_at" field.
func SentAtEQ(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldSentAt, v))
}

// SentAtNEQ applies the NEQ predicate on the "sent_at" field.
func SentAtNEQ(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNEQ(FieldSentAt, v))
}

// SentAtIn applies the In predicate on the "sent_at" field.
func SentAtIn(vs ...time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldIn(FieldSentAt, vs...))
}

// SentAtNotIn applies the NotIn predicate on the "sent_at" field.
func SentAtNotIn(vs ...time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNotIn(FieldSentAt, vs...))
}

// SentAtGT applies the GT predicate on the "sent_at" field.
func SentAtGT(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldGT(FieldSentAt, v))
}

// SentAtGTE applies the GTE predicate on the "sent_at" field.
func SentAtGTE(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldGTE(FieldSentAt, v))
}

// SentAtLT applies the LT predicate on the "sent_at" field.
func SentAtLT(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldLT(FieldSentAt, v))
}

// SentAtLTE applies the LTE predicate on the "sent_at" field.
func SentAtLTE(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldLTE(FieldSentAt, v))
}

// SentAtIsNil applies the IsNil predicate on the "sent_at" field.
func SentAtIsNil() predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldIsNull(FieldSentAt))
}

// SentAtNotNil applies the NotNil predicate on the "sent_at" field.
func SentAtNotNil() predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNotNull(FieldSentAt))
}

// AcknowledgedAtEQ applies the EQ predicate on the "acknowledged_at" field.
func AcknowledgedAtEQ(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldEQ(FieldAcknowledgedAt, v))
}

// AcknowledgedAtNEQ applies the NEQ predicate on the "acknowledged_at" field.
func AcknowledgedAtNEQ(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNEQ(FieldAcknowledgedAt, v))
}

// AcknowledgedAtIn applies the In predicate on the "acknowledged_at" field.
func AcknowledgedAtIn(vs ...time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldIn(FieldAcknowledgedAt, vs...))
}

// AcknowledgedAtNotIn applies the NotIn predicate on the "acknowledged_at" field.
func AcknowledgedAtNotIn(vs ...time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNotIn(FieldAcknowledgedAt, vs...))
}

// AcknowledgedAtGT applies the GT predicate on the "acknowledged_at" field.
func AcknowledgedAtGT(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldGT(FieldAcknowledgedAt, v))
}

// AcknowledgedAtGTE applies the GTE predicate on the "acknowledged_at" field.
func AcknowledgedAtGTE(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldGTE(FieldAcknowledgedAt, v))
}

// AcknowledgedAtLT applies the LT predicate on the "acknowledged_at" field.
func AcknowledgedAtLT(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldLT(FieldAcknowledgedAt, v))
}

// AcknowledgedAtLTE applies the LTE predicate on the "acknowledged_at" field.
func AcknowledgedAtLTE(v time.Time) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldLTE(FieldAcknowledgedAt, v))
}

// AcknowledgedAtIsNil applies the IsNil predicate on the "acknowledged_at" field.
func AcknowledgedAtIsNil() predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldIsNull(FieldAcknowledgedAt))
}

// AcknowledgedAtNotNil applies the NotNil predicate on the "acknowledged_at" field.
func AcknowledgedAtNotNil() predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNotNull(FieldAcknowledgedAt))
}

// ResponseIsNil applies the IsNil predicate on the "response" field.
func ResponseIsNil() predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldIsNull(FieldResponse))
}

// ResponseNotNil applies the NotNil predicate on the "response" field.
func ResponseNotNil() predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNotNull(FieldResponse))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.FieldNotNull(FieldMetadata))
}

// HasDevice applies the HasEdge predicate on the "device" edge.
func HasDevice() predicate.DeviceCommand {
	return predicate.DeviceCommand(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceWith applies the HasEdge predicate on the "device" edge with a given conditions (other predicates).
func HasDeviceWith(preds ...predicate.Device) predicate.DeviceCommand {
	return predicate.DeviceCommand(func(s *sql.Selector) {
		step := newDeviceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHistory applies the HasEdge predicate on the "history" edge.
func HasHistory() predicate.DeviceCommand {
	return predicate.DeviceCommand(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, HistoryTable, HistoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHistoryWith applies the HasEdge predicate on the "history" edge with a given conditions (other predicates).
func HasHistoryWith(preds ...predicate.CommandHistory) predicate.DeviceCommand {
	return predicate.DeviceCommand(func(s *sql.Selector) {
		step := newHistoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeviceCommand) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeviceCommand) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeviceCommand) predicate.DeviceCommand {
	return predicate.DeviceCommand(sql.NotPredicates(p))
}
