// Code generated by ent, DO NOT EDIT.

package device

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the device type in the database.
	Label = "device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldDeviceCode holds the string denoting the device_code field in the database.
	FieldDeviceCode = "device_code"
	// FieldDeviceType holds the string denoting the device_type field in the database.
	FieldDeviceType = "device_type"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldGeoPoint holds the string denoting the geo_point field in the database.
	FieldGeoPoint = "geo_point"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldRegisteredAt holds the string denoting the registered_at field in the database.
	FieldRegisteredAt = "registered_at"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAttributes holds the string denoting the attributes edge name in mutations.
	EdgeAttributes = "attributes"
	// EdgeGroupMembers holds the string denoting the group_members edge name in mutations.
	EdgeGroupMembers = "group_members"
	// EdgeTelemetryData holds the string denoting the telemetry_data edge name in mutations.
	EdgeTelemetryData = "telemetry_data"
	// EdgeCommands holds the string denoting the commands edge name in mutations.
	EdgeCommands = "commands"
	// EdgeHeartbeats holds the string denoting the heartbeats edge name in mutations.
	EdgeHeartbeats = "heartbeats"
	// EdgeFirmwareUpdates holds the string denoting the firmware_updates edge name in mutations.
	EdgeFirmwareUpdates = "firmware_updates"
	// Table holds the table name of the device in the database.
	Table = "devices"
	// AttributesTable is the table that holds the attributes relation/edge.
	AttributesTable = "device_attributes"
	// AttributesInverseTable is the table name for the DeviceAttribute entity.
	// It exists in this package in order to avoid circular dependency with the "deviceattribute" package.
	AttributesInverseTable = "device_attributes"
	// AttributesColumn is the table column denoting the attributes relation/edge.
	AttributesColumn = "device_id"
	// GroupMembersTable is the table that holds the group_members relation/edge.
	GroupMembersTable = "device_group_members"
	// GroupMembersInverseTable is the table name for the DeviceGroupMember entity.
	// It exists in this package in order to avoid circular dependency with the "devicegroupmember" package.
	GroupMembersInverseTable = "device_group_members"
	// GroupMembersColumn is the table column denoting the group_members relation/edge.
	GroupMembersColumn = "device_id"
	// TelemetryDataTable is the table that holds the telemetry_data relation/edge.
	TelemetryDataTable = "telemetry_data"
	// TelemetryDataInverseTable is the table name for the TelemetryData entity.
	// It exists in this package in order to avoid circular dependency with the "telemetrydata" package.
	TelemetryDataInverseTable = "telemetry_data"
	// TelemetryDataColumn is the table column denoting the telemetry_data relation/edge.
	TelemetryDataColumn = "device_id"
	// CommandsTable is the table that holds the commands relation/edge.
	CommandsTable = "device_commands"
	// CommandsInverseTable is the table name for the DeviceCommand entity.
	// It exists in this package in order to avoid circular dependency with the "devicecommand" package.
	CommandsInverseTable = "device_commands"
	// CommandsColumn is the table column denoting the commands relation/edge.
	CommandsColumn = "device_id"
	// HeartbeatsTable is the table that holds the heartbeats relation/edge.
	HeartbeatsTable = "device_heartbeats"
	// HeartbeatsInverseTable is the table name for the DeviceHeartbeat entity.
	// It exists in this package in order to avoid circular dependency with the "deviceheartbeat" package.
	HeartbeatsInverseTable = "device_heartbeats"
	// HeartbeatsColumn is the table column denoting the heartbeats relation/edge.
	HeartbeatsColumn = "device_id"
	// FirmwareUpdatesTable is the table that holds the firmware_updates relation/edge.
	FirmwareUpdatesTable = "firmware_updates"
	// FirmwareUpdatesInverseTable is the table name for the FirmwareUpdate entity.
	// It exists in this package in order to avoid circular dependency with the "firmwareupdate" package.
	FirmwareUpdatesInverseTable = "firmware_updates"
	// FirmwareUpdatesColumn is the table column denoting the firmware_updates relation/edge.
	FirmwareUpdatesColumn = "device_id"
)

// Columns holds all SQL columns for device fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldDeviceCode,
	FieldDeviceType,
	FieldName,
	FieldDescription,
	FieldStatus,
	FieldLocation,
	FieldGeoPoint,
	FieldMetadata,
	FieldRegisteredAt,
	FieldLastSeenAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DeviceCodeValidator is a validator for the "device_code" field. It is called by the builders before save.
	DeviceCodeValidator func(string) error
	// DeviceTypeValidator is a validator for the "device_type" field. It is called by the builders before save.
	DeviceTypeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultRegisteredAt holds the default value on creation for the "registered_at" field.
	DefaultRegisteredAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Device queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByDeviceCode orders the results by the device_code field.
func ByDeviceCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceCode, opts...).ToFunc()
}

// ByDeviceType orders the results by the device_type field.
func ByDeviceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceType, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByGeoPoint orders the results by the geo_point field.
func ByGeoPoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGeoPoint, opts...).ToFunc()
}

// ByRegisteredAt orders the results by the registered_at field.
func ByRegisteredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegisteredAt, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAttributesCount orders the results by attributes count.
func ByAttributesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttributesStep(), opts...)
	}
}

// ByAttributes orders the results by attributes terms.
func ByAttributes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttributesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGroupMembersCount orders the results by group_members count.
func ByGroupMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGroupMembersStep(), opts...)
	}
}

// ByGroupMembers orders the results by group_members terms.
func ByGroupMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTelemetryDataCount orders the results by telemetry_data count.
func ByTelemetryDataCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTelemetryDataStep(), opts...)
	}
}

// ByTelemetryData orders the results by telemetry_data terms.
func ByTelemetryData(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTelemetryDataStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCommandsCount orders the results by commands count.
func ByCommandsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommandsStep(), opts...)
	}
}

// ByCommands orders the results by commands terms.
func ByCommands(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommandsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByHeartbeatsCount orders the results by heartbeats count.
func ByHeartbeatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newHeartbeatsStep(), opts...)
	}
}

// ByHeartbeats orders the results by heartbeats terms.
func ByHeartbeats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHeartbeatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFirmwareUpdatesCount orders the results by firmware_updates count.
func ByFirmwareUpdatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFirmwareUpdatesStep(), opts...)
	}
}

// ByFirmwareUpdates orders the results by firmware_updates terms.
func ByFirmwareUpdates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFirmwareUpdatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAttributesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttributesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttributesTable, AttributesColumn),
	)
}
func newGroupMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupMembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GroupMembersTable, GroupMembersColumn),
	)
}
func newTelemetryDataStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TelemetryDataInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TelemetryDataTable, TelemetryDataColumn),
	)
}
func newCommandsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommandsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CommandsTable, CommandsColumn),
	)
}
func newHeartbeatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HeartbeatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HeartbeatsTable, HeartbeatsColumn),
	)
}
func newFirmwareUpdatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FirmwareUpdatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FirmwareUpdatesTable, FirmwareUpdatesColumn),
	)
}
