-- Create "outbox_events" table
CREATE TABLE "outbox_events" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "aggregate_type" character varying NOT NULL, "aggregate_id" uuid NOT NULL, "event_type" character varying NOT NULL, "payload" jsonb NULL, "status" character varying NOT NULL DEFAULT 'pending', "attempts" bigint NOT NULL DEFAULT 0, "last_attempt_at" timestamptz NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "tenant_sync_events" table
CREATE TABLE "tenant_sync_events" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "tenant_slug" character varying NOT NULL, "source_service" character varying NOT NULL, "payload" jsonb NULL, "synced_at" timestamptz NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', PRIMARY KEY ("id"));
-- Create "devices" table
CREATE TABLE "devices" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "device_code" character varying NOT NULL, "device_type" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "status" character varying NOT NULL DEFAULT 'active', "location" jsonb NULL, "geo_point" character varying NULL, "metadata" jsonb NULL, "registered_at" timestamptz NOT NULL, "last_seen_at" timestamptz NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "devices_device_code_key" to table: "devices"
CREATE UNIQUE INDEX "devices_device_code_key" ON "devices" ("device_code");
-- Create "device_commands" table
CREATE TABLE "device_commands" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "command_type" character varying NOT NULL, "payload" jsonb NULL, "status" character varying NOT NULL DEFAULT 'pending', "sent_at" timestamptz NULL, "acknowledged_at" timestamptz NULL, "response" jsonb NULL, "metadata" jsonb NULL, "device_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "device_commands_devices_commands" FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "command_histories" table
CREATE TABLE "command_histories" ("id" uuid NOT NULL, "event_type" character varying NOT NULL, "payload" jsonb NULL, "occurred_at" timestamptz NOT NULL, "command_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "command_histories_device_commands_history" FOREIGN KEY ("command_id") REFERENCES "device_commands" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "device_attributes" table
CREATE TABLE "device_attributes" ("id" uuid NOT NULL, "attribute_key" character varying NOT NULL, "attribute_value" character varying NOT NULL, "value_type" character varying NOT NULL DEFAULT 'string', "updated_at" timestamptz NOT NULL, "device_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "device_attributes_devices_attributes" FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "device_groups" table
CREATE TABLE "device_groups" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "group_type" character varying NOT NULL DEFAULT 'custom', "metadata" jsonb NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "device_group_members" table
CREATE TABLE "device_group_members" ("id" uuid NOT NULL, "added_at" timestamptz NOT NULL, "device_id" uuid NOT NULL, "device_group_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "device_group_members_device_groups_members" FOREIGN KEY ("device_group_id") REFERENCES "device_groups" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "device_group_members_devices_group_members" FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "device_heartbeats" table
CREATE TABLE "device_heartbeats" ("id" uuid NOT NULL, "heartbeat_at" timestamptz NOT NULL, "status" character varying NOT NULL DEFAULT 'online', "battery_level" bigint NULL, "signal_strength" bigint NULL, "metadata" jsonb NULL, "device_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "device_heartbeats_devices_heartbeats" FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "firmware_updates" table
CREATE TABLE "firmware_updates" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "firmware_version" character varying NOT NULL, "update_status" character varying NOT NULL DEFAULT 'pending', "scheduled_at" timestamptz NULL, "started_at" timestamptz NULL, "completed_at" timestamptz NULL, "error_message" character varying NULL, "metadata" jsonb NULL, "device_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "firmware_updates_devices_firmware_updates" FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "permissions" table
CREATE TABLE "permissions" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "module" character varying NOT NULL, "action" character varying NOT NULL, "resource" character varying NULL, "description" character varying NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "roles" table
CREATE TABLE "roles" ("code" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL, "is_system" boolean NOT NULL DEFAULT false, "permissions" jsonb NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("code"));
-- Create "role_permissions" table
CREATE TABLE "role_permissions" ("id" uuid NOT NULL, "assigned_at" timestamptz NOT NULL, "permission_id" uuid NOT NULL, "role_code" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "role_permissions_permissions_role_permissions" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "role_permissions_roles_role_permissions" FOREIGN KEY ("role_code") REFERENCES "roles" ("code") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "device_rules" table
CREATE TABLE "device_rules" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "name" character varying NOT NULL, "rule_type" character varying NOT NULL, "trigger_conditions" jsonb NULL, "action" jsonb NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "rule_executions" table
CREATE TABLE "rule_executions" ("id" uuid NOT NULL, "device_id" uuid NULL, "triggered_at" timestamptz NOT NULL, "execution_status" character varying NOT NULL DEFAULT 'pending', "result" jsonb NULL, "error_message" character varying NULL, "rule_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "rule_executions_device_rules_executions" FOREIGN KEY ("rule_id") REFERENCES "device_rules" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "telemetry_data" table
CREATE TABLE "telemetry_data" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "metric_name" character varying NOT NULL, "metric_value" double precision NOT NULL, "unit" character varying NULL, "timestamp" timestamptz NOT NULL, "geo_point" character varying NULL, "metadata" jsonb NULL, "created_at" timestamptz NOT NULL, "device_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "telemetry_data_devices_telemetry_data" FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "user_roles" table
CREATE TABLE "user_roles" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "user_id" uuid NOT NULL, "assigned_at" timestamptz NOT NULL, "assigned_by" uuid NULL, "metadata" jsonb NULL, "role_code" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "user_roles_roles_user_roles" FOREIGN KEY ("role_code") REFERENCES "roles" ("code") ON UPDATE NO ACTION ON DELETE NO ACTION);
