// Code generated by ent, DO NOT EDIT.

package devicegroupmember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldLTE(FieldID, id))
}

// DeviceGroupID applies equality check predicate on the "device_group_id" field. It's identical to DeviceGroupIDEQ.
func DeviceGroupID(v uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldEQ(FieldDeviceGroupID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldEQ(FieldDeviceID, v))
}

// AddedAt applies equality check predicate on the "added_at" field. It's identical to AddedAtEQ.
func AddedAt(v time.Time) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldEQ(FieldAddedAt, v))
}

// DeviceGroupIDEQ applies the EQ predicate on the "device_group_id" field.
func DeviceGroupIDEQ(v uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldEQ(FieldDeviceGroupID, v))
}

// DeviceGroupIDNEQ applies the NEQ predicate on the "device_group_id" field.
func DeviceGroupIDNEQ(v uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldNEQ(FieldDeviceGroupID, v))
}

// DeviceGroupIDIn applies the In predicate on the "device_group_id" field.
func DeviceGroupIDIn(vs ...uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldIn(FieldDeviceGroupID, vs...))
}

// DeviceGroupIDNotIn applies the NotIn predicate on the "device_group_id" field.
func DeviceGroupIDNotIn(vs ...uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldNotIn(FieldDeviceGroupID, vs...))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...uuid.UUID) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldNotIn(FieldDeviceID, vs...))
}

// AddedAtEQ applies the EQ predicate on the "added_at" field.
func AddedAtEQ(v time.Time) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldEQ(FieldAddedAt, v))
}

// AddedAtNEQ applies the NEQ predicate on the "added_at" field.
func AddedAtNEQ(v time.Time) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldNEQ(FieldAddedAt, v))
}

// AddedAtIn applies the In predicate on the "added_at" field.
func AddedAtIn(vs ...time.Time) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldIn(FieldAddedAt, vs...))
}

// AddedAtNotIn applies the NotIn predicate on the "added_at" field.
func AddedAtNotIn(vs ...time.Time) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldNotIn(FieldAddedAt, vs...))
}

// AddedAtGT applies the GT predicate on the "added_at" field.
func AddedAtGT(v time.Time) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldGT(FieldAddedAt, v))
}

// AddedAtGTE applies the GTE predicate on the "added_at" field.
func AddedAtGTE(v time.Time) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldGTE(FieldAddedAt, v))
}

// AddedAtLT applies the LT predicate on the "added_at" field.
func AddedAtLT(v time.Time) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldLT(FieldAddedAt, v))
}

// AddedAtLTE applies the LTE predicate on the "added_at" field.
func AddedAtLTE(v time.Time) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.FieldLTE(FieldAddedAt, v))
}

// HasDeviceGroup applies the HasEdge predicate on the "device_group" edge.
func HasDeviceGroup() predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceGroupTable, DeviceGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceGroupWith applies the HasEdge predicate on the "device_group" edge with a given conditions (other predicates).
func HasDeviceGroupWith(preds ...predicate.DeviceGroup) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(func(s *sql.Selector) {
		step := newDeviceGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDevice applies the HasEdge predicate on the "device" edge.
func HasDevice() predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceWith applies the HasEdge predicate on the "device" edge with a given conditions (other predicates).
func HasDeviceWith(preds ...predicate.Device) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(func(s *sql.Selector) {
		step := newDeviceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeviceGroupMember) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeviceGroupMember) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeviceGroupMember) predicate.DeviceGroupMember {
	return predicate.DeviceGroupMember(sql.NotPredicates(p))
}
