// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommandHistoriesColumns holds the columns for the "command_histories" table.
	CommandHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "event_type", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "occurred_at", Type: field.TypeTime},
		{Name: "command_id", Type: field.TypeUUID},
	}
	// CommandHistoriesTable holds the schema information for the "command_histories" table.
	CommandHistoriesTable = &schema.Table{
		Name:       "command_histories",
		Columns:    CommandHistoriesColumns,
		PrimaryKey: []*schema.Column{CommandHistoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "command_histories_device_commands_history",
				Columns:    []*schema.Column{CommandHistoriesColumns[4]},
				RefColumns: []*schema.Column{DeviceCommandsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DevicesColumns holds the columns for the "devices" table.
	DevicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "device_code", Type: field.TypeString, Unique: true},
		{Name: "device_type", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "location", Type: field.TypeJSON, Nullable: true},
		{Name: "geo_point", Type: field.TypeString, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "registered_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DevicesTable holds the schema information for the "devices" table.
	DevicesTable = &schema.Table{
		Name:       "devices",
		Columns:    DevicesColumns,
		PrimaryKey: []*schema.Column{DevicesColumns[0]},
	}
	// DeviceAttributesColumns holds the columns for the "device_attributes" table.
	DeviceAttributesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "attribute_key", Type: field.TypeString},
		{Name: "attribute_value", Type: field.TypeString},
		{Name: "value_type", Type: field.TypeString, Default: "string"},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "device_id", Type: field.TypeUUID},
	}
	// DeviceAttributesTable holds the schema information for the "device_attributes" table.
	DeviceAttributesTable = &schema.Table{
		Name:       "device_attributes",
		Columns:    DeviceAttributesColumns,
		PrimaryKey: []*schema.Column{DeviceAttributesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "device_attributes_devices_attributes",
				Columns:    []*schema.Column{DeviceAttributesColumns[5]},
				RefColumns: []*schema.Column{DevicesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DeviceCommandsColumns holds the columns for the "device_commands" table.
	DeviceCommandsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "command_type", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "sent_at", Type: field.TypeTime, Nullable: true},
		{Name: "acknowledged_at", Type: field.TypeTime, Nullable: true},
		{Name: "response", Type: field.TypeJSON, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "device_id", Type: field.TypeUUID},
	}
	// DeviceCommandsTable holds the schema information for the "device_commands" table.
	DeviceCommandsTable = &schema.Table{
		Name:       "device_commands",
		Columns:    DeviceCommandsColumns,
		PrimaryKey: []*schema.Column{DeviceCommandsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "device_commands_devices_commands",
				Columns:    []*schema.Column{DeviceCommandsColumns[9]},
				RefColumns: []*schema.Column{DevicesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DeviceGroupsColumns holds the columns for the "device_groups" table.
	DeviceGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "group_type", Type: field.TypeString, Default: "custom"},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DeviceGroupsTable holds the schema information for the "device_groups" table.
	DeviceGroupsTable = &schema.Table{
		Name:       "device_groups",
		Columns:    DeviceGroupsColumns,
		PrimaryKey: []*schema.Column{DeviceGroupsColumns[0]},
	}
	// DeviceGroupMembersColumns holds the columns for the "device_group_members" table.
	DeviceGroupMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "added_at", Type: field.TypeTime},
		{Name: "device_id", Type: field.TypeUUID},
		{Name: "device_group_id", Type: field.TypeUUID},
	}
	// DeviceGroupMembersTable holds the schema information for the "device_group_members" table.
	DeviceGroupMembersTable = &schema.Table{
		Name:       "device_group_members",
		Columns:    DeviceGroupMembersColumns,
		PrimaryKey: []*schema.Column{DeviceGroupMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "device_group_members_devices_group_members",
				Columns:    []*schema.Column{DeviceGroupMembersColumns[2]},
				RefColumns: []*schema.Column{DevicesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "device_group_members_device_groups_members",
				Columns:    []*schema.Column{DeviceGroupMembersColumns[3]},
				RefColumns: []*schema.Column{DeviceGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DeviceHeartbeatsColumns holds the columns for the "device_heartbeats" table.
	DeviceHeartbeatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "heartbeat_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "online"},
		{Name: "battery_level", Type: field.TypeInt, Nullable: true},
		{Name: "signal_strength", Type: field.TypeInt, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "device_id", Type: field.TypeUUID},
	}
	// DeviceHeartbeatsTable holds the schema information for the "device_heartbeats" table.
	DeviceHeartbeatsTable = &schema.Table{
		Name:       "device_heartbeats",
		Columns:    DeviceHeartbeatsColumns,
		PrimaryKey: []*schema.Column{DeviceHeartbeatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "device_heartbeats_devices_heartbeats",
				Columns:    []*schema.Column{DeviceHeartbeatsColumns[6]},
				RefColumns: []*schema.Column{DevicesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DeviceRulesColumns holds the columns for the "device_rules" table.
	DeviceRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "rule_type", Type: field.TypeString},
		{Name: "trigger_conditions", Type: field.TypeJSON, Nullable: true},
		{Name: "action", Type: field.TypeJSON, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DeviceRulesTable holds the schema information for the "device_rules" table.
	DeviceRulesTable = &schema.Table{
		Name:       "device_rules",
		Columns:    DeviceRulesColumns,
		PrimaryKey: []*schema.Column{DeviceRulesColumns[0]},
	}
	// FirmwareUpdatesColumns holds the columns for the "firmware_updates" table.
	FirmwareUpdatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "firmware_version", Type: field.TypeString},
		{Name: "update_status", Type: field.TypeString, Default: "pending"},
		{Name: "scheduled_at", Type: field.TypeTime, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "device_id", Type: field.TypeUUID},
	}
	// FirmwareUpdatesTable holds the schema information for the "firmware_updates" table.
	FirmwareUpdatesTable = &schema.Table{
		Name:       "firmware_updates",
		Columns:    FirmwareUpdatesColumns,
		PrimaryKey: []*schema.Column{FirmwareUpdatesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "firmware_updates_devices_firmware_updates",
				Columns:    []*schema.Column{FirmwareUpdatesColumns[9]},
				RefColumns: []*schema.Column{DevicesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// OutboxEventsColumns holds the columns for the "outbox_events" table.
	OutboxEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "aggregate_type", Type: field.TypeString},
		{Name: "aggregate_id", Type: field.TypeUUID},
		{Name: "event_type", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "last_attempt_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OutboxEventsTable holds the schema information for the "outbox_events" table.
	OutboxEventsTable = &schema.Table{
		Name:       "outbox_events",
		Columns:    OutboxEventsColumns,
		PrimaryKey: []*schema.Column{OutboxEventsColumns[0]},
	}
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "module", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "resource", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "is_system", Type: field.TypeBool, Default: false},
		{Name: "permissions", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "assigned_at", Type: field.TypeTime},
		{Name: "permission_id", Type: field.TypeUUID},
		{Name: "role_code", Type: field.TypeString},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_permissions_role_permissions",
				Columns:    []*schema.Column{RolePermissionsColumns[2]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "role_permissions_roles_role_permissions",
				Columns:    []*schema.Column{RolePermissionsColumns[3]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RuleExecutionsColumns holds the columns for the "rule_executions" table.
	RuleExecutionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "device_id", Type: field.TypeUUID, Nullable: true},
		{Name: "triggered_at", Type: field.TypeTime},
		{Name: "execution_status", Type: field.TypeString, Default: "pending"},
		{Name: "result", Type: field.TypeJSON, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "rule_id", Type: field.TypeUUID},
	}
	// RuleExecutionsTable holds the schema information for the "rule_executions" table.
	RuleExecutionsTable = &schema.Table{
		Name:       "rule_executions",
		Columns:    RuleExecutionsColumns,
		PrimaryKey: []*schema.Column{RuleExecutionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rule_executions_device_rules_executions",
				Columns:    []*schema.Column{RuleExecutionsColumns[6]},
				RefColumns: []*schema.Column{DeviceRulesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TelemetryDataColumns holds the columns for the "telemetry_data" table.
	TelemetryDataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "metric_name", Type: field.TypeString},
		{Name: "metric_value", Type: field.TypeFloat64},
		{Name: "unit", Type: field.TypeString, Nullable: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "geo_point", Type: field.TypeString, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "device_id", Type: field.TypeUUID},
	}
	// TelemetryDataTable holds the schema information for the "telemetry_data" table.
	TelemetryDataTable = &schema.Table{
		Name:       "telemetry_data",
		Columns:    TelemetryDataColumns,
		PrimaryKey: []*schema.Column{TelemetryDataColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "telemetry_data_devices_telemetry_data",
				Columns:    []*schema.Column{TelemetryDataColumns[9]},
				RefColumns: []*schema.Column{DevicesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TenantSyncEventsColumns holds the columns for the "tenant_sync_events" table.
	TenantSyncEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "tenant_slug", Type: field.TypeString},
		{Name: "source_service", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON, Nullable: true},
		{Name: "synced_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "pending"},
	}
	// TenantSyncEventsTable holds the schema information for the "tenant_sync_events" table.
	TenantSyncEventsTable = &schema.Table{
		Name:       "tenant_sync_events",
		Columns:    TenantSyncEventsColumns,
		PrimaryKey: []*schema.Column{TenantSyncEventsColumns[0]},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "assigned_at", Type: field.TypeTime},
		{Name: "assigned_by", Type: field.TypeUUID, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "role_code", Type: field.TypeString},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_roles_roles_user_roles",
				Columns:    []*schema.Column{UserRolesColumns[6]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommandHistoriesTable,
		DevicesTable,
		DeviceAttributesTable,
		DeviceCommandsTable,
		DeviceGroupsTable,
		DeviceGroupMembersTable,
		DeviceHeartbeatsTable,
		DeviceRulesTable,
		FirmwareUpdatesTable,
		OutboxEventsTable,
		PermissionsTable,
		RolesTable,
		RolePermissionsTable,
		RuleExecutionsTable,
		TelemetryDataTable,
		TenantSyncEventsTable,
		UserRolesTable,
	}
)

func init() {
	CommandHistoriesTable.ForeignKeys[0].RefTable = DeviceCommandsTable
	DeviceAttributesTable.ForeignKeys[0].RefTable = DevicesTable
	DeviceCommandsTable.ForeignKeys[0].RefTable = DevicesTable
	DeviceGroupMembersTable.ForeignKeys[0].RefTable = DevicesTable
	DeviceGroupMembersTable.ForeignKeys[1].RefTable = DeviceGroupsTable
	DeviceHeartbeatsTable.ForeignKeys[0].RefTable = DevicesTable
	FirmwareUpdatesTable.ForeignKeys[0].RefTable = DevicesTable
	RolePermissionsTable.ForeignKeys[0].RefTable = PermissionsTable
	RolePermissionsTable.ForeignKeys[1].RefTable = RolesTable
	RuleExecutionsTable.ForeignKeys[0].RefTable = DeviceRulesTable
	TelemetryDataTable.ForeignKeys[0].RefTable = DevicesTable
	UserRolesTable.ForeignKeys[0].RefTable = RolesTable
}
