// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/commandhistory"
	"github.com/bengobox/iot-service/internal/ent/predicate"
)

// CommandHistoryDelete is the builder for deleting a CommandHistory entity.
type CommandHistoryDelete struct {
	config
	hooks    []Hook
	mutation *CommandHistoryMutation
}

// Where appends a list predicates to the CommandHistoryDelete builder.
func (chd *CommandHistoryDelete) Where(ps ...predicate.CommandHistory) *CommandHistoryDelete {
	chd.mutation.Where(ps...)
	return chd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (chd *CommandHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, chd.sqlExec, chd.mutation, chd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (chd *CommandHistoryDelete) ExecX(ctx context.Context) int {
	n, err := chd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (chd *CommandHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(commandhistory.Table, sqlgraph.NewFieldSpec(commandhistory.FieldID, field.TypeUUID))
	if ps := chd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, chd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	chd.mutation.done = true
	return affected, err
}

// CommandHistoryDeleteOne is the builder for deleting a single CommandHistory entity.
type CommandHistoryDeleteOne struct {
	chd *CommandHistoryDelete
}

// Where appends a list predicates to the CommandHistoryDelete builder.
func (chdo *CommandHistoryDeleteOne) Where(ps ...predicate.CommandHistory) *CommandHistoryDeleteOne {
	chdo.chd.mutation.Where(ps...)
	return chdo
}

// Exec executes the deletion query.
func (chdo *CommandHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := chdo.chd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{commandhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (chdo *CommandHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := chdo.Exec(ctx); err != nil {
		panic(err)
	}
}
