// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/iot-service/internal/ent/commandhistory"
	"github.com/bengobox/iot-service/internal/ent/devicecommand"
	"github.com/google/uuid"
)

// CommandHistory is the model entity for the CommandHistory schema.
type CommandHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CommandID holds the value of the "command_id" field.
	CommandID uuid.UUID `json:"command_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// OccurredAt holds the value of the "occurred_at" field.
	OccurredAt time.Time `json:"occurred_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CommandHistoryQuery when eager-loading is set.
	Edges        CommandHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CommandHistoryEdges holds the relations/edges for other nodes in the graph.
type CommandHistoryEdges struct {
	// Command holds the value of the command edge.
	Command *DeviceCommand `json:"command,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CommandOrErr returns the Command value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CommandHistoryEdges) CommandOrErr() (*DeviceCommand, error) {
	if e.Command != nil {
		return e.Command, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: devicecommand.Label}
	}
	return nil, &NotLoadedError{edge: "command"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CommandHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case commandhistory.FieldPayload:
			values[i] = new([]byte)
		case commandhistory.FieldEventType:
			values[i] = new(sql.NullString)
		case commandhistory.FieldOccurredAt:
			values[i] = new(sql.NullTime)
		case commandhistory.FieldID, commandhistory.FieldCommandID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CommandHistory fields.
func (ch *CommandHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case commandhistory.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ch.ID = *value
			}
		case commandhistory.FieldCommandID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field command_id", values[i])
			} else if value != nil {
				ch.CommandID = *value
			}
		case commandhistory.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				ch.EventType = value.String
			}
		case commandhistory.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ch.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case commandhistory.FieldOccurredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field occurred_at", values[i])
			} else if value.Valid {
				ch.OccurredAt = value.Time
			}
		default:
			ch.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CommandHistory.
// This includes values selected through modifiers, order, etc.
func (ch *CommandHistory) Value(name string) (ent.Value, error) {
	return ch.selectValues.Get(name)
}

// QueryCommand queries the "command" edge of the CommandHistory entity.
func (ch *CommandHistory) QueryCommand() *DeviceCommandQuery {
	return NewCommandHistoryClient(ch.config).QueryCommand(ch)
}

// Update returns a builder for updating this CommandHistory.
// Note that you need to call CommandHistory.Unwrap() before calling this method if this CommandHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (ch *CommandHistory) Update() *CommandHistoryUpdateOne {
	return NewCommandHistoryClient(ch.config).UpdateOne(ch)
}

// Unwrap unwraps the CommandHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ch *CommandHistory) Unwrap() *CommandHistory {
	_tx, ok := ch.config.driver.(*txDriver)
	if !ok {
		panic("ent: CommandHistory is not a transactional entity")
	}
	ch.config.driver = _tx.drv
	return ch
}

// String implements the fmt.Stringer.
func (ch *CommandHistory) String() string {
	var builder strings.Builder
	builder.WriteString("CommandHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ch.ID))
	builder.WriteString("command_id=")
	builder.WriteString(fmt.Sprintf("%v", ch.CommandID))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(ch.EventType)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", ch.Payload))
	builder.WriteString(", ")
	builder.WriteString("occurred_at=")
	builder.WriteString(ch.OccurredAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CommandHistories is a parsable slice of CommandHistory.
type CommandHistories []*CommandHistory
