// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/commandhistory"
	"github.com/bengobox/iot-service/internal/ent/devicecommand"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// CommandHistoryQuery is the builder for querying CommandHistory entities.
type CommandHistoryQuery struct {
	config
	ctx         *QueryContext
	order       []commandhistory.OrderOption
	inters      []Interceptor
	predicates  []predicate.CommandHistory
	withCommand *DeviceCommandQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CommandHistoryQuery builder.
func (chq *CommandHistoryQuery) Where(ps ...predicate.CommandHistory) *CommandHistoryQuery {
	chq.predicates = append(chq.predicates, ps...)
	return chq
}

// Limit the number of records to be returned by this query.
func (chq *CommandHistoryQuery) Limit(limit int) *CommandHistoryQuery {
	chq.ctx.Limit = &limit
	return chq
}

// Offset to start from.
func (chq *CommandHistoryQuery) Offset(offset int) *CommandHistoryQuery {
	chq.ctx.Offset = &offset
	return chq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (chq *CommandHistoryQuery) Unique(unique bool) *CommandHistoryQuery {
	chq.ctx.Unique = &unique
	return chq
}

// Order specifies how the records should be ordered.
func (chq *CommandHistoryQuery) Order(o ...commandhistory.OrderOption) *CommandHistoryQuery {
	chq.order = append(chq.order, o...)
	return chq
}

// QueryCommand chains the current query on the "command" edge.
func (chq *CommandHistoryQuery) QueryCommand() *DeviceCommandQuery {
	query := (&DeviceCommandClient{config: chq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := chq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := chq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(commandhistory.Table, commandhistory.FieldID, selector),
			sqlgraph.To(devicecommand.Table, devicecommand.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, commandhistory.CommandTable, commandhistory.CommandColumn),
		)
		fromU = sqlgraph.SetNeighbors(chq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CommandHistory entity from the query.
// Returns a *NotFoundError when no CommandHistory was found.
func (chq *CommandHistoryQuery) First(ctx context.Context) (*CommandHistory, error) {
	nodes, err := chq.Limit(1).All(setContextOp(ctx, chq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{commandhistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (chq *CommandHistoryQuery) FirstX(ctx context.Context) *CommandHistory {
	node, err := chq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CommandHistory ID from the query.
// Returns a *NotFoundError when no CommandHistory ID was found.
func (chq *CommandHistoryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = chq.Limit(1).IDs(setContextOp(ctx, chq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{commandhistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (chq *CommandHistoryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := chq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CommandHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CommandHistory entity is found.
// Returns a *NotFoundError when no CommandHistory entities are found.
func (chq *CommandHistoryQuery) Only(ctx context.Context) (*CommandHistory, error) {
	nodes, err := chq.Limit(2).All(setContextOp(ctx, chq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{commandhistory.Label}
	default:
		return nil, &NotSingularError{commandhistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (chq *CommandHistoryQuery) OnlyX(ctx context.Context) *CommandHistory {
	node, err := chq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CommandHistory ID in the query.
// Returns a *NotSingularError when more than one CommandHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (chq *CommandHistoryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = chq.Limit(2).IDs(setContextOp(ctx, chq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{commandhistory.Label}
	default:
		err = &NotSingularError{commandhistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (chq *CommandHistoryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := chq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CommandHistories.
func (chq *CommandHistoryQuery) All(ctx context.Context) ([]*CommandHistory, error) {
	ctx = setContextOp(ctx, chq.ctx, "All")
	if err := chq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CommandHistory, *CommandHistoryQuery]()
	return withInterceptors[[]*CommandHistory](ctx, chq, qr, chq.inters)
}

// AllX is like All, but panics if an error occurs.
func (chq *CommandHistoryQuery) AllX(ctx context.Context) []*CommandHistory {
	nodes, err := chq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CommandHistory IDs.
func (chq *CommandHistoryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if chq.ctx.Unique == nil && chq.path != nil {
		chq.Unique(true)
	}
	ctx = setContextOp(ctx, chq.ctx, "IDs")
	if err = chq.Select(commandhistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (chq *CommandHistoryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := chq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (chq *CommandHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, chq.ctx, "Count")
	if err := chq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, chq, querierCount[*CommandHistoryQuery](), chq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (chq *CommandHistoryQuery) CountX(ctx context.Context) int {
	count, err := chq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (chq *CommandHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, chq.ctx, "Exist")
	switch _, err := chq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (chq *CommandHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := chq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CommandHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (chq *CommandHistoryQuery) Clone() *CommandHistoryQuery {
	if chq == nil {
		return nil
	}
	return &CommandHistoryQuery{
		config:      chq.config,
		ctx:         chq.ctx.Clone(),
		order:       append([]commandhistory.OrderOption{}, chq.order...),
		inters:      append([]Interceptor{}, chq.inters...),
		predicates:  append([]predicate.CommandHistory{}, chq.predicates...),
		withCommand: chq.withCommand.Clone(),
		// clone intermediate query.
		sql:  chq.sql.Clone(),
		path: chq.path,
	}
}

// WithCommand tells the query-builder to eager-load the nodes that are connected to
// the "command" edge. The optional arguments are used to configure the query builder of the edge.
func (chq *CommandHistoryQuery) WithCommand(opts ...func(*DeviceCommandQuery)) *CommandHistoryQuery {
	query := (&DeviceCommandClient{config: chq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	chq.withCommand = query
	return chq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CommandID uuid.UUID `json:"command_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CommandHistory.Query().
//		GroupBy(commandhistory.FieldCommandID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (chq *CommandHistoryQuery) GroupBy(field string, fields ...string) *CommandHistoryGroupBy {
	chq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CommandHistoryGroupBy{build: chq}
	grbuild.flds = &chq.ctx.Fields
	grbuild.label = commandhistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CommandID uuid.UUID `json:"command_id,omitempty"`
//	}
//
//	client.CommandHistory.Query().
//		Select(commandhistory.FieldCommandID).
//		Scan(ctx, &v)
func (chq *CommandHistoryQuery) Select(fields ...string) *CommandHistorySelect {
	chq.ctx.Fields = append(chq.ctx.Fields, fields...)
	sbuild := &CommandHistorySelect{CommandHistoryQuery: chq}
	sbuild.label = commandhistory.Label
	sbuild.flds, sbuild.scan = &chq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CommandHistorySelect configured with the given aggregations.
func (chq *CommandHistoryQuery) Aggregate(fns ...AggregateFunc) *CommandHistorySelect {
	return chq.Select().Aggregate(fns...)
}

func (chq *CommandHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range chq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, chq); err != nil {
				return err
			}
		}
	}
	for _, f := range chq.ctx.Fields {
		if !commandhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if chq.path != nil {
		prev, err := chq.path(ctx)
		if err != nil {
			return err
		}
		chq.sql = prev
	}
	return nil
}

func (chq *CommandHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CommandHistory, error) {
	var (
		nodes       = []*CommandHistory{}
		_spec       = chq.querySpec()
		loadedTypes = [1]bool{
			chq.withCommand != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CommandHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CommandHistory{config: chq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, chq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := chq.withCommand; query != nil {
		if err := chq.loadCommand(ctx, query, nodes, nil,
			func(n *CommandHistory, e *DeviceCommand) { n.Edges.Command = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (chq *CommandHistoryQuery) loadCommand(ctx context.Context, query *DeviceCommandQuery, nodes []*CommandHistory, init func(*CommandHistory), assign func(*CommandHistory, *DeviceCommand)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CommandHistory)
	for i := range nodes {
		fk := nodes[i].CommandID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(devicecommand.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "command_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (chq *CommandHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := chq.querySpec()
	_spec.Node.Columns = chq.ctx.Fields
	if len(chq.ctx.Fields) > 0 {
		_spec.Unique = chq.ctx.Unique != nil && *chq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, chq.driver, _spec)
}

func (chq *CommandHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(commandhistory.Table, commandhistory.Columns, sqlgraph.NewFieldSpec(commandhistory.FieldID, field.TypeUUID))
	_spec.From = chq.sql
	if unique := chq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if chq.path != nil {
		_spec.Unique = true
	}
	if fields := chq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commandhistory.FieldID)
		for i := range fields {
			if fields[i] != commandhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if chq.withCommand != nil {
			_spec.Node.AddColumnOnce(commandhistory.FieldCommandID)
		}
	}
	if ps := chq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := chq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := chq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := chq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (chq *CommandHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(chq.driver.Dialect())
	t1 := builder.Table(commandhistory.Table)
	columns := chq.ctx.Fields
	if len(columns) == 0 {
		columns = commandhistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if chq.sql != nil {
		selector = chq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if chq.ctx.Unique != nil && *chq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range chq.predicates {
		p(selector)
	}
	for _, p := range chq.order {
		p(selector)
	}
	if offset := chq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := chq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CommandHistoryGroupBy is the group-by builder for CommandHistory entities.
type CommandHistoryGroupBy struct {
	selector
	build *CommandHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (chgb *CommandHistoryGroupBy) Aggregate(fns ...AggregateFunc) *CommandHistoryGroupBy {
	chgb.fns = append(chgb.fns, fns...)
	return chgb
}

// Scan applies the selector query and scans the result into the given value.
func (chgb *CommandHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, chgb.build.ctx, "GroupBy")
	if err := chgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommandHistoryQuery, *CommandHistoryGroupBy](ctx, chgb.build, chgb, chgb.build.inters, v)
}

func (chgb *CommandHistoryGroupBy) sqlScan(ctx context.Context, root *CommandHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(chgb.fns))
	for _, fn := range chgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*chgb.flds)+len(chgb.fns))
		for _, f := range *chgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*chgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := chgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CommandHistorySelect is the builder for selecting fields of CommandHistory entities.
type CommandHistorySelect struct {
	*CommandHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (chs *CommandHistorySelect) Aggregate(fns ...AggregateFunc) *CommandHistorySelect {
	chs.fns = append(chs.fns, fns...)
	return chs
}

// Scan applies the selector query and scans the result into the given value.
func (chs *CommandHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, chs.ctx, "Select")
	if err := chs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CommandHistoryQuery, *CommandHistorySelect](ctx, chs.CommandHistoryQuery, chs, chs.inters, v)
}

func (chs *CommandHistorySelect) sqlScan(ctx context.Context, root *CommandHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(chs.fns))
	for _, fn := range chs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*chs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := chs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
