// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/commandhistory"
	"github.com/bengobox/iot-service/internal/ent/devicecommand"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// CommandHistoryUpdate is the builder for updating CommandHistory entities.
type CommandHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *CommandHistoryMutation
}

// Where appends a list predicates to the CommandHistoryUpdate builder.
func (chu *CommandHistoryUpdate) Where(ps ...predicate.CommandHistory) *CommandHistoryUpdate {
	chu.mutation.Where(ps...)
	return chu
}

// SetCommandID sets the "command_id" field.
func (chu *CommandHistoryUpdate) SetCommandID(u uuid.UUID) *CommandHistoryUpdate {
	chu.mutation.SetCommandID(u)
	return chu
}

// SetNillableCommandID sets the "command_id" field if the given value is not nil.
func (chu *CommandHistoryUpdate) SetNillableCommandID(u *uuid.UUID) *CommandHistoryUpdate {
	if u != nil {
		chu.SetCommandID(*u)
	}
	return chu
}

// SetEventType sets the "event_type" field.
func (chu *CommandHistoryUpdate) SetEventType(s string) *CommandHistoryUpdate {
	chu.mutation.SetEventType(s)
	return chu
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (chu *CommandHistoryUpdate) SetNillableEventType(s *string) *CommandHistoryUpdate {
	if s != nil {
		chu.SetEventType(*s)
	}
	return chu
}

// SetPayload sets the "payload" field.
func (chu *CommandHistoryUpdate) SetPayload(m map[string]interface{}) *CommandHistoryUpdate {
	chu.mutation.SetPayload(m)
	return chu
}

// ClearPayload clears the value of the "payload" field.
func (chu *CommandHistoryUpdate) ClearPayload() *CommandHistoryUpdate {
	chu.mutation.ClearPayload()
	return chu
}

// SetOccurredAt sets the "occurred_at" field.
func (chu *CommandHistoryUpdate) SetOccurredAt(t time.Time) *CommandHistoryUpdate {
	chu.mutation.SetOccurredAt(t)
	return chu
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (chu *CommandHistoryUpdate) SetNillableOccurredAt(t *time.Time) *CommandHistoryUpdate {
	if t != nil {
		chu.SetOccurredAt(*t)
	}
	return chu
}

// SetCommand sets the "command" edge to the DeviceCommand entity.
func (chu *CommandHistoryUpdate) SetCommand(d *DeviceCommand) *CommandHistoryUpdate {
	return chu.SetCommandID(d.ID)
}

// Mutation returns the CommandHistoryMutation object of the builder.
func (chu *CommandHistoryUpdate) Mutation() *CommandHistoryMutation {
	return chu.mutation
}

// ClearCommand clears the "command" edge to the DeviceCommand entity.
func (chu *CommandHistoryUpdate) ClearCommand() *CommandHistoryUpdate {
	chu.mutation.ClearCommand()
	return chu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (chu *CommandHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, chu.sqlSave, chu.mutation, chu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (chu *CommandHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := chu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (chu *CommandHistoryUpdate) Exec(ctx context.Context) error {
	_, err := chu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (chu *CommandHistoryUpdate) ExecX(ctx context.Context) {
	if err := chu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (chu *CommandHistoryUpdate) check() error {
	if v, ok := chu.mutation.EventType(); ok {
		if err := commandhistory.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "CommandHistory.event_type": %w`, err)}
		}
	}
	if _, ok := chu.mutation.CommandID(); chu.mutation.CommandCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "CommandHistory.command"`)
	}
	return nil
}

func (chu *CommandHistoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := chu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(commandhistory.Table, commandhistory.Columns, sqlgraph.NewFieldSpec(commandhistory.FieldID, field.TypeUUID))
	if ps := chu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := chu.mutation.EventType(); ok {
		_spec.SetField(commandhistory.FieldEventType, field.TypeString, value)
	}
	if value, ok := chu.mutation.Payload(); ok {
		_spec.SetField(commandhistory.FieldPayload, field.TypeJSON, value)
	}
	if chu.mutation.PayloadCleared() {
		_spec.ClearField(commandhistory.FieldPayload, field.TypeJSON)
	}
	if value, ok := chu.mutation.OccurredAt(); ok {
		_spec.SetField(commandhistory.FieldOccurredAt, field.TypeTime, value)
	}
	if chu.mutation.CommandCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commandhistory.CommandTable,
			Columns: []string{commandhistory.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicecommand.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := chu.mutation.CommandIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commandhistory.CommandTable,
			Columns: []string{commandhistory.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicecommand.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, chu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commandhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	chu.mutation.done = true
	return n, nil
}

// CommandHistoryUpdateOne is the builder for updating a single CommandHistory entity.
type CommandHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CommandHistoryMutation
}

// SetCommandID sets the "command_id" field.
func (chuo *CommandHistoryUpdateOne) SetCommandID(u uuid.UUID) *CommandHistoryUpdateOne {
	chuo.mutation.SetCommandID(u)
	return chuo
}

// SetNillableCommandID sets the "command_id" field if the given value is not nil.
func (chuo *CommandHistoryUpdateOne) SetNillableCommandID(u *uuid.UUID) *CommandHistoryUpdateOne {
	if u != nil {
		chuo.SetCommandID(*u)
	}
	return chuo
}

// SetEventType sets the "event_type" field.
func (chuo *CommandHistoryUpdateOne) SetEventType(s string) *CommandHistoryUpdateOne {
	chuo.mutation.SetEventType(s)
	return chuo
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (chuo *CommandHistoryUpdateOne) SetNillableEventType(s *string) *CommandHistoryUpdateOne {
	if s != nil {
		chuo.SetEventType(*s)
	}
	return chuo
}

// SetPayload sets the "payload" field.
func (chuo *CommandHistoryUpdateOne) SetPayload(m map[string]interface{}) *CommandHistoryUpdateOne {
	chuo.mutation.SetPayload(m)
	return chuo
}

// ClearPayload clears the value of the "payload" field.
func (chuo *CommandHistoryUpdateOne) ClearPayload() *CommandHistoryUpdateOne {
	chuo.mutation.ClearPayload()
	return chuo
}

// SetOccurredAt sets the "occurred_at" field.
func (chuo *CommandHistoryUpdateOne) SetOccurredAt(t time.Time) *CommandHistoryUpdateOne {
	chuo.mutation.SetOccurredAt(t)
	return chuo
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (chuo *CommandHistoryUpdateOne) SetNillableOccurredAt(t *time.Time) *CommandHistoryUpdateOne {
	if t != nil {
		chuo.SetOccurredAt(*t)
	}
	return chuo
}

// SetCommand sets the "command" edge to the DeviceCommand entity.
func (chuo *CommandHistoryUpdateOne) SetCommand(d *DeviceCommand) *CommandHistoryUpdateOne {
	return chuo.SetCommandID(d.ID)
}

// Mutation returns the CommandHistoryMutation object of the builder.
func (chuo *CommandHistoryUpdateOne) Mutation() *CommandHistoryMutation {
	return chuo.mutation
}

// ClearCommand clears the "command" edge to the DeviceCommand entity.
func (chuo *CommandHistoryUpdateOne) ClearCommand() *CommandHistoryUpdateOne {
	chuo.mutation.ClearCommand()
	return chuo
}

// Where appends a list predicates to the CommandHistoryUpdate builder.
func (chuo *CommandHistoryUpdateOne) Where(ps ...predicate.CommandHistory) *CommandHistoryUpdateOne {
	chuo.mutation.Where(ps...)
	return chuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (chuo *CommandHistoryUpdateOne) Select(field string, fields ...string) *CommandHistoryUpdateOne {
	chuo.fields = append([]string{field}, fields...)
	return chuo
}

// Save executes the query and returns the updated CommandHistory entity.
func (chuo *CommandHistoryUpdateOne) Save(ctx context.Context) (*CommandHistory, error) {
	return withHooks(ctx, chuo.sqlSave, chuo.mutation, chuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (chuo *CommandHistoryUpdateOne) SaveX(ctx context.Context) *CommandHistory {
	node, err := chuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (chuo *CommandHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := chuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (chuo *CommandHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := chuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (chuo *CommandHistoryUpdateOne) check() error {
	if v, ok := chuo.mutation.EventType(); ok {
		if err := commandhistory.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "CommandHistory.event_type": %w`, err)}
		}
	}
	if _, ok := chuo.mutation.CommandID(); chuo.mutation.CommandCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "CommandHistory.command"`)
	}
	return nil
}

func (chuo *CommandHistoryUpdateOne) sqlSave(ctx context.Context) (_node *CommandHistory, err error) {
	if err := chuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(commandhistory.Table, commandhistory.Columns, sqlgraph.NewFieldSpec(commandhistory.FieldID, field.TypeUUID))
	id, ok := chuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CommandHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := chuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commandhistory.FieldID)
		for _, f := range fields {
			if !commandhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != commandhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := chuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := chuo.mutation.EventType(); ok {
		_spec.SetField(commandhistory.FieldEventType, field.TypeString, value)
	}
	if value, ok := chuo.mutation.Payload(); ok {
		_spec.SetField(commandhistory.FieldPayload, field.TypeJSON, value)
	}
	if chuo.mutation.PayloadCleared() {
		_spec.ClearField(commandhistory.FieldPayload, field.TypeJSON)
	}
	if value, ok := chuo.mutation.OccurredAt(); ok {
		_spec.SetField(commandhistory.FieldOccurredAt, field.TypeTime, value)
	}
	if chuo.mutation.CommandCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commandhistory.CommandTable,
			Columns: []string{commandhistory.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicecommand.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := chuo.mutation.CommandIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commandhistory.CommandTable,
			Columns: []string{commandhistory.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicecommand.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CommandHistory{config: chuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, chuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commandhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	chuo.mutation.done = true
	return _node, nil
}
