// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/commandhistory"
	"github.com/bengobox/iot-service/internal/ent/devicecommand"
	"github.com/google/uuid"
)

// CommandHistoryCreate is the builder for creating a CommandHistory entity.
type CommandHistoryCreate struct {
	config
	mutation *CommandHistoryMutation
	hooks    []Hook
}

// SetCommandID sets the "command_id" field.
func (chc *CommandHistoryCreate) SetCommandID(u uuid.UUID) *CommandHistoryCreate {
	chc.mutation.SetCommandID(u)
	return chc
}

// SetEventType sets the "event_type" field.
func (chc *CommandHistoryCreate) SetEventType(s string) *CommandHistoryCreate {
	chc.mutation.SetEventType(s)
	return chc
}

// SetPayload sets the "payload" field.
func (chc *CommandHistoryCreate) SetPayload(m map[string]interface{}) *CommandHistoryCreate {
	chc.mutation.SetPayload(m)
	return chc
}

// SetOccurredAt sets the "occurred_at" field.
func (chc *CommandHistoryCreate) SetOccurredAt(t time.Time) *CommandHistoryCreate {
	chc.mutation.SetOccurredAt(t)
	return chc
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (chc *CommandHistoryCreate) SetNillableOccurredAt(t *time.Time) *CommandHistoryCreate {
	if t != nil {
		chc.SetOccurredAt(*t)
	}
	return chc
}

// SetID sets the "id" field.
func (chc *CommandHistoryCreate) SetID(u uuid.UUID) *CommandHistoryCreate {
	chc.mutation.SetID(u)
	return chc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (chc *CommandHistoryCreate) SetNillableID(u *uuid.UUID) *CommandHistoryCreate {
	if u != nil {
		chc.SetID(*u)
	}
	return chc
}

// SetCommand sets the "command" edge to the DeviceCommand entity.
func (chc *CommandHistoryCreate) SetCommand(d *DeviceCommand) *CommandHistoryCreate {
	return chc.SetCommandID(d.ID)
}

// Mutation returns the CommandHistoryMutation object of the builder.
func (chc *CommandHistoryCreate) Mutation() *CommandHistoryMutation {
	return chc.mutation
}

// Save creates the CommandHistory in the database.
func (chc *CommandHistoryCreate) Save(ctx context.Context) (*CommandHistory, error) {
	chc.defaults()
	return withHooks(ctx, chc.sqlSave, chc.mutation, chc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (chc *CommandHistoryCreate) SaveX(ctx context.Context) *CommandHistory {
	v, err := chc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (chc *CommandHistoryCreate) Exec(ctx context.Context) error {
	_, err := chc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (chc *CommandHistoryCreate) ExecX(ctx context.Context) {
	if err := chc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (chc *CommandHistoryCreate) defaults() {
	if _, ok := chc.mutation.OccurredAt(); !ok {
		v := commandhistory.DefaultOccurredAt()
		chc.mutation.SetOccurredAt(v)
	}
	if _, ok := chc.mutation.ID(); !ok {
		v := commandhistory.DefaultID()
		chc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (chc *CommandHistoryCreate) check() error {
	if _, ok := chc.mutation.CommandID(); !ok {
		return &ValidationError{Name: "command_id", err: errors.New(`ent: missing required field "CommandHistory.command_id"`)}
	}
	if _, ok := chc.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "CommandHistory.event_type"`)}
	}
	if v, ok := chc.mutation.EventType(); ok {
		if err := commandhistory.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "CommandHistory.event_type": %w`, err)}
		}
	}
	if _, ok := chc.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "CommandHistory.occurred_at"`)}
	}
	if _, ok := chc.mutation.CommandID(); !ok {
		return &ValidationError{Name: "command", err: errors.New(`ent: missing required edge "CommandHistory.command"`)}
	}
	return nil
}

func (chc *CommandHistoryCreate) sqlSave(ctx context.Context) (*CommandHistory, error) {
	if err := chc.check(); err != nil {
		return nil, err
	}
	_node, _spec := chc.createSpec()
	if err := sqlgraph.CreateNode(ctx, chc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	chc.mutation.id = &_node.ID
	chc.mutation.done = true
	return _node, nil
}

func (chc *CommandHistoryCreate) createSpec() (*CommandHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &CommandHistory{config: chc.config}
		_spec = sqlgraph.NewCreateSpec(commandhistory.Table, sqlgraph.NewFieldSpec(commandhistory.FieldID, field.TypeUUID))
	)
	if id, ok := chc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := chc.mutation.EventType(); ok {
		_spec.SetField(commandhistory.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := chc.mutation.Payload(); ok {
		_spec.SetField(commandhistory.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := chc.mutation.OccurredAt(); ok {
		_spec.SetField(commandhistory.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if nodes := chc.mutation.CommandIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   commandhistory.CommandTable,
			Columns: []string{commandhistory.CommandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicecommand.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CommandID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CommandHistoryCreateBulk is the builder for creating many CommandHistory entities in bulk.
type CommandHistoryCreateBulk struct {
	config
	err      error
	builders []*CommandHistoryCreate
}

// Save creates the CommandHistory entities in the database.
func (chcb *CommandHistoryCreateBulk) Save(ctx context.Context) ([]*CommandHistory, error) {
	if chcb.err != nil {
		return nil, chcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(chcb.builders))
	nodes := make([]*CommandHistory, len(chcb.builders))
	mutators := make([]Mutator, len(chcb.builders))
	for i := range chcb.builders {
		func(i int, root context.Context) {
			builder := chcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommandHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, chcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, chcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, chcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (chcb *CommandHistoryCreateBulk) SaveX(ctx context.Context) []*CommandHistory {
	v, err := chcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (chcb *CommandHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := chcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (chcb *CommandHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := chcb.Exec(ctx); err != nil {
		panic(err)
	}
}
