// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/devicecommand"
	"github.com/bengobox/iot-service/internal/ent/predicate"
)

// DeviceCommandDelete is the builder for deleting a DeviceCommand entity.
type DeviceCommandDelete struct {
	config
	hooks    []Hook
	mutation *DeviceCommandMutation
}

// Where appends a list predicates to the DeviceCommandDelete builder.
func (dcd *DeviceCommandDelete) Where(ps ...predicate.DeviceCommand) *DeviceCommandDelete {
	dcd.mutation.Where(ps...)
	return dcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dcd *DeviceCommandDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dcd.sqlExec, dcd.mutation, dcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dcd *DeviceCommandDelete) ExecX(ctx context.Context) int {
	n, err := dcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dcd *DeviceCommandDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(devicecommand.Table, sqlgraph.NewFieldSpec(devicecommand.FieldID, field.TypeUUID))
	if ps := dcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dcd.mutation.done = true
	return affected, err
}

// DeviceCommandDeleteOne is the builder for deleting a single DeviceCommand entity.
type DeviceCommandDeleteOne struct {
	dcd *DeviceCommandDelete
}

// Where appends a list predicates to the DeviceCommandDelete builder.
func (dcdo *DeviceCommandDeleteOne) Where(ps ...predicate.DeviceCommand) *DeviceCommandDeleteOne {
	dcdo.dcd.mutation.Where(ps...)
	return dcdo
}

// Exec executes the deletion query.
func (dcdo *DeviceCommandDeleteOne) Exec(ctx context.Context) error {
	n, err := dcdo.dcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{devicecommand.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dcdo *DeviceCommandDeleteOne) ExecX(ctx context.Context) {
	if err := dcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
