// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/iot-service/internal/ent/device"
	"github.com/bengobox/iot-service/internal/ent/devicegroup"
	"github.com/bengobox/iot-service/internal/ent/devicegroupmember"
	"github.com/google/uuid"
)

// DeviceGroupMember is the model entity for the DeviceGroupMember schema.
type DeviceGroupMember struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DeviceGroupID holds the value of the "device_group_id" field.
	DeviceGroupID uuid.UUID `json:"device_group_id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID uuid.UUID `json:"device_id,omitempty"`
	// AddedAt holds the value of the "added_at" field.
	AddedAt time.Time `json:"added_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeviceGroupMemberQuery when eager-loading is set.
	Edges        DeviceGroupMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeviceGroupMemberEdges holds the relations/edges for other nodes in the graph.
type DeviceGroupMemberEdges struct {
	// DeviceGroup holds the value of the device_group edge.
	DeviceGroup *DeviceGroup `json:"device_group,omitempty"`
	// Device holds the value of the device edge.
	Device *Device `json:"device,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DeviceGroupOrErr returns the DeviceGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeviceGroupMemberEdges) DeviceGroupOrErr() (*DeviceGroup, error) {
	if e.DeviceGroup != nil {
		return e.DeviceGroup, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: devicegroup.Label}
	}
	return nil, &NotLoadedError{edge: "device_group"}
}

// DeviceOrErr returns the Device value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeviceGroupMemberEdges) DeviceOrErr() (*Device, error) {
	if e.Device != nil {
		return e.Device, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: device.Label}
	}
	return nil, &NotLoadedError{edge: "device"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeviceGroupMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case devicegroupmember.FieldAddedAt:
			values[i] = new(sql.NullTime)
		case devicegroupmember.FieldID, devicegroupmember.FieldDeviceGroupID, devicegroupmember.FieldDeviceID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeviceGroupMember fields.
func (dgm *DeviceGroupMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case devicegroupmember.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				dgm.ID = *value
			}
		case devicegroupmember.FieldDeviceGroupID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field device_group_id", values[i])
			} else if value != nil {
				dgm.DeviceGroupID = *value
			}
		case devicegroupmember.FieldDeviceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value != nil {
				dgm.DeviceID = *value
			}
		case devicegroupmember.FieldAddedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field added_at", values[i])
			} else if value.Valid {
				dgm.AddedAt = value.Time
			}
		default:
			dgm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeviceGroupMember.
// This includes values selected through modifiers, order, etc.
func (dgm *DeviceGroupMember) Value(name string) (ent.Value, error) {
	return dgm.selectValues.Get(name)
}

// QueryDeviceGroup queries the "device_group" edge of the DeviceGroupMember entity.
func (dgm *DeviceGroupMember) QueryDeviceGroup() *DeviceGroupQuery {
	return NewDeviceGroupMemberClient(dgm.config).QueryDeviceGroup(dgm)
}

// QueryDevice queries the "device" edge of the DeviceGroupMember entity.
func (dgm *DeviceGroupMember) QueryDevice() *DeviceQuery {
	return NewDeviceGroupMemberClient(dgm.config).QueryDevice(dgm)
}

// Update returns a builder for updating this DeviceGroupMember.
// Note that you need to call DeviceGroupMember.Unwrap() before calling this method if this DeviceGroupMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (dgm *DeviceGroupMember) Update() *DeviceGroupMemberUpdateOne {
	return NewDeviceGroupMemberClient(dgm.config).UpdateOne(dgm)
}

// Unwrap unwraps the DeviceGroupMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dgm *DeviceGroupMember) Unwrap() *DeviceGroupMember {
	_tx, ok := dgm.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeviceGroupMember is not a transactional entity")
	}
	dgm.config.driver = _tx.drv
	return dgm
}

// String implements the fmt.Stringer.
func (dgm *DeviceGroupMember) String() string {
	var builder strings.Builder
	builder.WriteString("DeviceGroupMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", dgm.ID))
	builder.WriteString("device_group_id=")
	builder.WriteString(fmt.Sprintf("%v", dgm.DeviceGroupID))
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(fmt.Sprintf("%v", dgm.DeviceID))
	builder.WriteString(", ")
	builder.WriteString("added_at=")
	builder.WriteString(dgm.AddedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeviceGroupMembers is a parsable slice of DeviceGroupMember.
type DeviceGroupMembers []*DeviceGroupMember
