// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/iot-service/internal/ent/devicegroup"
	"github.com/google/uuid"
)

// DeviceGroup is the model entity for the DeviceGroup schema.
type DeviceGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// GroupType holds the value of the "group_type" field.
	GroupType string `json:"group_type,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeviceGroupQuery when eager-loading is set.
	Edges        DeviceGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeviceGroupEdges holds the relations/edges for other nodes in the graph.
type DeviceGroupEdges struct {
	// Members holds the value of the members edge.
	Members []*DeviceGroupMember `json:"members,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e DeviceGroupEdges) MembersOrErr() ([]*DeviceGroupMember, error) {
	if e.loadedTypes[0] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DeviceGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case devicegroup.FieldMetadata:
			values[i] = new([]byte)
		case devicegroup.FieldName, devicegroup.FieldDescription, devicegroup.FieldGroupType:
			values[i] = new(sql.NullString)
		case devicegroup.FieldCreatedAt, devicegroup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case devicegroup.FieldID, devicegroup.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DeviceGroup fields.
func (dg *DeviceGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case devicegroup.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				dg.ID = *value
			}
		case devicegroup.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				dg.TenantID = *value
			}
		case devicegroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				dg.Name = value.String
			}
		case devicegroup.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				dg.Description = value.String
			}
		case devicegroup.FieldGroupType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_type", values[i])
			} else if value.Valid {
				dg.GroupType = value.String
			}
		case devicegroup.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &dg.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case devicegroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				dg.CreatedAt = value.Time
			}
		case devicegroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				dg.UpdatedAt = value.Time
			}
		default:
			dg.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DeviceGroup.
// This includes values selected through modifiers, order, etc.
func (dg *DeviceGroup) Value(name string) (ent.Value, error) {
	return dg.selectValues.Get(name)
}

// QueryMembers queries the "members" edge of the DeviceGroup entity.
func (dg *DeviceGroup) QueryMembers() *DeviceGroupMemberQuery {
	return NewDeviceGroupClient(dg.config).QueryMembers(dg)
}

// Update returns a builder for updating this DeviceGroup.
// Note that you need to call DeviceGroup.Unwrap() before calling this method if this DeviceGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (dg *DeviceGroup) Update() *DeviceGroupUpdateOne {
	return NewDeviceGroupClient(dg.config).UpdateOne(dg)
}

// Unwrap unwraps the DeviceGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dg *DeviceGroup) Unwrap() *DeviceGroup {
	_tx, ok := dg.config.driver.(*txDriver)
	if !ok {
		panic("ent: DeviceGroup is not a transactional entity")
	}
	dg.config.driver = _tx.drv
	return dg
}

// String implements the fmt.Stringer.
func (dg *DeviceGroup) String() string {
	var builder strings.Builder
	builder.WriteString("DeviceGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", dg.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", dg.TenantID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(dg.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(dg.Description)
	builder.WriteString(", ")
	builder.WriteString("group_type=")
	builder.WriteString(dg.GroupType)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", dg.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(dg.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(dg.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DeviceGroups is a parsable slice of DeviceGroup.
type DeviceGroups []*DeviceGroup
