// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/deviceheartbeat"
	"github.com/bengobox/iot-service/internal/ent/predicate"
)

// DeviceHeartbeatDelete is the builder for deleting a DeviceHeartbeat entity.
type DeviceHeartbeatDelete struct {
	config
	hooks    []Hook
	mutation *DeviceHeartbeatMutation
}

// Where appends a list predicates to the DeviceHeartbeatDelete builder.
func (dhd *DeviceHeartbeatDelete) Where(ps ...predicate.DeviceHeartbeat) *DeviceHeartbeatDelete {
	dhd.mutation.Where(ps...)
	return dhd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dhd *DeviceHeartbeatDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dhd.sqlExec, dhd.mutation, dhd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dhd *DeviceHeartbeatDelete) ExecX(ctx context.Context) int {
	n, err := dhd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dhd *DeviceHeartbeatDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(deviceheartbeat.Table, sqlgraph.NewFieldSpec(deviceheartbeat.FieldID, field.TypeUUID))
	if ps := dhd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dhd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dhd.mutation.done = true
	return affected, err
}

// DeviceHeartbeatDeleteOne is the builder for deleting a single DeviceHeartbeat entity.
type DeviceHeartbeatDeleteOne struct {
	dhd *DeviceHeartbeatDelete
}

// Where appends a list predicates to the DeviceHeartbeatDelete builder.
func (dhdo *DeviceHeartbeatDeleteOne) Where(ps ...predicate.DeviceHeartbeat) *DeviceHeartbeatDeleteOne {
	dhdo.dhd.mutation.Where(ps...)
	return dhdo
}

// Exec executes the deletion query.
func (dhdo *DeviceHeartbeatDeleteOne) Exec(ctx context.Context) error {
	n, err := dhdo.dhd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{deviceheartbeat.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dhdo *DeviceHeartbeatDeleteOne) ExecX(ctx context.Context) {
	if err := dhdo.Exec(ctx); err != nil {
		panic(err)
	}
}
