// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/commandhistory"
	"github.com/bengobox/iot-service/internal/ent/device"
	"github.com/bengobox/iot-service/internal/ent/devicecommand"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// DeviceCommandQuery is the builder for querying DeviceCommand entities.
type DeviceCommandQuery struct {
	config
	ctx         *QueryContext
	order       []devicecommand.OrderOption
	inters      []Interceptor
	predicates  []predicate.DeviceCommand
	withDevice  *DeviceQuery
	withHistory *CommandHistoryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeviceCommandQuery builder.
func (dcq *DeviceCommandQuery) Where(ps ...predicate.DeviceCommand) *DeviceCommandQuery {
	dcq.predicates = append(dcq.predicates, ps...)
	return dcq
}

// Limit the number of records to be returned by this query.
func (dcq *DeviceCommandQuery) Limit(limit int) *DeviceCommandQuery {
	dcq.ctx.Limit = &limit
	return dcq
}

// Offset to start from.
func (dcq *DeviceCommandQuery) Offset(offset int) *DeviceCommandQuery {
	dcq.ctx.Offset = &offset
	return dcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dcq *DeviceCommandQuery) Unique(unique bool) *DeviceCommandQuery {
	dcq.ctx.Unique = &unique
	return dcq
}

// Order specifies how the records should be ordered.
func (dcq *DeviceCommandQuery) Order(o ...devicecommand.OrderOption) *DeviceCommandQuery {
	dcq.order = append(dcq.order, o...)
	return dcq
}

// QueryDevice chains the current query on the "device" edge.
func (dcq *DeviceCommandQuery) QueryDevice() *DeviceQuery {
	query := (&DeviceClient{config: dcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(devicecommand.Table, devicecommand.FieldID, selector),
			sqlgraph.To(device.Table, device.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, devicecommand.DeviceTable, devicecommand.DeviceColumn),
		)
		fromU = sqlgraph.SetNeighbors(dcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryHistory chains the current query on the "history" edge.
func (dcq *DeviceCommandQuery) QueryHistory() *CommandHistoryQuery {
	query := (&CommandHistoryClient{config: dcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(devicecommand.Table, devicecommand.FieldID, selector),
			sqlgraph.To(commandhistory.Table, commandhistory.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, devicecommand.HistoryTable, devicecommand.HistoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(dcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeviceCommand entity from the query.
// Returns a *NotFoundError when no DeviceCommand was found.
func (dcq *DeviceCommandQuery) First(ctx context.Context) (*DeviceCommand, error) {
	nodes, err := dcq.Limit(1).All(setContextOp(ctx, dcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{devicecommand.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dcq *DeviceCommandQuery) FirstX(ctx context.Context) *DeviceCommand {
	node, err := dcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeviceCommand ID from the query.
// Returns a *NotFoundError when no DeviceCommand ID was found.
func (dcq *DeviceCommandQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dcq.Limit(1).IDs(setContextOp(ctx, dcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{devicecommand.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dcq *DeviceCommandQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := dcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeviceCommand entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeviceCommand entity is found.
// Returns a *NotFoundError when no DeviceCommand entities are found.
func (dcq *DeviceCommandQuery) Only(ctx context.Context) (*DeviceCommand, error) {
	nodes, err := dcq.Limit(2).All(setContextOp(ctx, dcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{devicecommand.Label}
	default:
		return nil, &NotSingularError{devicecommand.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dcq *DeviceCommandQuery) OnlyX(ctx context.Context) *DeviceCommand {
	node, err := dcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeviceCommand ID in the query.
// Returns a *NotSingularError when more than one DeviceCommand ID is found.
// Returns a *NotFoundError when no entities are found.
func (dcq *DeviceCommandQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dcq.Limit(2).IDs(setContextOp(ctx, dcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{devicecommand.Label}
	default:
		err = &NotSingularError{devicecommand.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dcq *DeviceCommandQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := dcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeviceCommands.
func (dcq *DeviceCommandQuery) All(ctx context.Context) ([]*DeviceCommand, error) {
	ctx = setContextOp(ctx, dcq.ctx, "All")
	if err := dcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeviceCommand, *DeviceCommandQuery]()
	return withInterceptors[[]*DeviceCommand](ctx, dcq, qr, dcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dcq *DeviceCommandQuery) AllX(ctx context.Context) []*DeviceCommand {
	nodes, err := dcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeviceCommand IDs.
func (dcq *DeviceCommandQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if dcq.ctx.Unique == nil && dcq.path != nil {
		dcq.Unique(true)
	}
	ctx = setContextOp(ctx, dcq.ctx, "IDs")
	if err = dcq.Select(devicecommand.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dcq *DeviceCommandQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := dcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dcq *DeviceCommandQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dcq.ctx, "Count")
	if err := dcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dcq, querierCount[*DeviceCommandQuery](), dcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dcq *DeviceCommandQuery) CountX(ctx context.Context) int {
	count, err := dcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dcq *DeviceCommandQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dcq.ctx, "Exist")
	switch _, err := dcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dcq *DeviceCommandQuery) ExistX(ctx context.Context) bool {
	exist, err := dcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeviceCommandQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dcq *DeviceCommandQuery) Clone() *DeviceCommandQuery {
	if dcq == nil {
		return nil
	}
	return &DeviceCommandQuery{
		config:      dcq.config,
		ctx:         dcq.ctx.Clone(),
		order:       append([]devicecommand.OrderOption{}, dcq.order...),
		inters:      append([]Interceptor{}, dcq.inters...),
		predicates:  append([]predicate.DeviceCommand{}, dcq.predicates...),
		withDevice:  dcq.withDevice.Clone(),
		withHistory: dcq.withHistory.Clone(),
		// clone intermediate query.
		sql:  dcq.sql.Clone(),
		path: dcq.path,
	}
}

// WithDevice tells the query-builder to eager-load the nodes that are connected to
// the "device" edge. The optional arguments are used to configure the query builder of the edge.
func (dcq *DeviceCommandQuery) WithDevice(opts ...func(*DeviceQuery)) *DeviceCommandQuery {
	query := (&DeviceClient{config: dcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dcq.withDevice = query
	return dcq
}

// WithHistory tells the query-builder to eager-load the nodes that are connected to
// the "history" edge. The optional arguments are used to configure the query builder of the edge.
func (dcq *DeviceCommandQuery) WithHistory(opts ...func(*CommandHistoryQuery)) *DeviceCommandQuery {
	query := (&CommandHistoryClient{config: dcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dcq.withHistory = query
	return dcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeviceCommand.Query().
//		GroupBy(devicecommand.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dcq *DeviceCommandQuery) GroupBy(field string, fields ...string) *DeviceCommandGroupBy {
	dcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeviceCommandGroupBy{build: dcq}
	grbuild.flds = &dcq.ctx.Fields
	grbuild.label = devicecommand.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//	}
//
//	client.DeviceCommand.Query().
//		Select(devicecommand.FieldTenantID).
//		Scan(ctx, &v)
func (dcq *DeviceCommandQuery) Select(fields ...string) *DeviceCommandSelect {
	dcq.ctx.Fields = append(dcq.ctx.Fields, fields...)
	sbuild := &DeviceCommandSelect{DeviceCommandQuery: dcq}
	sbuild.label = devicecommand.Label
	sbuild.flds, sbuild.scan = &dcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeviceCommandSelect configured with the given aggregations.
func (dcq *DeviceCommandQuery) Aggregate(fns ...AggregateFunc) *DeviceCommandSelect {
	return dcq.Select().Aggregate(fns...)
}

func (dcq *DeviceCommandQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dcq); err != nil {
				return err
			}
		}
	}
	for _, f := range dcq.ctx.Fields {
		if !devicecommand.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dcq.path != nil {
		prev, err := dcq.path(ctx)
		if err != nil {
			return err
		}
		dcq.sql = prev
	}
	return nil
}

func (dcq *DeviceCommandQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeviceCommand, error) {
	var (
		nodes       = []*DeviceCommand{}
		_spec       = dcq.querySpec()
		loadedTypes = [2]bool{
			dcq.withDevice != nil,
			dcq.withHistory != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeviceCommand).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeviceCommand{config: dcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dcq.withDevice; query != nil {
		if err := dcq.loadDevice(ctx, query, nodes, nil,
			func(n *DeviceCommand, e *Device) { n.Edges.Device = e }); err != nil {
			return nil, err
		}
	}
	if query := dcq.withHistory; query != nil {
		if err := dcq.loadHistory(ctx, query, nodes,
			func(n *DeviceCommand) { n.Edges.History = []*CommandHistory{} },
			func(n *DeviceCommand, e *CommandHistory) { n.Edges.History = append(n.Edges.History, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dcq *DeviceCommandQuery) loadDevice(ctx context.Context, query *DeviceQuery, nodes []*DeviceCommand, init func(*DeviceCommand), assign func(*DeviceCommand, *Device)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DeviceCommand)
	for i := range nodes {
		fk := nodes[i].DeviceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(device.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "device_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (dcq *DeviceCommandQuery) loadHistory(ctx context.Context, query *CommandHistoryQuery, nodes []*DeviceCommand, init func(*DeviceCommand), assign func(*DeviceCommand, *CommandHistory)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*DeviceCommand)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(commandhistory.FieldCommandID)
	}
	query.Where(predicate.CommandHistory(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(devicecommand.HistoryColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CommandID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "command_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (dcq *DeviceCommandQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dcq.querySpec()
	_spec.Node.Columns = dcq.ctx.Fields
	if len(dcq.ctx.Fields) > 0 {
		_spec.Unique = dcq.ctx.Unique != nil && *dcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dcq.driver, _spec)
}

func (dcq *DeviceCommandQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(devicecommand.Table, devicecommand.Columns, sqlgraph.NewFieldSpec(devicecommand.FieldID, field.TypeUUID))
	_spec.From = dcq.sql
	if unique := dcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dcq.path != nil {
		_spec.Unique = true
	}
	if fields := dcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, devicecommand.FieldID)
		for i := range fields {
			if fields[i] != devicecommand.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if dcq.withDevice != nil {
			_spec.Node.AddColumnOnce(devicecommand.FieldDeviceID)
		}
	}
	if ps := dcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dcq *DeviceCommandQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dcq.driver.Dialect())
	t1 := builder.Table(devicecommand.Table)
	columns := dcq.ctx.Fields
	if len(columns) == 0 {
		columns = devicecommand.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dcq.sql != nil {
		selector = dcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dcq.ctx.Unique != nil && *dcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dcq.predicates {
		p(selector)
	}
	for _, p := range dcq.order {
		p(selector)
	}
	if offset := dcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeviceCommandGroupBy is the group-by builder for DeviceCommand entities.
type DeviceCommandGroupBy struct {
	selector
	build *DeviceCommandQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dcgb *DeviceCommandGroupBy) Aggregate(fns ...AggregateFunc) *DeviceCommandGroupBy {
	dcgb.fns = append(dcgb.fns, fns...)
	return dcgb
}

// Scan applies the selector query and scans the result into the given value.
func (dcgb *DeviceCommandGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dcgb.build.ctx, "GroupBy")
	if err := dcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceCommandQuery, *DeviceCommandGroupBy](ctx, dcgb.build, dcgb, dcgb.build.inters, v)
}

func (dcgb *DeviceCommandGroupBy) sqlScan(ctx context.Context, root *DeviceCommandQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dcgb.fns))
	for _, fn := range dcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dcgb.flds)+len(dcgb.fns))
		for _, f := range *dcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeviceCommandSelect is the builder for selecting fields of DeviceCommand entities.
type DeviceCommandSelect struct {
	*DeviceCommandQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dcs *DeviceCommandSelect) Aggregate(fns ...AggregateFunc) *DeviceCommandSelect {
	dcs.fns = append(dcs.fns, fns...)
	return dcs
}

// Scan applies the selector query and scans the result into the given value.
func (dcs *DeviceCommandSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dcs.ctx, "Select")
	if err := dcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceCommandQuery, *DeviceCommandSelect](ctx, dcs.DeviceCommandQuery, dcs, dcs.inters, v)
}

func (dcs *DeviceCommandSelect) sqlScan(ctx context.Context, root *DeviceCommandQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dcs.fns))
	for _, fn := range dcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
