// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/devicerule"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/bengobox/iot-service/internal/ent/ruleexecution"
	"github.com/google/uuid"
)

// DeviceRuleUpdate is the builder for updating DeviceRule entities.
type DeviceRuleUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceRuleMutation
}

// Where appends a list predicates to the DeviceRuleUpdate builder.
func (dru *DeviceRuleUpdate) Where(ps ...predicate.DeviceRule) *DeviceRuleUpdate {
	dru.mutation.Where(ps...)
	return dru
}

// SetTenantID sets the "tenant_id" field.
func (dru *DeviceRuleUpdate) SetTenantID(u uuid.UUID) *DeviceRuleUpdate {
	dru.mutation.SetTenantID(u)
	return dru
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (dru *DeviceRuleUpdate) SetNillableTenantID(u *uuid.UUID) *DeviceRuleUpdate {
	if u != nil {
		dru.SetTenantID(*u)
	}
	return dru
}

// SetName sets the "name" field.
func (dru *DeviceRuleUpdate) SetName(s string) *DeviceRuleUpdate {
	dru.mutation.SetName(s)
	return dru
}

// SetNillableName sets the "name" field if the given value is not nil.
func (dru *DeviceRuleUpdate) SetNillableName(s *string) *DeviceRuleUpdate {
	if s != nil {
		dru.SetName(*s)
	}
	return dru
}

// SetRuleType sets the "rule_type" field.
func (dru *DeviceRuleUpdate) SetRuleType(s string) *DeviceRuleUpdate {
	dru.mutation.SetRuleType(s)
	return dru
}

// SetNillableRuleType sets the "rule_type" field if the given value is not nil.
func (dru *DeviceRuleUpdate) SetNillableRuleType(s *string) *DeviceRuleUpdate {
	if s != nil {
		dru.SetRuleType(*s)
	}
	return dru
}

// SetTriggerConditions sets the "trigger_conditions" field.
func (dru *DeviceRuleUpdate) SetTriggerConditions(m map[string]interface{}) *DeviceRuleUpdate {
	dru.mutation.SetTriggerConditions(m)
	return dru
}

// ClearTriggerConditions clears the value of the "trigger_conditions" field.
func (dru *DeviceRuleUpdate) ClearTriggerConditions() *DeviceRuleUpdate {
	dru.mutation.ClearTriggerConditions()
	return dru
}

// SetAction sets the "action" field.
func (dru *DeviceRuleUpdate) SetAction(m map[string]interface{}) *DeviceRuleUpdate {
	dru.mutation.SetAction(m)
	return dru
}

// ClearAction clears the value of the "action" field.
func (dru *DeviceRuleUpdate) ClearAction() *DeviceRuleUpdate {
	dru.mutation.ClearAction()
	return dru
}

// SetIsActive sets the "is_active" field.
func (dru *DeviceRuleUpdate) SetIsActive(b bool) *DeviceRuleUpdate {
	dru.mutation.SetIsActive(b)
	return dru
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (dru *DeviceRuleUpdate) SetNillableIsActive(b *bool) *DeviceRuleUpdate {
	if b != nil {
		dru.SetIsActive(*b)
	}
	return dru
}

// SetUpdatedAt sets the "updated_at" field.
func (dru *DeviceRuleUpdate) SetUpdatedAt(t time.Time) *DeviceRuleUpdate {
	dru.mutation.SetUpdatedAt(t)
	return dru
}

// AddExecutionIDs adds the "executions" edge to the RuleExecution entity by IDs.
func (dru *DeviceRuleUpdate) AddExecutionIDs(ids ...uuid.UUID) *DeviceRuleUpdate {
	dru.mutation.AddExecutionIDs(ids...)
	return dru
}

// AddExecutions adds the "executions" edges to the RuleExecution entity.
func (dru *DeviceRuleUpdate) AddExecutions(r ...*RuleExecution) *DeviceRuleUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return dru.AddExecutionIDs(ids...)
}

// Mutation returns the DeviceRuleMutation object of the builder.
func (dru *DeviceRuleUpdate) Mutation() *DeviceRuleMutation {
	return dru.mutation
}

// ClearExecutions clears all "executions" edges to the RuleExecution entity.
func (dru *DeviceRuleUpdate) ClearExecutions() *DeviceRuleUpdate {
	dru.mutation.ClearExecutions()
	return dru
}

// RemoveExecutionIDs removes the "executions" edge to RuleExecution entities by IDs.
func (dru *DeviceRuleUpdate) RemoveExecutionIDs(ids ...uuid.UUID) *DeviceRuleUpdate {
	dru.mutation.RemoveExecutionIDs(ids...)
	return dru
}

// RemoveExecutions removes "executions" edges to RuleExecution entities.
func (dru *DeviceRuleUpdate) RemoveExecutions(r ...*RuleExecution) *DeviceRuleUpdate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return dru.RemoveExecutionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (dru *DeviceRuleUpdate) Save(ctx context.Context) (int, error) {
	dru.defaults()
	return withHooks(ctx, dru.sqlSave, dru.mutation, dru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (dru *DeviceRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := dru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (dru *DeviceRuleUpdate) Exec(ctx context.Context) error {
	_, err := dru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dru *DeviceRuleUpdate) ExecX(ctx context.Context) {
	if err := dru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dru *DeviceRuleUpdate) defaults() {
	if _, ok := dru.mutation.UpdatedAt(); !ok {
		v := devicerule.UpdateDefaultUpdatedAt()
		dru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dru *DeviceRuleUpdate) check() error {
	if v, ok := dru.mutation.Name(); ok {
		if err := devicerule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DeviceRule.name": %w`, err)}
		}
	}
	if v, ok := dru.mutation.RuleType(); ok {
		if err := devicerule.RuleTypeValidator(v); err != nil {
			return &ValidationError{Name: "rule_type", err: fmt.Errorf(`ent: validator failed for field "DeviceRule.rule_type": %w`, err)}
		}
	}
	return nil
}

func (dru *DeviceRuleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := dru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(devicerule.Table, devicerule.Columns, sqlgraph.NewFieldSpec(devicerule.FieldID, field.TypeUUID))
	if ps := dru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := dru.mutation.TenantID(); ok {
		_spec.SetField(devicerule.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := dru.mutation.Name(); ok {
		_spec.SetField(devicerule.FieldName, field.TypeString, value)
	}
	if value, ok := dru.mutation.RuleType(); ok {
		_spec.SetField(devicerule.FieldRuleType, field.TypeString, value)
	}
	if value, ok := dru.mutation.TriggerConditions(); ok {
		_spec.SetField(devicerule.FieldTriggerConditions, field.TypeJSON, value)
	}
	if dru.mutation.TriggerConditionsCleared() {
		_spec.ClearField(devicerule.FieldTriggerConditions, field.TypeJSON)
	}
	if value, ok := dru.mutation.Action(); ok {
		_spec.SetField(devicerule.FieldAction, field.TypeJSON, value)
	}
	if dru.mutation.ActionCleared() {
		_spec.ClearField(devicerule.FieldAction, field.TypeJSON)
	}
	if value, ok := dru.mutation.IsActive(); ok {
		_spec.SetField(devicerule.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := dru.mutation.UpdatedAt(); ok {
		_spec.SetField(devicerule.FieldUpdatedAt, field.TypeTime, value)
	}
	if dru.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   devicerule.ExecutionsTable,
			Columns: []string{devicerule.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dru.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !dru.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   devicerule.ExecutionsTable,
			Columns: []string{devicerule.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := dru.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   devicerule.ExecutionsTable,
			Columns: []string{devicerule.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, dru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{devicerule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	dru.mutation.done = true
	return n, nil
}

// DeviceRuleUpdateOne is the builder for updating a single DeviceRule entity.
type DeviceRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceRuleMutation
}

// SetTenantID sets the "tenant_id" field.
func (druo *DeviceRuleUpdateOne) SetTenantID(u uuid.UUID) *DeviceRuleUpdateOne {
	druo.mutation.SetTenantID(u)
	return druo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (druo *DeviceRuleUpdateOne) SetNillableTenantID(u *uuid.UUID) *DeviceRuleUpdateOne {
	if u != nil {
		druo.SetTenantID(*u)
	}
	return druo
}

// SetName sets the "name" field.
func (druo *DeviceRuleUpdateOne) SetName(s string) *DeviceRuleUpdateOne {
	druo.mutation.SetName(s)
	return druo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (druo *DeviceRuleUpdateOne) SetNillableName(s *string) *DeviceRuleUpdateOne {
	if s != nil {
		druo.SetName(*s)
	}
	return druo
}

// SetRuleType sets the "rule_type" field.
func (druo *DeviceRuleUpdateOne) SetRuleType(s string) *DeviceRuleUpdateOne {
	druo.mutation.SetRuleType(s)
	return druo
}

// SetNillableRuleType sets the "rule_type" field if the given value is not nil.
func (druo *DeviceRuleUpdateOne) SetNillableRuleType(s *string) *DeviceRuleUpdateOne {
	if s != nil {
		druo.SetRuleType(*s)
	}
	return druo
}

// SetTriggerConditions sets the "trigger_conditions" field.
func (druo *DeviceRuleUpdateOne) SetTriggerConditions(m map[string]interface{}) *DeviceRuleUpdateOne {
	druo.mutation.SetTriggerConditions(m)
	return druo
}

// ClearTriggerConditions clears the value of the "trigger_conditions" field.
func (druo *DeviceRuleUpdateOne) ClearTriggerConditions() *DeviceRuleUpdateOne {
	druo.mutation.ClearTriggerConditions()
	return druo
}

// SetAction sets the "action" field.
func (druo *DeviceRuleUpdateOne) SetAction(m map[string]interface{}) *DeviceRuleUpdateOne {
	druo.mutation.SetAction(m)
	return druo
}

// ClearAction clears the value of the "action" field.
func (druo *DeviceRuleUpdateOne) ClearAction() *DeviceRuleUpdateOne {
	druo.mutation.ClearAction()
	return druo
}

// SetIsActive sets the "is_active" field.
func (druo *DeviceRuleUpdateOne) SetIsActive(b bool) *DeviceRuleUpdateOne {
	druo.mutation.SetIsActive(b)
	return druo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (druo *DeviceRuleUpdateOne) SetNillableIsActive(b *bool) *DeviceRuleUpdateOne {
	if b != nil {
		druo.SetIsActive(*b)
	}
	return druo
}

// SetUpdatedAt sets the "updated_at" field.
func (druo *DeviceRuleUpdateOne) SetUpdatedAt(t time.Time) *DeviceRuleUpdateOne {
	druo.mutation.SetUpdatedAt(t)
	return druo
}

// AddExecutionIDs adds the "executions" edge to the RuleExecution entity by IDs.
func (druo *DeviceRuleUpdateOne) AddExecutionIDs(ids ...uuid.UUID) *DeviceRuleUpdateOne {
	druo.mutation.AddExecutionIDs(ids...)
	return druo
}

// AddExecutions adds the "executions" edges to the RuleExecution entity.
func (druo *DeviceRuleUpdateOne) AddExecutions(r ...*RuleExecution) *DeviceRuleUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return druo.AddExecutionIDs(ids...)
}

// Mutation returns the DeviceRuleMutation object of the builder.
func (druo *DeviceRuleUpdateOne) Mutation() *DeviceRuleMutation {
	return druo.mutation
}

// ClearExecutions clears all "executions" edges to the RuleExecution entity.
func (druo *DeviceRuleUpdateOne) ClearExecutions() *DeviceRuleUpdateOne {
	druo.mutation.ClearExecutions()
	return druo
}

// RemoveExecutionIDs removes the "executions" edge to RuleExecution entities by IDs.
func (druo *DeviceRuleUpdateOne) RemoveExecutionIDs(ids ...uuid.UUID) *DeviceRuleUpdateOne {
	druo.mutation.RemoveExecutionIDs(ids...)
	return druo
}

// RemoveExecutions removes "executions" edges to RuleExecution entities.
func (druo *DeviceRuleUpdateOne) RemoveExecutions(r ...*RuleExecution) *DeviceRuleUpdateOne {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return druo.RemoveExecutionIDs(ids...)
}

// Where appends a list predicates to the DeviceRuleUpdate builder.
func (druo *DeviceRuleUpdateOne) Where(ps ...predicate.DeviceRule) *DeviceRuleUpdateOne {
	druo.mutation.Where(ps...)
	return druo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (druo *DeviceRuleUpdateOne) Select(field string, fields ...string) *DeviceRuleUpdateOne {
	druo.fields = append([]string{field}, fields...)
	return druo
}

// Save executes the query and returns the updated DeviceRule entity.
func (druo *DeviceRuleUpdateOne) Save(ctx context.Context) (*DeviceRule, error) {
	druo.defaults()
	return withHooks(ctx, druo.sqlSave, druo.mutation, druo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (druo *DeviceRuleUpdateOne) SaveX(ctx context.Context) *DeviceRule {
	node, err := druo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (druo *DeviceRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := druo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (druo *DeviceRuleUpdateOne) ExecX(ctx context.Context) {
	if err := druo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (druo *DeviceRuleUpdateOne) defaults() {
	if _, ok := druo.mutation.UpdatedAt(); !ok {
		v := devicerule.UpdateDefaultUpdatedAt()
		druo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (druo *DeviceRuleUpdateOne) check() error {
	if v, ok := druo.mutation.Name(); ok {
		if err := devicerule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DeviceRule.name": %w`, err)}
		}
	}
	if v, ok := druo.mutation.RuleType(); ok {
		if err := devicerule.RuleTypeValidator(v); err != nil {
			return &ValidationError{Name: "rule_type", err: fmt.Errorf(`ent: validator failed for field "DeviceRule.rule_type": %w`, err)}
		}
	}
	return nil
}

func (druo *DeviceRuleUpdateOne) sqlSave(ctx context.Context) (_node *DeviceRule, err error) {
	if err := druo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(devicerule.Table, devicerule.Columns, sqlgraph.NewFieldSpec(devicerule.FieldID, field.TypeUUID))
	id, ok := druo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeviceRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := druo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, devicerule.FieldID)
		for _, f := range fields {
			if !devicerule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != devicerule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := druo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := druo.mutation.TenantID(); ok {
		_spec.SetField(devicerule.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := druo.mutation.Name(); ok {
		_spec.SetField(devicerule.FieldName, field.TypeString, value)
	}
	if value, ok := druo.mutation.RuleType(); ok {
		_spec.SetField(devicerule.FieldRuleType, field.TypeString, value)
	}
	if value, ok := druo.mutation.TriggerConditions(); ok {
		_spec.SetField(devicerule.FieldTriggerConditions, field.TypeJSON, value)
	}
	if druo.mutation.TriggerConditionsCleared() {
		_spec.ClearField(devicerule.FieldTriggerConditions, field.TypeJSON)
	}
	if value, ok := druo.mutation.Action(); ok {
		_spec.SetField(devicerule.FieldAction, field.TypeJSON, value)
	}
	if druo.mutation.ActionCleared() {
		_spec.ClearField(devicerule.FieldAction, field.TypeJSON)
	}
	if value, ok := druo.mutation.IsActive(); ok {
		_spec.SetField(devicerule.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := druo.mutation.UpdatedAt(); ok {
		_spec.SetField(devicerule.FieldUpdatedAt, field.TypeTime, value)
	}
	if druo.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   devicerule.ExecutionsTable,
			Columns: []string{devicerule.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := druo.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !druo.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   devicerule.ExecutionsTable,
			Columns: []string{devicerule.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := druo.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   devicerule.ExecutionsTable,
			Columns: []string{devicerule.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DeviceRule{config: druo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, druo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{devicerule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	druo.mutation.done = true
	return _node, nil
}
