// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/devicerule"
	"github.com/bengobox/iot-service/internal/ent/predicate"
)

// DeviceRuleDelete is the builder for deleting a DeviceRule entity.
type DeviceRuleDelete struct {
	config
	hooks    []Hook
	mutation *DeviceRuleMutation
}

// Where appends a list predicates to the DeviceRuleDelete builder.
func (drd *DeviceRuleDelete) Where(ps ...predicate.DeviceRule) *DeviceRuleDelete {
	drd.mutation.Where(ps...)
	return drd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (drd *DeviceRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, drd.sqlExec, drd.mutation, drd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (drd *DeviceRuleDelete) ExecX(ctx context.Context) int {
	n, err := drd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (drd *DeviceRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(devicerule.Table, sqlgraph.NewFieldSpec(devicerule.FieldID, field.TypeUUID))
	if ps := drd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, drd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	drd.mutation.done = true
	return affected, err
}

// DeviceRuleDeleteOne is the builder for deleting a single DeviceRule entity.
type DeviceRuleDeleteOne struct {
	drd *DeviceRuleDelete
}

// Where appends a list predicates to the DeviceRuleDelete builder.
func (drdo *DeviceRuleDeleteOne) Where(ps ...predicate.DeviceRule) *DeviceRuleDeleteOne {
	drdo.drd.mutation.Where(ps...)
	return drdo
}

// Exec executes the deletion query.
func (drdo *DeviceRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := drdo.drd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{devicerule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (drdo *DeviceRuleDeleteOne) ExecX(ctx context.Context) {
	if err := drdo.Exec(ctx); err != nil {
		panic(err)
	}
}
