// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/iot-service/internal/ent/device"
	"github.com/google/uuid"
)

// Device is the model entity for the Device schema.
type Device struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// DeviceCode holds the value of the "device_code" field.
	DeviceCode string `json:"device_code,omitempty"`
	// DeviceType holds the value of the "device_type" field.
	DeviceType string `json:"device_type,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Location holds the value of the "location" field.
	Location map[string]interface{} `json:"location,omitempty"`
	// GeoPoint holds the value of the "geo_point" field.
	GeoPoint string `json:"geo_point,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// RegisteredAt holds the value of the "registered_at" field.
	RegisteredAt time.Time `json:"registered_at,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt time.Time `json:"last_seen_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeviceQuery when eager-loading is set.
	Edges        DeviceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeviceEdges holds the relations/edges for other nodes in the graph.
type DeviceEdges struct {
	// Attributes holds the value of the attributes edge.
	Attributes []*DeviceAttribute `json:"attributes,omitempty"`
	// GroupMembers holds the value of the group_members edge.
	GroupMembers []*DeviceGroupMember `json:"group_members,omitempty"`
	// TelemetryData holds the value of the telemetry_data edge.
	TelemetryData []*TelemetryData `json:"telemetry_data,omitempty"`
	// Commands holds the value of the commands edge.
	Commands []*DeviceCommand `json:"commands,omitempty"`
	// Heartbeats holds the value of the heartbeats edge.
	Heartbeats []*DeviceHeartbeat `json:"heartbeats,omitempty"`
	// FirmwareUpdates holds the value of the firmware_updates edge.
	FirmwareUpdates []*FirmwareUpdate `json:"firmware_updates,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// AttributesOrErr returns the Attributes value or an error if the edge
// was not loaded in eager-loading.
func (e DeviceEdges) AttributesOrErr() ([]*DeviceAttribute, error) {
	if e.loadedTypes[0] {
		return e.Attributes, nil
	}
	return nil, &NotLoadedError{edge: "attributes"}
}

// GroupMembersOrErr returns the GroupMembers value or an error if the edge
// was not loaded in eager-loading.
func (e DeviceEdges) GroupMembersOrErr() ([]*DeviceGroupMember, error) {
	if e.loadedTypes[1] {
		return e.GroupMembers, nil
	}
	return nil, &NotLoadedError{edge: "group_members"}
}

// TelemetryDataOrErr returns the TelemetryData value or an error if the edge
// was not loaded in eager-loading.
func (e DeviceEdges) TelemetryDataOrErr() ([]*TelemetryData, error) {
	if e.loadedTypes[2] {
		return e.TelemetryData, nil
	}
	return nil, &NotLoadedError{edge: "telemetry_data"}
}

// CommandsOrErr returns the Commands value or an error if the edge
// was not loaded in eager-loading.
func (e DeviceEdges) CommandsOrErr() ([]*DeviceCommand, error) {
	if e.loadedTypes[3] {
		return e.Commands, nil
	}
	return nil, &NotLoadedError{edge: "commands"}
}

// HeartbeatsOrErr returns the Heartbeats value or an error if the edge
// was not loaded in eager-loading.
func (e DeviceEdges) HeartbeatsOrErr() ([]*DeviceHeartbeat, error) {
	if e.loadedTypes[4] {
		return e.Heartbeats, nil
	}
	return nil, &NotLoadedError{edge: "heartbeats"}
}

// FirmwareUpdatesOrErr returns the FirmwareUpdates value or an error if the edge
// was not loaded in eager-loading.
func (e DeviceEdges) FirmwareUpdatesOrErr() ([]*FirmwareUpdate, error) {
	if e.loadedTypes[5] {
		return e.FirmwareUpdates, nil
	}
	return nil, &NotLoadedError{edge: "firmware_updates"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Device) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case device.FieldLocation, device.FieldMetadata:
			values[i] = new([]byte)
		case device.FieldDeviceCode, device.FieldDeviceType, device.FieldName, device.FieldDescription, device.FieldStatus, device.FieldGeoPoint:
			values[i] = new(sql.NullString)
		case device.FieldRegisteredAt, device.FieldLastSeenAt, device.FieldCreatedAt, device.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case device.FieldID, device.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Device fields.
func (d *Device) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case device.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				d.ID = *value
			}
		case device.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				d.TenantID = *value
			}
		case device.FieldDeviceCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_code", values[i])
			} else if value.Valid {
				d.DeviceCode = value.String
			}
		case device.FieldDeviceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device_type", values[i])
			} else if value.Valid {
				d.DeviceType = value.String
			}
		case device.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				d.Name = value.String
			}
		case device.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				d.Description = value.String
			}
		case device.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				d.Status = value.String
			}
		case device.FieldLocation:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &d.Location); err != nil {
					return fmt.Errorf("unmarshal field location: %w", err)
				}
			}
		case device.FieldGeoPoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field geo_point", values[i])
			} else if value.Valid {
				d.GeoPoint = value.String
			}
		case device.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &d.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case device.FieldRegisteredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field registered_at", values[i])
			} else if value.Valid {
				d.RegisteredAt = value.Time
			}
		case device.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				d.LastSeenAt = value.Time
			}
		case device.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				d.CreatedAt = value.Time
			}
		case device.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				d.UpdatedAt = value.Time
			}
		default:
			d.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Device.
// This includes values selected through modifiers, order, etc.
func (d *Device) Value(name string) (ent.Value, error) {
	return d.selectValues.Get(name)
}

// QueryAttributes queries the "attributes" edge of the Device entity.
func (d *Device) QueryAttributes() *DeviceAttributeQuery {
	return NewDeviceClient(d.config).QueryAttributes(d)
}

// QueryGroupMembers queries the "group_members" edge of the Device entity.
func (d *Device) QueryGroupMembers() *DeviceGroupMemberQuery {
	return NewDeviceClient(d.config).QueryGroupMembers(d)
}

// QueryTelemetryData queries the "telemetry_data" edge of the Device entity.
func (d *Device) QueryTelemetryData() *TelemetryDataQuery {
	return NewDeviceClient(d.config).QueryTelemetryData(d)
}

// QueryCommands queries the "commands" edge of the Device entity.
func (d *Device) QueryCommands() *DeviceCommandQuery {
	return NewDeviceClient(d.config).QueryCommands(d)
}

// QueryHeartbeats queries the "heartbeats" edge of the Device entity.
func (d *Device) QueryHeartbeats() *DeviceHeartbeatQuery {
	return NewDeviceClient(d.config).QueryHeartbeats(d)
}

// QueryFirmwareUpdates queries the "firmware_updates" edge of the Device entity.
func (d *Device) QueryFirmwareUpdates() *FirmwareUpdateQuery {
	return NewDeviceClient(d.config).QueryFirmwareUpdates(d)
}

// Update returns a builder for updating this Device.
// Note that you need to call Device.Unwrap() before calling this method if this Device
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Device) Update() *DeviceUpdateOne {
	return NewDeviceClient(d.config).UpdateOne(d)
}

// Unwrap unwraps the Device entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Device) Unwrap() *Device {
	_tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Device is not a transactional entity")
	}
	d.config.driver = _tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Device) String() string {
	var builder strings.Builder
	builder.WriteString("Device(")
	builder.WriteString(fmt.Sprintf("id=%v, ", d.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", d.TenantID))
	builder.WriteString(", ")
	builder.WriteString("device_code=")
	builder.WriteString(d.DeviceCode)
	builder.WriteString(", ")
	builder.WriteString("device_type=")
	builder.WriteString(d.DeviceType)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(d.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(d.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(d.Status)
	builder.WriteString(", ")
	builder.WriteString("location=")
	builder.WriteString(fmt.Sprintf("%v", d.Location))
	builder.WriteString(", ")
	builder.WriteString("geo_point=")
	builder.WriteString(d.GeoPoint)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", d.Metadata))
	builder.WriteString(", ")
	builder.WriteString("registered_at=")
	builder.WriteString(d.RegisteredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen_at=")
	builder.WriteString(d.LastSeenAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(d.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(d.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Devices is a parsable slice of Device.
type Devices []*Device
