// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/devicegroup"
	"github.com/bengobox/iot-service/internal/ent/devicegroupmember"
	"github.com/google/uuid"
)

// DeviceGroupCreate is the builder for creating a DeviceGroup entity.
type DeviceGroupCreate struct {
	config
	mutation *DeviceGroupMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (dgc *DeviceGroupCreate) SetTenantID(u uuid.UUID) *DeviceGroupCreate {
	dgc.mutation.SetTenantID(u)
	return dgc
}

// SetName sets the "name" field.
func (dgc *DeviceGroupCreate) SetName(s string) *DeviceGroupCreate {
	dgc.mutation.SetName(s)
	return dgc
}

// SetDescription sets the "description" field.
func (dgc *DeviceGroupCreate) SetDescription(s string) *DeviceGroupCreate {
	dgc.mutation.SetDescription(s)
	return dgc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (dgc *DeviceGroupCreate) SetNillableDescription(s *string) *DeviceGroupCreate {
	if s != nil {
		dgc.SetDescription(*s)
	}
	return dgc
}

// SetGroupType sets the "group_type" field.
func (dgc *DeviceGroupCreate) SetGroupType(s string) *DeviceGroupCreate {
	dgc.mutation.SetGroupType(s)
	return dgc
}

// SetNillableGroupType sets the "group_type" field if the given value is not nil.
func (dgc *DeviceGroupCreate) SetNillableGroupType(s *string) *DeviceGroupCreate {
	if s != nil {
		dgc.SetGroupType(*s)
	}
	return dgc
}

// SetMetadata sets the "metadata" field.
func (dgc *DeviceGroupCreate) SetMetadata(m map[string]interface{}) *DeviceGroupCreate {
	dgc.mutation.SetMetadata(m)
	return dgc
}

// SetCreatedAt sets the "created_at" field.
func (dgc *DeviceGroupCreate) SetCreatedAt(t time.Time) *DeviceGroupCreate {
	dgc.mutation.SetCreatedAt(t)
	return dgc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (dgc *DeviceGroupCreate) SetNillableCreatedAt(t *time.Time) *DeviceGroupCreate {
	if t != nil {
		dgc.SetCreatedAt(*t)
	}
	return dgc
}

// SetUpdatedAt sets the "updated_at" field.
func (dgc *DeviceGroupCreate) SetUpdatedAt(t time.Time) *DeviceGroupCreate {
	dgc.mutation.SetUpdatedAt(t)
	return dgc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (dgc *DeviceGroupCreate) SetNillableUpdatedAt(t *time.Time) *DeviceGroupCreate {
	if t != nil {
		dgc.SetUpdatedAt(*t)
	}
	return dgc
}

// SetID sets the "id" field.
func (dgc *DeviceGroupCreate) SetID(u uuid.UUID) *DeviceGroupCreate {
	dgc.mutation.SetID(u)
	return dgc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (dgc *DeviceGroupCreate) SetNillableID(u *uuid.UUID) *DeviceGroupCreate {
	if u != nil {
		dgc.SetID(*u)
	}
	return dgc
}

// AddMemberIDs adds the "members" edge to the DeviceGroupMember entity by IDs.
func (dgc *DeviceGroupCreate) AddMemberIDs(ids ...uuid.UUID) *DeviceGroupCreate {
	dgc.mutation.AddMemberIDs(ids...)
	return dgc
}

// AddMembers adds the "members" edges to the DeviceGroupMember entity.
func (dgc *DeviceGroupCreate) AddMembers(d ...*DeviceGroupMember) *DeviceGroupCreate {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dgc.AddMemberIDs(ids...)
}

// Mutation returns the DeviceGroupMutation object of the builder.
func (dgc *DeviceGroupCreate) Mutation() *DeviceGroupMutation {
	return dgc.mutation
}

// Save creates the DeviceGroup in the database.
func (dgc *DeviceGroupCreate) Save(ctx context.Context) (*DeviceGroup, error) {
	dgc.defaults()
	return withHooks(ctx, dgc.sqlSave, dgc.mutation, dgc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dgc *DeviceGroupCreate) SaveX(ctx context.Context) *DeviceGroup {
	v, err := dgc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dgc *DeviceGroupCreate) Exec(ctx context.Context) error {
	_, err := dgc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dgc *DeviceGroupCreate) ExecX(ctx context.Context) {
	if err := dgc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dgc *DeviceGroupCreate) defaults() {
	if _, ok := dgc.mutation.GroupType(); !ok {
		v := devicegroup.DefaultGroupType
		dgc.mutation.SetGroupType(v)
	}
	if _, ok := dgc.mutation.CreatedAt(); !ok {
		v := devicegroup.DefaultCreatedAt()
		dgc.mutation.SetCreatedAt(v)
	}
	if _, ok := dgc.mutation.UpdatedAt(); !ok {
		v := devicegroup.DefaultUpdatedAt()
		dgc.mutation.SetUpdatedAt(v)
	}
	if _, ok := dgc.mutation.ID(); !ok {
		v := devicegroup.DefaultID()
		dgc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dgc *DeviceGroupCreate) check() error {
	if _, ok := dgc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "DeviceGroup.tenant_id"`)}
	}
	if _, ok := dgc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DeviceGroup.name"`)}
	}
	if v, ok := dgc.mutation.Name(); ok {
		if err := devicegroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DeviceGroup.name": %w`, err)}
		}
	}
	if _, ok := dgc.mutation.GroupType(); !ok {
		return &ValidationError{Name: "group_type", err: errors.New(`ent: missing required field "DeviceGroup.group_type"`)}
	}
	if _, ok := dgc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeviceGroup.created_at"`)}
	}
	if _, ok := dgc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DeviceGroup.updated_at"`)}
	}
	return nil
}

func (dgc *DeviceGroupCreate) sqlSave(ctx context.Context) (*DeviceGroup, error) {
	if err := dgc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dgc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dgc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	dgc.mutation.id = &_node.ID
	dgc.mutation.done = true
	return _node, nil
}

func (dgc *DeviceGroupCreate) createSpec() (*DeviceGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceGroup{config: dgc.config}
		_spec = sqlgraph.NewCreateSpec(devicegroup.Table, sqlgraph.NewFieldSpec(devicegroup.FieldID, field.TypeUUID))
	)
	if id, ok := dgc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := dgc.mutation.TenantID(); ok {
		_spec.SetField(devicegroup.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := dgc.mutation.Name(); ok {
		_spec.SetField(devicegroup.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := dgc.mutation.Description(); ok {
		_spec.SetField(devicegroup.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := dgc.mutation.GroupType(); ok {
		_spec.SetField(devicegroup.FieldGroupType, field.TypeString, value)
		_node.GroupType = value
	}
	if value, ok := dgc.mutation.Metadata(); ok {
		_spec.SetField(devicegroup.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := dgc.mutation.CreatedAt(); ok {
		_spec.SetField(devicegroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := dgc.mutation.UpdatedAt(); ok {
		_spec.SetField(devicegroup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := dgc.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   devicegroup.MembersTable,
			Columns: []string{devicegroup.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(devicegroupmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DeviceGroupCreateBulk is the builder for creating many DeviceGroup entities in bulk.
type DeviceGroupCreateBulk struct {
	config
	err      error
	builders []*DeviceGroupCreate
}

// Save creates the DeviceGroup entities in the database.
func (dgcb *DeviceGroupCreateBulk) Save(ctx context.Context) ([]*DeviceGroup, error) {
	if dgcb.err != nil {
		return nil, dgcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dgcb.builders))
	nodes := make([]*DeviceGroup, len(dgcb.builders))
	mutators := make([]Mutator, len(dgcb.builders))
	for i := range dgcb.builders {
		func(i int, root context.Context) {
			builder := dgcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dgcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dgcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dgcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dgcb *DeviceGroupCreateBulk) SaveX(ctx context.Context) []*DeviceGroup {
	v, err := dgcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dgcb *DeviceGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := dgcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dgcb *DeviceGroupCreateBulk) ExecX(ctx context.Context) {
	if err := dgcb.Exec(ctx); err != nil {
		panic(err)
	}
}
