// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/devicegroup"
	"github.com/bengobox/iot-service/internal/ent/devicegroupmember"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// DeviceGroupQuery is the builder for querying DeviceGroup entities.
type DeviceGroupQuery struct {
	config
	ctx         *QueryContext
	order       []devicegroup.OrderOption
	inters      []Interceptor
	predicates  []predicate.DeviceGroup
	withMembers *DeviceGroupMemberQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeviceGroupQuery builder.
func (dgq *DeviceGroupQuery) Where(ps ...predicate.DeviceGroup) *DeviceGroupQuery {
	dgq.predicates = append(dgq.predicates, ps...)
	return dgq
}

// Limit the number of records to be returned by this query.
func (dgq *DeviceGroupQuery) Limit(limit int) *DeviceGroupQuery {
	dgq.ctx.Limit = &limit
	return dgq
}

// Offset to start from.
func (dgq *DeviceGroupQuery) Offset(offset int) *DeviceGroupQuery {
	dgq.ctx.Offset = &offset
	return dgq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dgq *DeviceGroupQuery) Unique(unique bool) *DeviceGroupQuery {
	dgq.ctx.Unique = &unique
	return dgq
}

// Order specifies how the records should be ordered.
func (dgq *DeviceGroupQuery) Order(o ...devicegroup.OrderOption) *DeviceGroupQuery {
	dgq.order = append(dgq.order, o...)
	return dgq
}

// QueryMembers chains the current query on the "members" edge.
func (dgq *DeviceGroupQuery) QueryMembers() *DeviceGroupMemberQuery {
	query := (&DeviceGroupMemberClient{config: dgq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dgq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dgq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(devicegroup.Table, devicegroup.FieldID, selector),
			sqlgraph.To(devicegroupmember.Table, devicegroupmember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, devicegroup.MembersTable, devicegroup.MembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(dgq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeviceGroup entity from the query.
// Returns a *NotFoundError when no DeviceGroup was found.
func (dgq *DeviceGroupQuery) First(ctx context.Context) (*DeviceGroup, error) {
	nodes, err := dgq.Limit(1).All(setContextOp(ctx, dgq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{devicegroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dgq *DeviceGroupQuery) FirstX(ctx context.Context) *DeviceGroup {
	node, err := dgq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeviceGroup ID from the query.
// Returns a *NotFoundError when no DeviceGroup ID was found.
func (dgq *DeviceGroupQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dgq.Limit(1).IDs(setContextOp(ctx, dgq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{devicegroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dgq *DeviceGroupQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := dgq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeviceGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeviceGroup entity is found.
// Returns a *NotFoundError when no DeviceGroup entities are found.
func (dgq *DeviceGroupQuery) Only(ctx context.Context) (*DeviceGroup, error) {
	nodes, err := dgq.Limit(2).All(setContextOp(ctx, dgq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{devicegroup.Label}
	default:
		return nil, &NotSingularError{devicegroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dgq *DeviceGroupQuery) OnlyX(ctx context.Context) *DeviceGroup {
	node, err := dgq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeviceGroup ID in the query.
// Returns a *NotSingularError when more than one DeviceGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (dgq *DeviceGroupQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dgq.Limit(2).IDs(setContextOp(ctx, dgq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{devicegroup.Label}
	default:
		err = &NotSingularError{devicegroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dgq *DeviceGroupQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := dgq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeviceGroups.
func (dgq *DeviceGroupQuery) All(ctx context.Context) ([]*DeviceGroup, error) {
	ctx = setContextOp(ctx, dgq.ctx, "All")
	if err := dgq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeviceGroup, *DeviceGroupQuery]()
	return withInterceptors[[]*DeviceGroup](ctx, dgq, qr, dgq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dgq *DeviceGroupQuery) AllX(ctx context.Context) []*DeviceGroup {
	nodes, err := dgq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeviceGroup IDs.
func (dgq *DeviceGroupQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if dgq.ctx.Unique == nil && dgq.path != nil {
		dgq.Unique(true)
	}
	ctx = setContextOp(ctx, dgq.ctx, "IDs")
	if err = dgq.Select(devicegroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dgq *DeviceGroupQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := dgq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dgq *DeviceGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dgq.ctx, "Count")
	if err := dgq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dgq, querierCount[*DeviceGroupQuery](), dgq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dgq *DeviceGroupQuery) CountX(ctx context.Context) int {
	count, err := dgq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dgq *DeviceGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dgq.ctx, "Exist")
	switch _, err := dgq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dgq *DeviceGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := dgq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeviceGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dgq *DeviceGroupQuery) Clone() *DeviceGroupQuery {
	if dgq == nil {
		return nil
	}
	return &DeviceGroupQuery{
		config:      dgq.config,
		ctx:         dgq.ctx.Clone(),
		order:       append([]devicegroup.OrderOption{}, dgq.order...),
		inters:      append([]Interceptor{}, dgq.inters...),
		predicates:  append([]predicate.DeviceGroup{}, dgq.predicates...),
		withMembers: dgq.withMembers.Clone(),
		// clone intermediate query.
		sql:  dgq.sql.Clone(),
		path: dgq.path,
	}
}

// WithMembers tells the query-builder to eager-load the nodes that are connected to
// the "members" edge. The optional arguments are used to configure the query builder of the edge.
func (dgq *DeviceGroupQuery) WithMembers(opts ...func(*DeviceGroupMemberQuery)) *DeviceGroupQuery {
	query := (&DeviceGroupMemberClient{config: dgq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dgq.withMembers = query
	return dgq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeviceGroup.Query().
//		GroupBy(devicegroup.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dgq *DeviceGroupQuery) GroupBy(field string, fields ...string) *DeviceGroupGroupBy {
	dgq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeviceGroupGroupBy{build: dgq}
	grbuild.flds = &dgq.ctx.Fields
	grbuild.label = devicegroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID uuid.UUID `json:"tenant_id,omitempty"`
//	}
//
//	client.DeviceGroup.Query().
//		Select(devicegroup.FieldTenantID).
//		Scan(ctx, &v)
func (dgq *DeviceGroupQuery) Select(fields ...string) *DeviceGroupSelect {
	dgq.ctx.Fields = append(dgq.ctx.Fields, fields...)
	sbuild := &DeviceGroupSelect{DeviceGroupQuery: dgq}
	sbuild.label = devicegroup.Label
	sbuild.flds, sbuild.scan = &dgq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeviceGroupSelect configured with the given aggregations.
func (dgq *DeviceGroupQuery) Aggregate(fns ...AggregateFunc) *DeviceGroupSelect {
	return dgq.Select().Aggregate(fns...)
}

func (dgq *DeviceGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dgq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dgq); err != nil {
				return err
			}
		}
	}
	for _, f := range dgq.ctx.Fields {
		if !devicegroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dgq.path != nil {
		prev, err := dgq.path(ctx)
		if err != nil {
			return err
		}
		dgq.sql = prev
	}
	return nil
}

func (dgq *DeviceGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeviceGroup, error) {
	var (
		nodes       = []*DeviceGroup{}
		_spec       = dgq.querySpec()
		loadedTypes = [1]bool{
			dgq.withMembers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeviceGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeviceGroup{config: dgq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dgq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dgq.withMembers; query != nil {
		if err := dgq.loadMembers(ctx, query, nodes,
			func(n *DeviceGroup) { n.Edges.Members = []*DeviceGroupMember{} },
			func(n *DeviceGroup, e *DeviceGroupMember) { n.Edges.Members = append(n.Edges.Members, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dgq *DeviceGroupQuery) loadMembers(ctx context.Context, query *DeviceGroupMemberQuery, nodes []*DeviceGroup, init func(*DeviceGroup), assign func(*DeviceGroup, *DeviceGroupMember)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*DeviceGroup)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(devicegroupmember.FieldDeviceGroupID)
	}
	query.Where(predicate.DeviceGroupMember(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(devicegroup.MembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DeviceGroupID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "device_group_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (dgq *DeviceGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dgq.querySpec()
	_spec.Node.Columns = dgq.ctx.Fields
	if len(dgq.ctx.Fields) > 0 {
		_spec.Unique = dgq.ctx.Unique != nil && *dgq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dgq.driver, _spec)
}

func (dgq *DeviceGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(devicegroup.Table, devicegroup.Columns, sqlgraph.NewFieldSpec(devicegroup.FieldID, field.TypeUUID))
	_spec.From = dgq.sql
	if unique := dgq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dgq.path != nil {
		_spec.Unique = true
	}
	if fields := dgq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, devicegroup.FieldID)
		for i := range fields {
			if fields[i] != devicegroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dgq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dgq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dgq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dgq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dgq *DeviceGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dgq.driver.Dialect())
	t1 := builder.Table(devicegroup.Table)
	columns := dgq.ctx.Fields
	if len(columns) == 0 {
		columns = devicegroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dgq.sql != nil {
		selector = dgq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dgq.ctx.Unique != nil && *dgq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dgq.predicates {
		p(selector)
	}
	for _, p := range dgq.order {
		p(selector)
	}
	if offset := dgq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dgq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeviceGroupGroupBy is the group-by builder for DeviceGroup entities.
type DeviceGroupGroupBy struct {
	selector
	build *DeviceGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dggb *DeviceGroupGroupBy) Aggregate(fns ...AggregateFunc) *DeviceGroupGroupBy {
	dggb.fns = append(dggb.fns, fns...)
	return dggb
}

// Scan applies the selector query and scans the result into the given value.
func (dggb *DeviceGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dggb.build.ctx, "GroupBy")
	if err := dggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceGroupQuery, *DeviceGroupGroupBy](ctx, dggb.build, dggb, dggb.build.inters, v)
}

func (dggb *DeviceGroupGroupBy) sqlScan(ctx context.Context, root *DeviceGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dggb.fns))
	for _, fn := range dggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dggb.flds)+len(dggb.fns))
		for _, f := range *dggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeviceGroupSelect is the builder for selecting fields of DeviceGroup entities.
type DeviceGroupSelect struct {
	*DeviceGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dgs *DeviceGroupSelect) Aggregate(fns ...AggregateFunc) *DeviceGroupSelect {
	dgs.fns = append(dgs.fns, fns...)
	return dgs
}

// Scan applies the selector query and scans the result into the given value.
func (dgs *DeviceGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dgs.ctx, "Select")
	if err := dgs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceGroupQuery, *DeviceGroupSelect](ctx, dgs.DeviceGroupQuery, dgs, dgs.inters, v)
}

func (dgs *DeviceGroupSelect) sqlScan(ctx context.Context, root *DeviceGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dgs.fns))
	for _, fn := range dgs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dgs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dgs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
