// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/devicegroupmember"
	"github.com/bengobox/iot-service/internal/ent/predicate"
)

// DeviceGroupMemberDelete is the builder for deleting a DeviceGroupMember entity.
type DeviceGroupMemberDelete struct {
	config
	hooks    []Hook
	mutation *DeviceGroupMemberMutation
}

// Where appends a list predicates to the DeviceGroupMemberDelete builder.
func (dgmd *DeviceGroupMemberDelete) Where(ps ...predicate.DeviceGroupMember) *DeviceGroupMemberDelete {
	dgmd.mutation.Where(ps...)
	return dgmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dgmd *DeviceGroupMemberDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, dgmd.sqlExec, dgmd.mutation, dgmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (dgmd *DeviceGroupMemberDelete) ExecX(ctx context.Context) int {
	n, err := dgmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dgmd *DeviceGroupMemberDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(devicegroupmember.Table, sqlgraph.NewFieldSpec(devicegroupmember.FieldID, field.TypeUUID))
	if ps := dgmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, dgmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	dgmd.mutation.done = true
	return affected, err
}

// DeviceGroupMemberDeleteOne is the builder for deleting a single DeviceGroupMember entity.
type DeviceGroupMemberDeleteOne struct {
	dgmd *DeviceGroupMemberDelete
}

// Where appends a list predicates to the DeviceGroupMemberDelete builder.
func (dgmdo *DeviceGroupMemberDeleteOne) Where(ps ...predicate.DeviceGroupMember) *DeviceGroupMemberDeleteOne {
	dgmdo.dgmd.mutation.Where(ps...)
	return dgmdo
}

// Exec executes the deletion query.
func (dgmdo *DeviceGroupMemberDeleteOne) Exec(ctx context.Context) error {
	n, err := dgmdo.dgmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{devicegroupmember.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dgmdo *DeviceGroupMemberDeleteOne) ExecX(ctx context.Context) {
	if err := dgmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
