// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/device"
	"github.com/bengobox/iot-service/internal/ent/deviceattribute"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// DeviceAttributeQuery is the builder for querying DeviceAttribute entities.
type DeviceAttributeQuery struct {
	config
	ctx        *QueryContext
	order      []deviceattribute.OrderOption
	inters     []Interceptor
	predicates []predicate.DeviceAttribute
	withDevice *DeviceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeviceAttributeQuery builder.
func (daq *DeviceAttributeQuery) Where(ps ...predicate.DeviceAttribute) *DeviceAttributeQuery {
	daq.predicates = append(daq.predicates, ps...)
	return daq
}

// Limit the number of records to be returned by this query.
func (daq *DeviceAttributeQuery) Limit(limit int) *DeviceAttributeQuery {
	daq.ctx.Limit = &limit
	return daq
}

// Offset to start from.
func (daq *DeviceAttributeQuery) Offset(offset int) *DeviceAttributeQuery {
	daq.ctx.Offset = &offset
	return daq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (daq *DeviceAttributeQuery) Unique(unique bool) *DeviceAttributeQuery {
	daq.ctx.Unique = &unique
	return daq
}

// Order specifies how the records should be ordered.
func (daq *DeviceAttributeQuery) Order(o ...deviceattribute.OrderOption) *DeviceAttributeQuery {
	daq.order = append(daq.order, o...)
	return daq
}

// QueryDevice chains the current query on the "device" edge.
func (daq *DeviceAttributeQuery) QueryDevice() *DeviceQuery {
	query := (&DeviceClient{config: daq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := daq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := daq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deviceattribute.Table, deviceattribute.FieldID, selector),
			sqlgraph.To(device.Table, device.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deviceattribute.DeviceTable, deviceattribute.DeviceColumn),
		)
		fromU = sqlgraph.SetNeighbors(daq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeviceAttribute entity from the query.
// Returns a *NotFoundError when no DeviceAttribute was found.
func (daq *DeviceAttributeQuery) First(ctx context.Context) (*DeviceAttribute, error) {
	nodes, err := daq.Limit(1).All(setContextOp(ctx, daq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deviceattribute.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (daq *DeviceAttributeQuery) FirstX(ctx context.Context) *DeviceAttribute {
	node, err := daq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeviceAttribute ID from the query.
// Returns a *NotFoundError when no DeviceAttribute ID was found.
func (daq *DeviceAttributeQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = daq.Limit(1).IDs(setContextOp(ctx, daq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deviceattribute.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (daq *DeviceAttributeQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := daq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeviceAttribute entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeviceAttribute entity is found.
// Returns a *NotFoundError when no DeviceAttribute entities are found.
func (daq *DeviceAttributeQuery) Only(ctx context.Context) (*DeviceAttribute, error) {
	nodes, err := daq.Limit(2).All(setContextOp(ctx, daq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deviceattribute.Label}
	default:
		return nil, &NotSingularError{deviceattribute.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (daq *DeviceAttributeQuery) OnlyX(ctx context.Context) *DeviceAttribute {
	node, err := daq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeviceAttribute ID in the query.
// Returns a *NotSingularError when more than one DeviceAttribute ID is found.
// Returns a *NotFoundError when no entities are found.
func (daq *DeviceAttributeQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = daq.Limit(2).IDs(setContextOp(ctx, daq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deviceattribute.Label}
	default:
		err = &NotSingularError{deviceattribute.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (daq *DeviceAttributeQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := daq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeviceAttributes.
func (daq *DeviceAttributeQuery) All(ctx context.Context) ([]*DeviceAttribute, error) {
	ctx = setContextOp(ctx, daq.ctx, "All")
	if err := daq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeviceAttribute, *DeviceAttributeQuery]()
	return withInterceptors[[]*DeviceAttribute](ctx, daq, qr, daq.inters)
}

// AllX is like All, but panics if an error occurs.
func (daq *DeviceAttributeQuery) AllX(ctx context.Context) []*DeviceAttribute {
	nodes, err := daq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeviceAttribute IDs.
func (daq *DeviceAttributeQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if daq.ctx.Unique == nil && daq.path != nil {
		daq.Unique(true)
	}
	ctx = setContextOp(ctx, daq.ctx, "IDs")
	if err = daq.Select(deviceattribute.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (daq *DeviceAttributeQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := daq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (daq *DeviceAttributeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, daq.ctx, "Count")
	if err := daq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, daq, querierCount[*DeviceAttributeQuery](), daq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (daq *DeviceAttributeQuery) CountX(ctx context.Context) int {
	count, err := daq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (daq *DeviceAttributeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, daq.ctx, "Exist")
	switch _, err := daq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (daq *DeviceAttributeQuery) ExistX(ctx context.Context) bool {
	exist, err := daq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeviceAttributeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (daq *DeviceAttributeQuery) Clone() *DeviceAttributeQuery {
	if daq == nil {
		return nil
	}
	return &DeviceAttributeQuery{
		config:     daq.config,
		ctx:        daq.ctx.Clone(),
		order:      append([]deviceattribute.OrderOption{}, daq.order...),
		inters:     append([]Interceptor{}, daq.inters...),
		predicates: append([]predicate.DeviceAttribute{}, daq.predicates...),
		withDevice: daq.withDevice.Clone(),
		// clone intermediate query.
		sql:  daq.sql.Clone(),
		path: daq.path,
	}
}

// WithDevice tells the query-builder to eager-load the nodes that are connected to
// the "device" edge. The optional arguments are used to configure the query builder of the edge.
func (daq *DeviceAttributeQuery) WithDevice(opts ...func(*DeviceQuery)) *DeviceAttributeQuery {
	query := (&DeviceClient{config: daq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	daq.withDevice = query
	return daq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeviceID uuid.UUID `json:"device_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeviceAttribute.Query().
//		GroupBy(deviceattribute.FieldDeviceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (daq *DeviceAttributeQuery) GroupBy(field string, fields ...string) *DeviceAttributeGroupBy {
	daq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeviceAttributeGroupBy{build: daq}
	grbuild.flds = &daq.ctx.Fields
	grbuild.label = deviceattribute.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeviceID uuid.UUID `json:"device_id,omitempty"`
//	}
//
//	client.DeviceAttribute.Query().
//		Select(deviceattribute.FieldDeviceID).
//		Scan(ctx, &v)
func (daq *DeviceAttributeQuery) Select(fields ...string) *DeviceAttributeSelect {
	daq.ctx.Fields = append(daq.ctx.Fields, fields...)
	sbuild := &DeviceAttributeSelect{DeviceAttributeQuery: daq}
	sbuild.label = deviceattribute.Label
	sbuild.flds, sbuild.scan = &daq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeviceAttributeSelect configured with the given aggregations.
func (daq *DeviceAttributeQuery) Aggregate(fns ...AggregateFunc) *DeviceAttributeSelect {
	return daq.Select().Aggregate(fns...)
}

func (daq *DeviceAttributeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range daq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, daq); err != nil {
				return err
			}
		}
	}
	for _, f := range daq.ctx.Fields {
		if !deviceattribute.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if daq.path != nil {
		prev, err := daq.path(ctx)
		if err != nil {
			return err
		}
		daq.sql = prev
	}
	return nil
}

func (daq *DeviceAttributeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeviceAttribute, error) {
	var (
		nodes       = []*DeviceAttribute{}
		_spec       = daq.querySpec()
		loadedTypes = [1]bool{
			daq.withDevice != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeviceAttribute).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeviceAttribute{config: daq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, daq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := daq.withDevice; query != nil {
		if err := daq.loadDevice(ctx, query, nodes, nil,
			func(n *DeviceAttribute, e *Device) { n.Edges.Device = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (daq *DeviceAttributeQuery) loadDevice(ctx context.Context, query *DeviceQuery, nodes []*DeviceAttribute, init func(*DeviceAttribute), assign func(*DeviceAttribute, *Device)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DeviceAttribute)
	for i := range nodes {
		fk := nodes[i].DeviceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(device.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "device_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (daq *DeviceAttributeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := daq.querySpec()
	_spec.Node.Columns = daq.ctx.Fields
	if len(daq.ctx.Fields) > 0 {
		_spec.Unique = daq.ctx.Unique != nil && *daq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, daq.driver, _spec)
}

func (daq *DeviceAttributeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deviceattribute.Table, deviceattribute.Columns, sqlgraph.NewFieldSpec(deviceattribute.FieldID, field.TypeUUID))
	_spec.From = daq.sql
	if unique := daq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if daq.path != nil {
		_spec.Unique = true
	}
	if fields := daq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deviceattribute.FieldID)
		for i := range fields {
			if fields[i] != deviceattribute.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if daq.withDevice != nil {
			_spec.Node.AddColumnOnce(deviceattribute.FieldDeviceID)
		}
	}
	if ps := daq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := daq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := daq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := daq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (daq *DeviceAttributeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(daq.driver.Dialect())
	t1 := builder.Table(deviceattribute.Table)
	columns := daq.ctx.Fields
	if len(columns) == 0 {
		columns = deviceattribute.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if daq.sql != nil {
		selector = daq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if daq.ctx.Unique != nil && *daq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range daq.predicates {
		p(selector)
	}
	for _, p := range daq.order {
		p(selector)
	}
	if offset := daq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := daq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeviceAttributeGroupBy is the group-by builder for DeviceAttribute entities.
type DeviceAttributeGroupBy struct {
	selector
	build *DeviceAttributeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dagb *DeviceAttributeGroupBy) Aggregate(fns ...AggregateFunc) *DeviceAttributeGroupBy {
	dagb.fns = append(dagb.fns, fns...)
	return dagb
}

// Scan applies the selector query and scans the result into the given value.
func (dagb *DeviceAttributeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dagb.build.ctx, "GroupBy")
	if err := dagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceAttributeQuery, *DeviceAttributeGroupBy](ctx, dagb.build, dagb, dagb.build.inters, v)
}

func (dagb *DeviceAttributeGroupBy) sqlScan(ctx context.Context, root *DeviceAttributeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dagb.fns))
	for _, fn := range dagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dagb.flds)+len(dagb.fns))
		for _, f := range *dagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeviceAttributeSelect is the builder for selecting fields of DeviceAttribute entities.
type DeviceAttributeSelect struct {
	*DeviceAttributeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (das *DeviceAttributeSelect) Aggregate(fns ...AggregateFunc) *DeviceAttributeSelect {
	das.fns = append(das.fns, fns...)
	return das
}

// Scan applies the selector query and scans the result into the given value.
func (das *DeviceAttributeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, das.ctx, "Select")
	if err := das.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceAttributeQuery, *DeviceAttributeSelect](ctx, das.DeviceAttributeQuery, das, das.inters, v)
}

func (das *DeviceAttributeSelect) sqlScan(ctx context.Context, root *DeviceAttributeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(das.fns))
	for _, fn := range das.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*das.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := das.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
