// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/devicerule"
	"github.com/bengobox/iot-service/internal/ent/ruleexecution"
	"github.com/google/uuid"
)

// DeviceRuleCreate is the builder for creating a DeviceRule entity.
type DeviceRuleCreate struct {
	config
	mutation *DeviceRuleMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (drc *DeviceRuleCreate) SetTenantID(u uuid.UUID) *DeviceRuleCreate {
	drc.mutation.SetTenantID(u)
	return drc
}

// SetName sets the "name" field.
func (drc *DeviceRuleCreate) SetName(s string) *DeviceRuleCreate {
	drc.mutation.SetName(s)
	return drc
}

// SetRuleType sets the "rule_type" field.
func (drc *DeviceRuleCreate) SetRuleType(s string) *DeviceRuleCreate {
	drc.mutation.SetRuleType(s)
	return drc
}

// SetTriggerConditions sets the "trigger_conditions" field.
func (drc *DeviceRuleCreate) SetTriggerConditions(m map[string]interface{}) *DeviceRuleCreate {
	drc.mutation.SetTriggerConditions(m)
	return drc
}

// SetAction sets the "action" field.
func (drc *DeviceRuleCreate) SetAction(m map[string]interface{}) *DeviceRuleCreate {
	drc.mutation.SetAction(m)
	return drc
}

// SetIsActive sets the "is_active" field.
func (drc *DeviceRuleCreate) SetIsActive(b bool) *DeviceRuleCreate {
	drc.mutation.SetIsActive(b)
	return drc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (drc *DeviceRuleCreate) SetNillableIsActive(b *bool) *DeviceRuleCreate {
	if b != nil {
		drc.SetIsActive(*b)
	}
	return drc
}

// SetCreatedAt sets the "created_at" field.
func (drc *DeviceRuleCreate) SetCreatedAt(t time.Time) *DeviceRuleCreate {
	drc.mutation.SetCreatedAt(t)
	return drc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (drc *DeviceRuleCreate) SetNillableCreatedAt(t *time.Time) *DeviceRuleCreate {
	if t != nil {
		drc.SetCreatedAt(*t)
	}
	return drc
}

// SetUpdatedAt sets the "updated_at" field.
func (drc *DeviceRuleCreate) SetUpdatedAt(t time.Time) *DeviceRuleCreate {
	drc.mutation.SetUpdatedAt(t)
	return drc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (drc *DeviceRuleCreate) SetNillableUpdatedAt(t *time.Time) *DeviceRuleCreate {
	if t != nil {
		drc.SetUpdatedAt(*t)
	}
	return drc
}

// SetID sets the "id" field.
func (drc *DeviceRuleCreate) SetID(u uuid.UUID) *DeviceRuleCreate {
	drc.mutation.SetID(u)
	return drc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (drc *DeviceRuleCreate) SetNillableID(u *uuid.UUID) *DeviceRuleCreate {
	if u != nil {
		drc.SetID(*u)
	}
	return drc
}

// AddExecutionIDs adds the "executions" edge to the RuleExecution entity by IDs.
func (drc *DeviceRuleCreate) AddExecutionIDs(ids ...uuid.UUID) *DeviceRuleCreate {
	drc.mutation.AddExecutionIDs(ids...)
	return drc
}

// AddExecutions adds the "executions" edges to the RuleExecution entity.
func (drc *DeviceRuleCreate) AddExecutions(r ...*RuleExecution) *DeviceRuleCreate {
	ids := make([]uuid.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return drc.AddExecutionIDs(ids...)
}

// Mutation returns the DeviceRuleMutation object of the builder.
func (drc *DeviceRuleCreate) Mutation() *DeviceRuleMutation {
	return drc.mutation
}

// Save creates the DeviceRule in the database.
func (drc *DeviceRuleCreate) Save(ctx context.Context) (*DeviceRule, error) {
	drc.defaults()
	return withHooks(ctx, drc.sqlSave, drc.mutation, drc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (drc *DeviceRuleCreate) SaveX(ctx context.Context) *DeviceRule {
	v, err := drc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (drc *DeviceRuleCreate) Exec(ctx context.Context) error {
	_, err := drc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (drc *DeviceRuleCreate) ExecX(ctx context.Context) {
	if err := drc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (drc *DeviceRuleCreate) defaults() {
	if _, ok := drc.mutation.IsActive(); !ok {
		v := devicerule.DefaultIsActive
		drc.mutation.SetIsActive(v)
	}
	if _, ok := drc.mutation.CreatedAt(); !ok {
		v := devicerule.DefaultCreatedAt()
		drc.mutation.SetCreatedAt(v)
	}
	if _, ok := drc.mutation.UpdatedAt(); !ok {
		v := devicerule.DefaultUpdatedAt()
		drc.mutation.SetUpdatedAt(v)
	}
	if _, ok := drc.mutation.ID(); !ok {
		v := devicerule.DefaultID()
		drc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (drc *DeviceRuleCreate) check() error {
	if _, ok := drc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "DeviceRule.tenant_id"`)}
	}
	if _, ok := drc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DeviceRule.name"`)}
	}
	if v, ok := drc.mutation.Name(); ok {
		if err := devicerule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DeviceRule.name": %w`, err)}
		}
	}
	if _, ok := drc.mutation.RuleType(); !ok {
		return &ValidationError{Name: "rule_type", err: errors.New(`ent: missing required field "DeviceRule.rule_type"`)}
	}
	if v, ok := drc.mutation.RuleType(); ok {
		if err := devicerule.RuleTypeValidator(v); err != nil {
			return &ValidationError{Name: "rule_type", err: fmt.Errorf(`ent: validator failed for field "DeviceRule.rule_type": %w`, err)}
		}
	}
	if _, ok := drc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "DeviceRule.is_active"`)}
	}
	if _, ok := drc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeviceRule.created_at"`)}
	}
	if _, ok := drc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DeviceRule.updated_at"`)}
	}
	return nil
}

func (drc *DeviceRuleCreate) sqlSave(ctx context.Context) (*DeviceRule, error) {
	if err := drc.check(); err != nil {
		return nil, err
	}
	_node, _spec := drc.createSpec()
	if err := sqlgraph.CreateNode(ctx, drc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	drc.mutation.id = &_node.ID
	drc.mutation.done = true
	return _node, nil
}

func (drc *DeviceRuleCreate) createSpec() (*DeviceRule, *sqlgraph.CreateSpec) {
	var (
		_node = &DeviceRule{config: drc.config}
		_spec = sqlgraph.NewCreateSpec(devicerule.Table, sqlgraph.NewFieldSpec(devicerule.FieldID, field.TypeUUID))
	)
	if id, ok := drc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := drc.mutation.TenantID(); ok {
		_spec.SetField(devicerule.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := drc.mutation.Name(); ok {
		_spec.SetField(devicerule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := drc.mutation.RuleType(); ok {
		_spec.SetField(devicerule.FieldRuleType, field.TypeString, value)
		_node.RuleType = value
	}
	if value, ok := drc.mutation.TriggerConditions(); ok {
		_spec.SetField(devicerule.FieldTriggerConditions, field.TypeJSON, value)
		_node.TriggerConditions = value
	}
	if value, ok := drc.mutation.Action(); ok {
		_spec.SetField(devicerule.FieldAction, field.TypeJSON, value)
		_node.Action = value
	}
	if value, ok := drc.mutation.IsActive(); ok {
		_spec.SetField(devicerule.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := drc.mutation.CreatedAt(); ok {
		_spec.SetField(devicerule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := drc.mutation.UpdatedAt(); ok {
		_spec.SetField(devicerule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := drc.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   devicerule.ExecutionsTable,
			Columns: []string{devicerule.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DeviceRuleCreateBulk is the builder for creating many DeviceRule entities in bulk.
type DeviceRuleCreateBulk struct {
	config
	err      error
	builders []*DeviceRuleCreate
}

// Save creates the DeviceRule entities in the database.
func (drcb *DeviceRuleCreateBulk) Save(ctx context.Context) ([]*DeviceRule, error) {
	if drcb.err != nil {
		return nil, drcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(drcb.builders))
	nodes := make([]*DeviceRule, len(drcb.builders))
	mutators := make([]Mutator, len(drcb.builders))
	for i := range drcb.builders {
		func(i int, root context.Context) {
			builder := drcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeviceRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, drcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, drcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, drcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (drcb *DeviceRuleCreateBulk) SaveX(ctx context.Context) []*DeviceRule {
	v, err := drcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (drcb *DeviceRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := drcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (drcb *DeviceRuleCreateBulk) ExecX(ctx context.Context) {
	if err := drcb.Exec(ctx); err != nil {
		panic(err)
	}
}
