// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/device"
	"github.com/bengobox/iot-service/internal/ent/firmwareupdate"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// FirmwareUpdateUpdate is the builder for updating FirmwareUpdate entities.
type FirmwareUpdateUpdate struct {
	config
	hooks    []Hook
	mutation *FirmwareUpdateMutation
}

// Where appends a list predicates to the FirmwareUpdateUpdate builder.
func (fuu *FirmwareUpdateUpdate) Where(ps ...predicate.FirmwareUpdate) *FirmwareUpdateUpdate {
	fuu.mutation.Where(ps...)
	return fuu
}

// SetTenantID sets the "tenant_id" field.
func (fuu *FirmwareUpdateUpdate) SetTenantID(u uuid.UUID) *FirmwareUpdateUpdate {
	fuu.mutation.SetTenantID(u)
	return fuu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (fuu *FirmwareUpdateUpdate) SetNillableTenantID(u *uuid.UUID) *FirmwareUpdateUpdate {
	if u != nil {
		fuu.SetTenantID(*u)
	}
	return fuu
}

// SetDeviceID sets the "device_id" field.
func (fuu *FirmwareUpdateUpdate) SetDeviceID(u uuid.UUID) *FirmwareUpdateUpdate {
	fuu.mutation.SetDeviceID(u)
	return fuu
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (fuu *FirmwareUpdateUpdate) SetNillableDeviceID(u *uuid.UUID) *FirmwareUpdateUpdate {
	if u != nil {
		fuu.SetDeviceID(*u)
	}
	return fuu
}

// SetFirmwareVersion sets the "firmware_version" field.
func (fuu *FirmwareUpdateUpdate) SetFirmwareVersion(s string) *FirmwareUpdateUpdate {
	fuu.mutation.SetFirmwareVersion(s)
	return fuu
}

// SetNillableFirmwareVersion sets the "firmware_version" field if the given value is not nil.
func (fuu *FirmwareUpdateUpdate) SetNillableFirmwareVersion(s *string) *FirmwareUpdateUpdate {
	if s != nil {
		fuu.SetFirmwareVersion(*s)
	}
	return fuu
}

// SetUpdateStatus sets the "update_status" field.
func (fuu *FirmwareUpdateUpdate) SetUpdateStatus(s string) *FirmwareUpdateUpdate {
	fuu.mutation.SetUpdateStatus(s)
	return fuu
}

// SetNillableUpdateStatus sets the "update_status" field if the given value is not nil.
func (fuu *FirmwareUpdateUpdate) SetNillableUpdateStatus(s *string) *FirmwareUpdateUpdate {
	if s != nil {
		fuu.SetUpdateStatus(*s)
	}
	return fuu
}

// SetScheduledAt sets the "scheduled_at" field.
func (fuu *FirmwareUpdateUpdate) SetScheduledAt(t time.Time) *FirmwareUpdateUpdate {
	fuu.mutation.SetScheduledAt(t)
	return fuu
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (fuu *FirmwareUpdateUpdate) SetNillableScheduledAt(t *time.Time) *FirmwareUpdateUpdate {
	if t != nil {
		fuu.SetScheduledAt(*t)
	}
	return fuu
}

// ClearScheduledAt clears the value of the "scheduled_at" field.
func (fuu *FirmwareUpdateUpdate) ClearScheduledAt() *FirmwareUpdateUpdate {
	fuu.mutation.ClearScheduledAt()
	return fuu
}

// SetStartedAt sets the "started_at" field.
func (fuu *FirmwareUpdateUpdate) SetStartedAt(t time.Time) *FirmwareUpdateUpdate {
	fuu.mutation.SetStartedAt(t)
	return fuu
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (fuu *FirmwareUpdateUpdate) SetNillableStartedAt(t *time.Time) *FirmwareUpdateUpdate {
	if t != nil {
		fuu.SetStartedAt(*t)
	}
	return fuu
}

// ClearStartedAt clears the value of the "started_at" field.
func (fuu *FirmwareUpdateUpdate) ClearStartedAt() *FirmwareUpdateUpdate {
	fuu.mutation.ClearStartedAt()
	return fuu
}

// SetCompletedAt sets the "completed_at" field.
func (fuu *FirmwareUpdateUpdate) SetCompletedAt(t time.Time) *FirmwareUpdateUpdate {
	fuu.mutation.SetCompletedAt(t)
	return fuu
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (fuu *FirmwareUpdateUpdate) SetNillableCompletedAt(t *time.Time) *FirmwareUpdateUpdate {
	if t != nil {
		fuu.SetCompletedAt(*t)
	}
	return fuu
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (fuu *FirmwareUpdateUpdate) ClearCompletedAt() *FirmwareUpdateUpdate {
	fuu.mutation.ClearCompletedAt()
	return fuu
}

// SetErrorMessage sets the "error_message" field.
func (fuu *FirmwareUpdateUpdate) SetErrorMessage(s string) *FirmwareUpdateUpdate {
	fuu.mutation.SetErrorMessage(s)
	return fuu
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (fuu *FirmwareUpdateUpdate) SetNillableErrorMessage(s *string) *FirmwareUpdateUpdate {
	if s != nil {
		fuu.SetErrorMessage(*s)
	}
	return fuu
}

// ClearErrorMessage clears the value of the "error_message" field.
func (fuu *FirmwareUpdateUpdate) ClearErrorMessage() *FirmwareUpdateUpdate {
	fuu.mutation.ClearErrorMessage()
	return fuu
}

// SetMetadata sets the "metadata" field.
func (fuu *FirmwareUpdateUpdate) SetMetadata(m map[string]interface{}) *FirmwareUpdateUpdate {
	fuu.mutation.SetMetadata(m)
	return fuu
}

// ClearMetadata clears the value of the "metadata" field.
func (fuu *FirmwareUpdateUpdate) ClearMetadata() *FirmwareUpdateUpdate {
	fuu.mutation.ClearMetadata()
	return fuu
}

// SetDevice sets the "device" edge to the Device entity.
func (fuu *FirmwareUpdateUpdate) SetDevice(d *Device) *FirmwareUpdateUpdate {
	return fuu.SetDeviceID(d.ID)
}

// Mutation returns the FirmwareUpdateMutation object of the builder.
func (fuu *FirmwareUpdateUpdate) Mutation() *FirmwareUpdateMutation {
	return fuu.mutation
}

// ClearDevice clears the "device" edge to the Device entity.
func (fuu *FirmwareUpdateUpdate) ClearDevice() *FirmwareUpdateUpdate {
	fuu.mutation.ClearDevice()
	return fuu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fuu *FirmwareUpdateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, fuu.sqlSave, fuu.mutation, fuu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuu *FirmwareUpdateUpdate) SaveX(ctx context.Context) int {
	affected, err := fuu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fuu *FirmwareUpdateUpdate) Exec(ctx context.Context) error {
	_, err := fuu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuu *FirmwareUpdateUpdate) ExecX(ctx context.Context) {
	if err := fuu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fuu *FirmwareUpdateUpdate) check() error {
	if v, ok := fuu.mutation.FirmwareVersion(); ok {
		if err := firmwareupdate.FirmwareVersionValidator(v); err != nil {
			return &ValidationError{Name: "firmware_version", err: fmt.Errorf(`ent: validator failed for field "FirmwareUpdate.firmware_version": %w`, err)}
		}
	}
	if _, ok := fuu.mutation.DeviceID(); fuu.mutation.DeviceCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "FirmwareUpdate.device"`)
	}
	return nil
}

func (fuu *FirmwareUpdateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fuu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(firmwareupdate.Table, firmwareupdate.Columns, sqlgraph.NewFieldSpec(firmwareupdate.FieldID, field.TypeUUID))
	if ps := fuu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuu.mutation.TenantID(); ok {
		_spec.SetField(firmwareupdate.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := fuu.mutation.FirmwareVersion(); ok {
		_spec.SetField(firmwareupdate.FieldFirmwareVersion, field.TypeString, value)
	}
	if value, ok := fuu.mutation.UpdateStatus(); ok {
		_spec.SetField(firmwareupdate.FieldUpdateStatus, field.TypeString, value)
	}
	if value, ok := fuu.mutation.ScheduledAt(); ok {
		_spec.SetField(firmwareupdate.FieldScheduledAt, field.TypeTime, value)
	}
	if fuu.mutation.ScheduledAtCleared() {
		_spec.ClearField(firmwareupdate.FieldScheduledAt, field.TypeTime)
	}
	if value, ok := fuu.mutation.StartedAt(); ok {
		_spec.SetField(firmwareupdate.FieldStartedAt, field.TypeTime, value)
	}
	if fuu.mutation.StartedAtCleared() {
		_spec.ClearField(firmwareupdate.FieldStartedAt, field.TypeTime)
	}
	if value, ok := fuu.mutation.CompletedAt(); ok {
		_spec.SetField(firmwareupdate.FieldCompletedAt, field.TypeTime, value)
	}
	if fuu.mutation.CompletedAtCleared() {
		_spec.ClearField(firmwareupdate.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := fuu.mutation.ErrorMessage(); ok {
		_spec.SetField(firmwareupdate.FieldErrorMessage, field.TypeString, value)
	}
	if fuu.mutation.ErrorMessageCleared() {
		_spec.ClearField(firmwareupdate.FieldErrorMessage, field.TypeString)
	}
	if value, ok := fuu.mutation.Metadata(); ok {
		_spec.SetField(firmwareupdate.FieldMetadata, field.TypeJSON, value)
	}
	if fuu.mutation.MetadataCleared() {
		_spec.ClearField(firmwareupdate.FieldMetadata, field.TypeJSON)
	}
	if fuu.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   firmwareupdate.DeviceTable,
			Columns: []string{firmwareupdate.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuu.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   firmwareupdate.DeviceTable,
			Columns: []string{firmwareupdate.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fuu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{firmwareupdate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fuu.mutation.done = true
	return n, nil
}

// FirmwareUpdateUpdateOne is the builder for updating a single FirmwareUpdate entity.
type FirmwareUpdateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FirmwareUpdateMutation
}

// SetTenantID sets the "tenant_id" field.
func (fuuo *FirmwareUpdateUpdateOne) SetTenantID(u uuid.UUID) *FirmwareUpdateUpdateOne {
	fuuo.mutation.SetTenantID(u)
	return fuuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (fuuo *FirmwareUpdateUpdateOne) SetNillableTenantID(u *uuid.UUID) *FirmwareUpdateUpdateOne {
	if u != nil {
		fuuo.SetTenantID(*u)
	}
	return fuuo
}

// SetDeviceID sets the "device_id" field.
func (fuuo *FirmwareUpdateUpdateOne) SetDeviceID(u uuid.UUID) *FirmwareUpdateUpdateOne {
	fuuo.mutation.SetDeviceID(u)
	return fuuo
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (fuuo *FirmwareUpdateUpdateOne) SetNillableDeviceID(u *uuid.UUID) *FirmwareUpdateUpdateOne {
	if u != nil {
		fuuo.SetDeviceID(*u)
	}
	return fuuo
}

// SetFirmwareVersion sets the "firmware_version" field.
func (fuuo *FirmwareUpdateUpdateOne) SetFirmwareVersion(s string) *FirmwareUpdateUpdateOne {
	fuuo.mutation.SetFirmwareVersion(s)
	return fuuo
}

// SetNillableFirmwareVersion sets the "firmware_version" field if the given value is not nil.
func (fuuo *FirmwareUpdateUpdateOne) SetNillableFirmwareVersion(s *string) *FirmwareUpdateUpdateOne {
	if s != nil {
		fuuo.SetFirmwareVersion(*s)
	}
	return fuuo
}

// SetUpdateStatus sets the "update_status" field.
func (fuuo *FirmwareUpdateUpdateOne) SetUpdateStatus(s string) *FirmwareUpdateUpdateOne {
	fuuo.mutation.SetUpdateStatus(s)
	return fuuo
}

// SetNillableUpdateStatus sets the "update_status" field if the given value is not nil.
func (fuuo *FirmwareUpdateUpdateOne) SetNillableUpdateStatus(s *string) *FirmwareUpdateUpdateOne {
	if s != nil {
		fuuo.SetUpdateStatus(*s)
	}
	return fuuo
}

// SetScheduledAt sets the "scheduled_at" field.
func (fuuo *FirmwareUpdateUpdateOne) SetScheduledAt(t time.Time) *FirmwareUpdateUpdateOne {
	fuuo.mutation.SetScheduledAt(t)
	return fuuo
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (fuuo *FirmwareUpdateUpdateOne) SetNillableScheduledAt(t *time.Time) *FirmwareUpdateUpdateOne {
	if t != nil {
		fuuo.SetScheduledAt(*t)
	}
	return fuuo
}

// ClearScheduledAt clears the value of the "scheduled_at" field.
func (fuuo *FirmwareUpdateUpdateOne) ClearScheduledAt() *FirmwareUpdateUpdateOne {
	fuuo.mutation.ClearScheduledAt()
	return fuuo
}

// SetStartedAt sets the "started_at" field.
func (fuuo *FirmwareUpdateUpdateOne) SetStartedAt(t time.Time) *FirmwareUpdateUpdateOne {
	fuuo.mutation.SetStartedAt(t)
	return fuuo
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (fuuo *FirmwareUpdateUpdateOne) SetNillableStartedAt(t *time.Time) *FirmwareUpdateUpdateOne {
	if t != nil {
		fuuo.SetStartedAt(*t)
	}
	return fuuo
}

// ClearStartedAt clears the value of the "started_at" field.
func (fuuo *FirmwareUpdateUpdateOne) ClearStartedAt() *FirmwareUpdateUpdateOne {
	fuuo.mutation.ClearStartedAt()
	return fuuo
}

// SetCompletedAt sets the "completed_at" field.
func (fuuo *FirmwareUpdateUpdateOne) SetCompletedAt(t time.Time) *FirmwareUpdateUpdateOne {
	fuuo.mutation.SetCompletedAt(t)
	return fuuo
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (fuuo *FirmwareUpdateUpdateOne) SetNillableCompletedAt(t *time.Time) *FirmwareUpdateUpdateOne {
	if t != nil {
		fuuo.SetCompletedAt(*t)
	}
	return fuuo
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (fuuo *FirmwareUpdateUpdateOne) ClearCompletedAt() *FirmwareUpdateUpdateOne {
	fuuo.mutation.ClearCompletedAt()
	return fuuo
}

// SetErrorMessage sets the "error_message" field.
func (fuuo *FirmwareUpdateUpdateOne) SetErrorMessage(s string) *FirmwareUpdateUpdateOne {
	fuuo.mutation.SetErrorMessage(s)
	return fuuo
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (fuuo *FirmwareUpdateUpdateOne) SetNillableErrorMessage(s *string) *FirmwareUpdateUpdateOne {
	if s != nil {
		fuuo.SetErrorMessage(*s)
	}
	return fuuo
}

// ClearErrorMessage clears the value of the "error_message" field.
func (fuuo *FirmwareUpdateUpdateOne) ClearErrorMessage() *FirmwareUpdateUpdateOne {
	fuuo.mutation.ClearErrorMessage()
	return fuuo
}

// SetMetadata sets the "metadata" field.
func (fuuo *FirmwareUpdateUpdateOne) SetMetadata(m map[string]interface{}) *FirmwareUpdateUpdateOne {
	fuuo.mutation.SetMetadata(m)
	return fuuo
}

// ClearMetadata clears the value of the "metadata" field.
func (fuuo *FirmwareUpdateUpdateOne) ClearMetadata() *FirmwareUpdateUpdateOne {
	fuuo.mutation.ClearMetadata()
	return fuuo
}

// SetDevice sets the "device" edge to the Device entity.
func (fuuo *FirmwareUpdateUpdateOne) SetDevice(d *Device) *FirmwareUpdateUpdateOne {
	return fuuo.SetDeviceID(d.ID)
}

// Mutation returns the FirmwareUpdateMutation object of the builder.
func (fuuo *FirmwareUpdateUpdateOne) Mutation() *FirmwareUpdateMutation {
	return fuuo.mutation
}

// ClearDevice clears the "device" edge to the Device entity.
func (fuuo *FirmwareUpdateUpdateOne) ClearDevice() *FirmwareUpdateUpdateOne {
	fuuo.mutation.ClearDevice()
	return fuuo
}

// Where appends a list predicates to the FirmwareUpdateUpdate builder.
func (fuuo *FirmwareUpdateUpdateOne) Where(ps ...predicate.FirmwareUpdate) *FirmwareUpdateUpdateOne {
	fuuo.mutation.Where(ps...)
	return fuuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuuo *FirmwareUpdateUpdateOne) Select(field string, fields ...string) *FirmwareUpdateUpdateOne {
	fuuo.fields = append([]string{field}, fields...)
	return fuuo
}

// Save executes the query and returns the updated FirmwareUpdate entity.
func (fuuo *FirmwareUpdateUpdateOne) Save(ctx context.Context) (*FirmwareUpdate, error) {
	return withHooks(ctx, fuuo.sqlSave, fuuo.mutation, fuuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuuo *FirmwareUpdateUpdateOne) SaveX(ctx context.Context) *FirmwareUpdate {
	node, err := fuuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuuo *FirmwareUpdateUpdateOne) Exec(ctx context.Context) error {
	_, err := fuuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuuo *FirmwareUpdateUpdateOne) ExecX(ctx context.Context) {
	if err := fuuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fuuo *FirmwareUpdateUpdateOne) check() error {
	if v, ok := fuuo.mutation.FirmwareVersion(); ok {
		if err := firmwareupdate.FirmwareVersionValidator(v); err != nil {
			return &ValidationError{Name: "firmware_version", err: fmt.Errorf(`ent: validator failed for field "FirmwareUpdate.firmware_version": %w`, err)}
		}
	}
	if _, ok := fuuo.mutation.DeviceID(); fuuo.mutation.DeviceCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "FirmwareUpdate.device"`)
	}
	return nil
}

func (fuuo *FirmwareUpdateUpdateOne) sqlSave(ctx context.Context) (_node *FirmwareUpdate, err error) {
	if err := fuuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(firmwareupdate.Table, firmwareupdate.Columns, sqlgraph.NewFieldSpec(firmwareupdate.FieldID, field.TypeUUID))
	id, ok := fuuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FirmwareUpdate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, firmwareupdate.FieldID)
		for _, f := range fields {
			if !firmwareupdate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != firmwareupdate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuuo.mutation.TenantID(); ok {
		_spec.SetField(firmwareupdate.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := fuuo.mutation.FirmwareVersion(); ok {
		_spec.SetField(firmwareupdate.FieldFirmwareVersion, field.TypeString, value)
	}
	if value, ok := fuuo.mutation.UpdateStatus(); ok {
		_spec.SetField(firmwareupdate.FieldUpdateStatus, field.TypeString, value)
	}
	if value, ok := fuuo.mutation.ScheduledAt(); ok {
		_spec.SetField(firmwareupdate.FieldScheduledAt, field.TypeTime, value)
	}
	if fuuo.mutation.ScheduledAtCleared() {
		_spec.ClearField(firmwareupdate.FieldScheduledAt, field.TypeTime)
	}
	if value, ok := fuuo.mutation.StartedAt(); ok {
		_spec.SetField(firmwareupdate.FieldStartedAt, field.TypeTime, value)
	}
	if fuuo.mutation.StartedAtCleared() {
		_spec.ClearField(firmwareupdate.FieldStartedAt, field.TypeTime)
	}
	if value, ok := fuuo.mutation.CompletedAt(); ok {
		_spec.SetField(firmwareupdate.FieldCompletedAt, field.TypeTime, value)
	}
	if fuuo.mutation.CompletedAtCleared() {
		_spec.ClearField(firmwareupdate.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := fuuo.mutation.ErrorMessage(); ok {
		_spec.SetField(firmwareupdate.FieldErrorMessage, field.TypeString, value)
	}
	if fuuo.mutation.ErrorMessageCleared() {
		_spec.ClearField(firmwareupdate.FieldErrorMessage, field.TypeString)
	}
	if value, ok := fuuo.mutation.Metadata(); ok {
		_spec.SetField(firmwareupdate.FieldMetadata, field.TypeJSON, value)
	}
	if fuuo.mutation.MetadataCleared() {
		_spec.ClearField(firmwareupdate.FieldMetadata, field.TypeJSON)
	}
	if fuuo.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   firmwareupdate.DeviceTable,
			Columns: []string{firmwareupdate.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuuo.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   firmwareupdate.DeviceTable,
			Columns: []string{firmwareupdate.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FirmwareUpdate{config: fuuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{firmwareupdate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuuo.mutation.done = true
	return _node, nil
}
