// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/devicerule"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/bengobox/iot-service/internal/ent/ruleexecution"
	"github.com/google/uuid"
)

// RuleExecutionQuery is the builder for querying RuleExecution entities.
type RuleExecutionQuery struct {
	config
	ctx        *QueryContext
	order      []ruleexecution.OrderOption
	inters     []Interceptor
	predicates []predicate.RuleExecution
	withRule   *DeviceRuleQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RuleExecutionQuery builder.
func (req *RuleExecutionQuery) Where(ps ...predicate.RuleExecution) *RuleExecutionQuery {
	req.predicates = append(req.predicates, ps...)
	return req
}

// Limit the number of records to be returned by this query.
func (req *RuleExecutionQuery) Limit(limit int) *RuleExecutionQuery {
	req.ctx.Limit = &limit
	return req
}

// Offset to start from.
func (req *RuleExecutionQuery) Offset(offset int) *RuleExecutionQuery {
	req.ctx.Offset = &offset
	return req
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (req *RuleExecutionQuery) Unique(unique bool) *RuleExecutionQuery {
	req.ctx.Unique = &unique
	return req
}

// Order specifies how the records should be ordered.
func (req *RuleExecutionQuery) Order(o ...ruleexecution.OrderOption) *RuleExecutionQuery {
	req.order = append(req.order, o...)
	return req
}

// QueryRule chains the current query on the "rule" edge.
func (req *RuleExecutionQuery) QueryRule() *DeviceRuleQuery {
	query := (&DeviceRuleClient{config: req.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := req.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := req.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ruleexecution.Table, ruleexecution.FieldID, selector),
			sqlgraph.To(devicerule.Table, devicerule.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ruleexecution.RuleTable, ruleexecution.RuleColumn),
		)
		fromU = sqlgraph.SetNeighbors(req.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RuleExecution entity from the query.
// Returns a *NotFoundError when no RuleExecution was found.
func (req *RuleExecutionQuery) First(ctx context.Context) (*RuleExecution, error) {
	nodes, err := req.Limit(1).All(setContextOp(ctx, req.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ruleexecution.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (req *RuleExecutionQuery) FirstX(ctx context.Context) *RuleExecution {
	node, err := req.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RuleExecution ID from the query.
// Returns a *NotFoundError when no RuleExecution ID was found.
func (req *RuleExecutionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = req.Limit(1).IDs(setContextOp(ctx, req.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ruleexecution.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (req *RuleExecutionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := req.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RuleExecution entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RuleExecution entity is found.
// Returns a *NotFoundError when no RuleExecution entities are found.
func (req *RuleExecutionQuery) Only(ctx context.Context) (*RuleExecution, error) {
	nodes, err := req.Limit(2).All(setContextOp(ctx, req.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ruleexecution.Label}
	default:
		return nil, &NotSingularError{ruleexecution.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (req *RuleExecutionQuery) OnlyX(ctx context.Context) *RuleExecution {
	node, err := req.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RuleExecution ID in the query.
// Returns a *NotSingularError when more than one RuleExecution ID is found.
// Returns a *NotFoundError when no entities are found.
func (req *RuleExecutionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = req.Limit(2).IDs(setContextOp(ctx, req.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ruleexecution.Label}
	default:
		err = &NotSingularError{ruleexecution.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (req *RuleExecutionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := req.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RuleExecutions.
func (req *RuleExecutionQuery) All(ctx context.Context) ([]*RuleExecution, error) {
	ctx = setContextOp(ctx, req.ctx, "All")
	if err := req.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RuleExecution, *RuleExecutionQuery]()
	return withInterceptors[[]*RuleExecution](ctx, req, qr, req.inters)
}

// AllX is like All, but panics if an error occurs.
func (req *RuleExecutionQuery) AllX(ctx context.Context) []*RuleExecution {
	nodes, err := req.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RuleExecution IDs.
func (req *RuleExecutionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if req.ctx.Unique == nil && req.path != nil {
		req.Unique(true)
	}
	ctx = setContextOp(ctx, req.ctx, "IDs")
	if err = req.Select(ruleexecution.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (req *RuleExecutionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := req.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (req *RuleExecutionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, req.ctx, "Count")
	if err := req.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, req, querierCount[*RuleExecutionQuery](), req.inters)
}

// CountX is like Count, but panics if an error occurs.
func (req *RuleExecutionQuery) CountX(ctx context.Context) int {
	count, err := req.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (req *RuleExecutionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, req.ctx, "Exist")
	switch _, err := req.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (req *RuleExecutionQuery) ExistX(ctx context.Context) bool {
	exist, err := req.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RuleExecutionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (req *RuleExecutionQuery) Clone() *RuleExecutionQuery {
	if req == nil {
		return nil
	}
	return &RuleExecutionQuery{
		config:     req.config,
		ctx:        req.ctx.Clone(),
		order:      append([]ruleexecution.OrderOption{}, req.order...),
		inters:     append([]Interceptor{}, req.inters...),
		predicates: append([]predicate.RuleExecution{}, req.predicates...),
		withRule:   req.withRule.Clone(),
		// clone intermediate query.
		sql:  req.sql.Clone(),
		path: req.path,
	}
}

// WithRule tells the query-builder to eager-load the nodes that are connected to
// the "rule" edge. The optional arguments are used to configure the query builder of the edge.
func (req *RuleExecutionQuery) WithRule(opts ...func(*DeviceRuleQuery)) *RuleExecutionQuery {
	query := (&DeviceRuleClient{config: req.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	req.withRule = query
	return req
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RuleID uuid.UUID `json:"rule_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RuleExecution.Query().
//		GroupBy(ruleexecution.FieldRuleID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (req *RuleExecutionQuery) GroupBy(field string, fields ...string) *RuleExecutionGroupBy {
	req.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RuleExecutionGroupBy{build: req}
	grbuild.flds = &req.ctx.Fields
	grbuild.label = ruleexecution.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RuleID uuid.UUID `json:"rule_id,omitempty"`
//	}
//
//	client.RuleExecution.Query().
//		Select(ruleexecution.FieldRuleID).
//		Scan(ctx, &v)
func (req *RuleExecutionQuery) Select(fields ...string) *RuleExecutionSelect {
	req.ctx.Fields = append(req.ctx.Fields, fields...)
	sbuild := &RuleExecutionSelect{RuleExecutionQuery: req}
	sbuild.label = ruleexecution.Label
	sbuild.flds, sbuild.scan = &req.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RuleExecutionSelect configured with the given aggregations.
func (req *RuleExecutionQuery) Aggregate(fns ...AggregateFunc) *RuleExecutionSelect {
	return req.Select().Aggregate(fns...)
}

func (req *RuleExecutionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range req.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, req); err != nil {
				return err
			}
		}
	}
	for _, f := range req.ctx.Fields {
		if !ruleexecution.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if req.path != nil {
		prev, err := req.path(ctx)
		if err != nil {
			return err
		}
		req.sql = prev
	}
	return nil
}

func (req *RuleExecutionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RuleExecution, error) {
	var (
		nodes       = []*RuleExecution{}
		_spec       = req.querySpec()
		loadedTypes = [1]bool{
			req.withRule != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RuleExecution).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RuleExecution{config: req.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, req.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := req.withRule; query != nil {
		if err := req.loadRule(ctx, query, nodes, nil,
			func(n *RuleExecution, e *DeviceRule) { n.Edges.Rule = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (req *RuleExecutionQuery) loadRule(ctx context.Context, query *DeviceRuleQuery, nodes []*RuleExecution, init func(*RuleExecution), assign func(*RuleExecution, *DeviceRule)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*RuleExecution)
	for i := range nodes {
		fk := nodes[i].RuleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(devicerule.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "rule_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (req *RuleExecutionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := req.querySpec()
	_spec.Node.Columns = req.ctx.Fields
	if len(req.ctx.Fields) > 0 {
		_spec.Unique = req.ctx.Unique != nil && *req.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, req.driver, _spec)
}

func (req *RuleExecutionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ruleexecution.Table, ruleexecution.Columns, sqlgraph.NewFieldSpec(ruleexecution.FieldID, field.TypeUUID))
	_spec.From = req.sql
	if unique := req.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if req.path != nil {
		_spec.Unique = true
	}
	if fields := req.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ruleexecution.FieldID)
		for i := range fields {
			if fields[i] != ruleexecution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if req.withRule != nil {
			_spec.Node.AddColumnOnce(ruleexecution.FieldRuleID)
		}
	}
	if ps := req.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := req.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := req.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := req.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (req *RuleExecutionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(req.driver.Dialect())
	t1 := builder.Table(ruleexecution.Table)
	columns := req.ctx.Fields
	if len(columns) == 0 {
		columns = ruleexecution.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if req.sql != nil {
		selector = req.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if req.ctx.Unique != nil && *req.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range req.predicates {
		p(selector)
	}
	for _, p := range req.order {
		p(selector)
	}
	if offset := req.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := req.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RuleExecutionGroupBy is the group-by builder for RuleExecution entities.
type RuleExecutionGroupBy struct {
	selector
	build *RuleExecutionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (regb *RuleExecutionGroupBy) Aggregate(fns ...AggregateFunc) *RuleExecutionGroupBy {
	regb.fns = append(regb.fns, fns...)
	return regb
}

// Scan applies the selector query and scans the result into the given value.
func (regb *RuleExecutionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, regb.build.ctx, "GroupBy")
	if err := regb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RuleExecutionQuery, *RuleExecutionGroupBy](ctx, regb.build, regb, regb.build.inters, v)
}

func (regb *RuleExecutionGroupBy) sqlScan(ctx context.Context, root *RuleExecutionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(regb.fns))
	for _, fn := range regb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*regb.flds)+len(regb.fns))
		for _, f := range *regb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*regb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := regb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RuleExecutionSelect is the builder for selecting fields of RuleExecution entities.
type RuleExecutionSelect struct {
	*RuleExecutionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (res *RuleExecutionSelect) Aggregate(fns ...AggregateFunc) *RuleExecutionSelect {
	res.fns = append(res.fns, fns...)
	return res
}

// Scan applies the selector query and scans the result into the given value.
func (res *RuleExecutionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, res.ctx, "Select")
	if err := res.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RuleExecutionQuery, *RuleExecutionSelect](ctx, res.RuleExecutionQuery, res, res.inters, v)
}

func (res *RuleExecutionSelect) sqlScan(ctx context.Context, root *RuleExecutionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(res.fns))
	for _, fn := range res.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*res.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := res.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
