// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/iot-service/internal/ent/devicerule"
	"github.com/bengobox/iot-service/internal/ent/ruleexecution"
	"github.com/google/uuid"
)

// RuleExecution is the model entity for the RuleExecution schema.
type RuleExecution struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RuleID holds the value of the "rule_id" field.
	RuleID uuid.UUID `json:"rule_id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID uuid.UUID `json:"device_id,omitempty"`
	// TriggeredAt holds the value of the "triggered_at" field.
	TriggeredAt time.Time `json:"triggered_at,omitempty"`
	// ExecutionStatus holds the value of the "execution_status" field.
	ExecutionStatus string `json:"execution_status,omitempty"`
	// Result holds the value of the "result" field.
	Result map[string]interface{} `json:"result,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RuleExecutionQuery when eager-loading is set.
	Edges        RuleExecutionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RuleExecutionEdges holds the relations/edges for other nodes in the graph.
type RuleExecutionEdges struct {
	// Rule holds the value of the rule edge.
	Rule *DeviceRule `json:"rule,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RuleOrErr returns the Rule value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RuleExecutionEdges) RuleOrErr() (*DeviceRule, error) {
	if e.Rule != nil {
		return e.Rule, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: devicerule.Label}
	}
	return nil, &NotLoadedError{edge: "rule"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RuleExecution) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ruleexecution.FieldResult:
			values[i] = new([]byte)
		case ruleexecution.FieldExecutionStatus, ruleexecution.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case ruleexecution.FieldTriggeredAt:
			values[i] = new(sql.NullTime)
		case ruleexecution.FieldID, ruleexecution.FieldRuleID, ruleexecution.FieldDeviceID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RuleExecution fields.
func (re *RuleExecution) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ruleexecution.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				re.ID = *value
			}
		case ruleexecution.FieldRuleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field rule_id", values[i])
			} else if value != nil {
				re.RuleID = *value
			}
		case ruleexecution.FieldDeviceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value != nil {
				re.DeviceID = *value
			}
		case ruleexecution.FieldTriggeredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field triggered_at", values[i])
			} else if value.Valid {
				re.TriggeredAt = value.Time
			}
		case ruleexecution.FieldExecutionStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_status", values[i])
			} else if value.Valid {
				re.ExecutionStatus = value.String
			}
		case ruleexecution.FieldResult:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &re.Result); err != nil {
					return fmt.Errorf("unmarshal field result: %w", err)
				}
			}
		case ruleexecution.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				re.ErrorMessage = value.String
			}
		default:
			re.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RuleExecution.
// This includes values selected through modifiers, order, etc.
func (re *RuleExecution) Value(name string) (ent.Value, error) {
	return re.selectValues.Get(name)
}

// QueryRule queries the "rule" edge of the RuleExecution entity.
func (re *RuleExecution) QueryRule() *DeviceRuleQuery {
	return NewRuleExecutionClient(re.config).QueryRule(re)
}

// Update returns a builder for updating this RuleExecution.
// Note that you need to call RuleExecution.Unwrap() before calling this method if this RuleExecution
// was returned from a transaction, and the transaction was committed or rolled back.
func (re *RuleExecution) Update() *RuleExecutionUpdateOne {
	return NewRuleExecutionClient(re.config).UpdateOne(re)
}

// Unwrap unwraps the RuleExecution entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (re *RuleExecution) Unwrap() *RuleExecution {
	_tx, ok := re.config.driver.(*txDriver)
	if !ok {
		panic("ent: RuleExecution is not a transactional entity")
	}
	re.config.driver = _tx.drv
	return re
}

// String implements the fmt.Stringer.
func (re *RuleExecution) String() string {
	var builder strings.Builder
	builder.WriteString("RuleExecution(")
	builder.WriteString(fmt.Sprintf("id=%v, ", re.ID))
	builder.WriteString("rule_id=")
	builder.WriteString(fmt.Sprintf("%v", re.RuleID))
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(fmt.Sprintf("%v", re.DeviceID))
	builder.WriteString(", ")
	builder.WriteString("triggered_at=")
	builder.WriteString(re.TriggeredAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("execution_status=")
	builder.WriteString(re.ExecutionStatus)
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(fmt.Sprintf("%v", re.Result))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(re.ErrorMessage)
	builder.WriteByte(')')
	return builder.String()
}

// RuleExecutions is a parsable slice of RuleExecution.
type RuleExecutions []*RuleExecution
