// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/bengobox/iot-service/internal/ent/telemetrydata"
)

// TelemetryDataDelete is the builder for deleting a TelemetryData entity.
type TelemetryDataDelete struct {
	config
	hooks    []Hook
	mutation *TelemetryDataMutation
}

// Where appends a list predicates to the TelemetryDataDelete builder.
func (tdd *TelemetryDataDelete) Where(ps ...predicate.TelemetryData) *TelemetryDataDelete {
	tdd.mutation.Where(ps...)
	return tdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tdd *TelemetryDataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tdd.sqlExec, tdd.mutation, tdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tdd *TelemetryDataDelete) ExecX(ctx context.Context) int {
	n, err := tdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tdd *TelemetryDataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(telemetrydata.Table, sqlgraph.NewFieldSpec(telemetrydata.FieldID, field.TypeUUID))
	if ps := tdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tdd.mutation.done = true
	return affected, err
}

// TelemetryDataDeleteOne is the builder for deleting a single TelemetryData entity.
type TelemetryDataDeleteOne struct {
	tdd *TelemetryDataDelete
}

// Where appends a list predicates to the TelemetryDataDelete builder.
func (tddo *TelemetryDataDeleteOne) Where(ps ...predicate.TelemetryData) *TelemetryDataDeleteOne {
	tddo.tdd.mutation.Where(ps...)
	return tddo
}

// Exec executes the deletion query.
func (tddo *TelemetryDataDeleteOne) Exec(ctx context.Context) error {
	n, err := tddo.tdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{telemetrydata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tddo *TelemetryDataDeleteOne) ExecX(ctx context.Context) {
	if err := tddo.Exec(ctx); err != nil {
		panic(err)
	}
}
