// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/iot-service/internal/ent/device"
	"github.com/bengobox/iot-service/internal/ent/telemetrydata"
	"github.com/google/uuid"
)

// TelemetryDataCreate is the builder for creating a TelemetryData entity.
type TelemetryDataCreate struct {
	config
	mutation *TelemetryDataMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (tdc *TelemetryDataCreate) SetTenantID(u uuid.UUID) *TelemetryDataCreate {
	tdc.mutation.SetTenantID(u)
	return tdc
}

// SetDeviceID sets the "device_id" field.
func (tdc *TelemetryDataCreate) SetDeviceID(u uuid.UUID) *TelemetryDataCreate {
	tdc.mutation.SetDeviceID(u)
	return tdc
}

// SetMetricName sets the "metric_name" field.
func (tdc *TelemetryDataCreate) SetMetricName(s string) *TelemetryDataCreate {
	tdc.mutation.SetMetricName(s)
	return tdc
}

// SetMetricValue sets the "metric_value" field.
func (tdc *TelemetryDataCreate) SetMetricValue(f float64) *TelemetryDataCreate {
	tdc.mutation.SetMetricValue(f)
	return tdc
}

// SetUnit sets the "unit" field.
func (tdc *TelemetryDataCreate) SetUnit(s string) *TelemetryDataCreate {
	tdc.mutation.SetUnit(s)
	return tdc
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (tdc *TelemetryDataCreate) SetNillableUnit(s *string) *TelemetryDataCreate {
	if s != nil {
		tdc.SetUnit(*s)
	}
	return tdc
}

// SetTimestamp sets the "timestamp" field.
func (tdc *TelemetryDataCreate) SetTimestamp(t time.Time) *TelemetryDataCreate {
	tdc.mutation.SetTimestamp(t)
	return tdc
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (tdc *TelemetryDataCreate) SetNillableTimestamp(t *time.Time) *TelemetryDataCreate {
	if t != nil {
		tdc.SetTimestamp(*t)
	}
	return tdc
}

// SetGeoPoint sets the "geo_point" field.
func (tdc *TelemetryDataCreate) SetGeoPoint(s string) *TelemetryDataCreate {
	tdc.mutation.SetGeoPoint(s)
	return tdc
}

// SetNillableGeoPoint sets the "geo_point" field if the given value is not nil.
func (tdc *TelemetryDataCreate) SetNillableGeoPoint(s *string) *TelemetryDataCreate {
	if s != nil {
		tdc.SetGeoPoint(*s)
	}
	return tdc
}

// SetMetadata sets the "metadata" field.
func (tdc *TelemetryDataCreate) SetMetadata(m map[string]interface{}) *TelemetryDataCreate {
	tdc.mutation.SetMetadata(m)
	return tdc
}

// SetCreatedAt sets the "created_at" field.
func (tdc *TelemetryDataCreate) SetCreatedAt(t time.Time) *TelemetryDataCreate {
	tdc.mutation.SetCreatedAt(t)
	return tdc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tdc *TelemetryDataCreate) SetNillableCreatedAt(t *time.Time) *TelemetryDataCreate {
	if t != nil {
		tdc.SetCreatedAt(*t)
	}
	return tdc
}

// SetID sets the "id" field.
func (tdc *TelemetryDataCreate) SetID(u uuid.UUID) *TelemetryDataCreate {
	tdc.mutation.SetID(u)
	return tdc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tdc *TelemetryDataCreate) SetNillableID(u *uuid.UUID) *TelemetryDataCreate {
	if u != nil {
		tdc.SetID(*u)
	}
	return tdc
}

// SetDevice sets the "device" edge to the Device entity.
func (tdc *TelemetryDataCreate) SetDevice(d *Device) *TelemetryDataCreate {
	return tdc.SetDeviceID(d.ID)
}

// Mutation returns the TelemetryDataMutation object of the builder.
func (tdc *TelemetryDataCreate) Mutation() *TelemetryDataMutation {
	return tdc.mutation
}

// Save creates the TelemetryData in the database.
func (tdc *TelemetryDataCreate) Save(ctx context.Context) (*TelemetryData, error) {
	tdc.defaults()
	return withHooks(ctx, tdc.sqlSave, tdc.mutation, tdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tdc *TelemetryDataCreate) SaveX(ctx context.Context) *TelemetryData {
	v, err := tdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tdc *TelemetryDataCreate) Exec(ctx context.Context) error {
	_, err := tdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdc *TelemetryDataCreate) ExecX(ctx context.Context) {
	if err := tdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tdc *TelemetryDataCreate) defaults() {
	if _, ok := tdc.mutation.Timestamp(); !ok {
		v := telemetrydata.DefaultTimestamp()
		tdc.mutation.SetTimestamp(v)
	}
	if _, ok := tdc.mutation.CreatedAt(); !ok {
		v := telemetrydata.DefaultCreatedAt()
		tdc.mutation.SetCreatedAt(v)
	}
	if _, ok := tdc.mutation.ID(); !ok {
		v := telemetrydata.DefaultID()
		tdc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tdc *TelemetryDataCreate) check() error {
	if _, ok := tdc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TelemetryData.tenant_id"`)}
	}
	if _, ok := tdc.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "TelemetryData.device_id"`)}
	}
	if _, ok := tdc.mutation.MetricName(); !ok {
		return &ValidationError{Name: "metric_name", err: errors.New(`ent: missing required field "TelemetryData.metric_name"`)}
	}
	if v, ok := tdc.mutation.MetricName(); ok {
		if err := telemetrydata.MetricNameValidator(v); err != nil {
			return &ValidationError{Name: "metric_name", err: fmt.Errorf(`ent: validator failed for field "TelemetryData.metric_name": %w`, err)}
		}
	}
	if _, ok := tdc.mutation.MetricValue(); !ok {
		return &ValidationError{Name: "metric_value", err: errors.New(`ent: missing required field "TelemetryData.metric_value"`)}
	}
	if _, ok := tdc.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "TelemetryData.timestamp"`)}
	}
	if _, ok := tdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TelemetryData.created_at"`)}
	}
	if _, ok := tdc.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required edge "TelemetryData.device"`)}
	}
	return nil
}

func (tdc *TelemetryDataCreate) sqlSave(ctx context.Context) (*TelemetryData, error) {
	if err := tdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	tdc.mutation.id = &_node.ID
	tdc.mutation.done = true
	return _node, nil
}

func (tdc *TelemetryDataCreate) createSpec() (*TelemetryData, *sqlgraph.CreateSpec) {
	var (
		_node = &TelemetryData{config: tdc.config}
		_spec = sqlgraph.NewCreateSpec(telemetrydata.Table, sqlgraph.NewFieldSpec(telemetrydata.FieldID, field.TypeUUID))
	)
	if id, ok := tdc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tdc.mutation.TenantID(); ok {
		_spec.SetField(telemetrydata.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := tdc.mutation.MetricName(); ok {
		_spec.SetField(telemetrydata.FieldMetricName, field.TypeString, value)
		_node.MetricName = value
	}
	if value, ok := tdc.mutation.MetricValue(); ok {
		_spec.SetField(telemetrydata.FieldMetricValue, field.TypeFloat64, value)
		_node.MetricValue = value
	}
	if value, ok := tdc.mutation.Unit(); ok {
		_spec.SetField(telemetrydata.FieldUnit, field.TypeString, value)
		_node.Unit = value
	}
	if value, ok := tdc.mutation.Timestamp(); ok {
		_spec.SetField(telemetrydata.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := tdc.mutation.GeoPoint(); ok {
		_spec.SetField(telemetrydata.FieldGeoPoint, field.TypeString, value)
		_node.GeoPoint = value
	}
	if value, ok := tdc.mutation.Metadata(); ok {
		_spec.SetField(telemetrydata.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := tdc.mutation.CreatedAt(); ok {
		_spec.SetField(telemetrydata.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := tdc.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   telemetrydata.DeviceTable,
			Columns: []string{telemetrydata.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeviceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TelemetryDataCreateBulk is the builder for creating many TelemetryData entities in bulk.
type TelemetryDataCreateBulk struct {
	config
	err      error
	builders []*TelemetryDataCreate
}

// Save creates the TelemetryData entities in the database.
func (tdcb *TelemetryDataCreateBulk) Save(ctx context.Context) ([]*TelemetryData, error) {
	if tdcb.err != nil {
		return nil, tdcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tdcb.builders))
	nodes := make([]*TelemetryData, len(tdcb.builders))
	mutators := make([]Mutator, len(tdcb.builders))
	for i := range tdcb.builders {
		func(i int, root context.Context) {
			builder := tdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TelemetryDataMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tdcb *TelemetryDataCreateBulk) SaveX(ctx context.Context) []*TelemetryData {
	v, err := tdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tdcb *TelemetryDataCreateBulk) Exec(ctx context.Context) error {
	_, err := tdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdcb *TelemetryDataCreateBulk) ExecX(ctx context.Context) {
	if err := tdcb.Exec(ctx); err != nil {
		panic(err)
	}
}
