// Code generated by ent, DO NOT EDIT.

package firmwareupdate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldTenantID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldDeviceID, v))
}

// FirmwareVersion applies equality check predicate on the "firmware_version" field. It's identical to FirmwareVersionEQ.
func FirmwareVersion(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldFirmwareVersion, v))
}

// UpdateStatus applies equality check predicate on the "update_status" field. It's identical to UpdateStatusEQ.
func UpdateStatus(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldUpdateStatus, v))
}

// ScheduledAt applies equality check predicate on the "scheduled_at" field. It's identical to ScheduledAtEQ.
func ScheduledAt(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldScheduledAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldCompletedAt, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldErrorMessage, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldTenantID, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...uuid.UUID) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldDeviceID, vs...))
}

// FirmwareVersionEQ applies the EQ predicate on the "firmware_version" field.
func FirmwareVersionEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldFirmwareVersion, v))
}

// FirmwareVersionNEQ applies the NEQ predicate on the "firmware_version" field.
func FirmwareVersionNEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldFirmwareVersion, v))
}

// FirmwareVersionIn applies the In predicate on the "firmware_version" field.
func FirmwareVersionIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldFirmwareVersion, vs...))
}

// FirmwareVersionNotIn applies the NotIn predicate on the "firmware_version" field.
func FirmwareVersionNotIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldFirmwareVersion, vs...))
}

// FirmwareVersionGT applies the GT predicate on the "firmware_version" field.
func FirmwareVersionGT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldFirmwareVersion, v))
}

// FirmwareVersionGTE applies the GTE predicate on the "firmware_version" field.
func FirmwareVersionGTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldFirmwareVersion, v))
}

// FirmwareVersionLT applies the LT predicate on the "firmware_version" field.
func FirmwareVersionLT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldFirmwareVersion, v))
}

// FirmwareVersionLTE applies the LTE predicate on the "firmware_version" field.
func FirmwareVersionLTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldFirmwareVersion, v))
}

// FirmwareVersionContains applies the Contains predicate on the "firmware_version" field.
func FirmwareVersionContains(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContains(FieldFirmwareVersion, v))
}

// FirmwareVersionHasPrefix applies the HasPrefix predicate on the "firmware_version" field.
func FirmwareVersionHasPrefix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasPrefix(FieldFirmwareVersion, v))
}

// FirmwareVersionHasSuffix applies the HasSuffix predicate on the "firmware_version" field.
func FirmwareVersionHasSuffix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasSuffix(FieldFirmwareVersion, v))
}

// FirmwareVersionEqualFold applies the EqualFold predicate on the "firmware_version" field.
func FirmwareVersionEqualFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEqualFold(FieldFirmwareVersion, v))
}

// FirmwareVersionContainsFold applies the ContainsFold predicate on the "firmware_version" field.
func FirmwareVersionContainsFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContainsFold(FieldFirmwareVersion, v))
}

// UpdateStatusEQ applies the EQ predicate on the "update_status" field.
func UpdateStatusEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldUpdateStatus, v))
}

// UpdateStatusNEQ applies the NEQ predicate on the "update_status" field.
func UpdateStatusNEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldUpdateStatus, v))
}

// UpdateStatusIn applies the In predicate on the "update_status" field.
func UpdateStatusIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldUpdateStatus, vs...))
}

// UpdateStatusNotIn applies the NotIn predicate on the "update_status" field.
func UpdateStatusNotIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldUpdateStatus, vs...))
}

// UpdateStatusGT applies the GT predicate on the "update_status" field.
func UpdateStatusGT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldUpdateStatus, v))
}

// UpdateStatusGTE applies the GTE predicate on the "update_status" field.
func UpdateStatusGTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldUpdateStatus, v))
}

// UpdateStatusLT applies the LT predicate on the "update_status" field.
func UpdateStatusLT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldUpdateStatus, v))
}

// UpdateStatusLTE applies the LTE predicate on the "update_status" field.
func UpdateStatusLTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldUpdateStatus, v))
}

// UpdateStatusContains applies the Contains predicate on the "update_status" field.
func UpdateStatusContains(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContains(FieldUpdateStatus, v))
}

// UpdateStatusHasPrefix applies the HasPrefix predicate on the "update_status" field.
func UpdateStatusHasPrefix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasPrefix(FieldUpdateStatus, v))
}

// UpdateStatusHasSuffix applies the HasSuffix predicate on the "update_status" field.
func UpdateStatusHasSuffix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasSuffix(FieldUpdateStatus, v))
}

// UpdateStatusEqualFold applies the EqualFold predicate on the "update_status" field.
func UpdateStatusEqualFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEqualFold(FieldUpdateStatus, v))
}

// UpdateStatusContainsFold applies the ContainsFold predicate on the "update_status" field.
func UpdateStatusContainsFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContainsFold(FieldUpdateStatus, v))
}

// ScheduledAtEQ applies the EQ predicate on the "scheduled_at" field.
func ScheduledAtEQ(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldScheduledAt, v))
}

// ScheduledAtNEQ applies the NEQ predicate on the "scheduled_at" field.
func ScheduledAtNEQ(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldScheduledAt, v))
}

// ScheduledAtIn applies the In predicate on the "scheduled_at" field.
func ScheduledAtIn(vs ...time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldScheduledAt, vs...))
}

// ScheduledAtNotIn applies the NotIn predicate on the "scheduled_at" field.
func ScheduledAtNotIn(vs ...time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldScheduledAt, vs...))
}

// ScheduledAtGT applies the GT predicate on the "scheduled_at" field.
func ScheduledAtGT(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldScheduledAt, v))
}

// ScheduledAtGTE applies the GTE predicate on the "scheduled_at" field.
func ScheduledAtGTE(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldScheduledAt, v))
}

// ScheduledAtLT applies the LT predicate on the "scheduled_at" field.
func ScheduledAtLT(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldScheduledAt, v))
}

// ScheduledAtLTE applies the LTE predicate on the "scheduled_at" field.
func ScheduledAtLTE(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldScheduledAt, v))
}

// ScheduledAtIsNil applies the IsNil predicate on the "scheduled_at" field.
func ScheduledAtIsNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIsNull(FieldScheduledAt))
}

// ScheduledAtNotNil applies the NotNil predicate on the "scheduled_at" field.
func ScheduledAtNotNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotNull(FieldScheduledAt))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotNull(FieldCompletedAt))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldContainsFold(FieldErrorMessage, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.FieldNotNull(FieldMetadata))
}

// HasDevice applies the HasEdge predicate on the "device" edge.
func HasDevice() predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceWith applies the HasEdge predicate on the "device" edge with a given conditions (other predicates).
func HasDeviceWith(preds ...predicate.Device) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(func(s *sql.Selector) {
		step := newDeviceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FirmwareUpdate) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FirmwareUpdate) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FirmwareUpdate) predicate.FirmwareUpdate {
	return predicate.FirmwareUpdate(sql.NotPredicates(p))
}
