// Code generated by ent, DO NOT EDIT.

package commandhistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the commandhistory type in the database.
	Label = "command_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCommandID holds the string denoting the command_id field in the database.
	FieldCommandID = "command_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldOccurredAt holds the string denoting the occurred_at field in the database.
	FieldOccurredAt = "occurred_at"
	// EdgeCommand holds the string denoting the command edge name in mutations.
	EdgeCommand = "command"
	// Table holds the table name of the commandhistory in the database.
	Table = "command_histories"
	// CommandTable is the table that holds the command relation/edge.
	CommandTable = "command_histories"
	// CommandInverseTable is the table name for the DeviceCommand entity.
	// It exists in this package in order to avoid circular dependency with the "devicecommand" package.
	CommandInverseTable = "device_commands"
	// CommandColumn is the table column denoting the command relation/edge.
	CommandColumn = "command_id"
)

// Columns holds all SQL columns for commandhistory fields.
var Columns = []string{
	FieldID,
	FieldCommandID,
	FieldEventType,
	FieldPayload,
	FieldOccurredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultOccurredAt holds the default value on creation for the "occurred_at" field.
	DefaultOccurredAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the CommandHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCommandID orders the results by the command_id field.
func ByCommandID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommandID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByOccurredAt orders the results by the occurred_at field.
func ByOccurredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOccurredAt, opts...).ToFunc()
}

// ByCommandField orders the results by command field.
func ByCommandField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommandStep(), sql.OrderByField(field, opts...))
	}
}
func newCommandStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommandInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CommandTable, CommandColumn),
	)
}
