// Code generated by ent, DO NOT EDIT.

package deviceattribute

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the deviceattribute type in the database.
	Label = "device_attribute"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldAttributeKey holds the string denoting the attribute_key field in the database.
	FieldAttributeKey = "attribute_key"
	// FieldAttributeValue holds the string denoting the attribute_value field in the database.
	FieldAttributeValue = "attribute_value"
	// FieldValueType holds the string denoting the value_type field in the database.
	FieldValueType = "value_type"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeDevice holds the string denoting the device edge name in mutations.
	EdgeDevice = "device"
	// Table holds the table name of the deviceattribute in the database.
	Table = "device_attributes"
	// DeviceTable is the table that holds the device relation/edge.
	DeviceTable = "device_attributes"
	// DeviceInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DeviceInverseTable = "devices"
	// DeviceColumn is the table column denoting the device relation/edge.
	DeviceColumn = "device_id"
)

// Columns holds all SQL columns for deviceattribute fields.
var Columns = []string{
	FieldID,
	FieldDeviceID,
	FieldAttributeKey,
	FieldAttributeValue,
	FieldValueType,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AttributeKeyValidator is a validator for the "attribute_key" field. It is called by the builders before save.
	AttributeKeyValidator func(string) error
	// AttributeValueValidator is a validator for the "attribute_value" field. It is called by the builders before save.
	AttributeValueValidator func(string) error
	// DefaultValueType holds the default value on creation for the "value_type" field.
	DefaultValueType string
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the DeviceAttribute queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByAttributeKey orders the results by the attribute_key field.
func ByAttributeKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttributeKey, opts...).ToFunc()
}

// ByAttributeValue orders the results by the attribute_value field.
func ByAttributeValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttributeValue, opts...).ToFunc()
}

// ByValueType orders the results by the value_type field.
func ByValueType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValueType, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeviceField orders the results by device field.
func ByDeviceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeviceStep(), sql.OrderByField(field, opts...))
	}
}
func newDeviceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeviceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
	)
}
