// Code generated by ent, DO NOT EDIT.

package deviceheartbeat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the deviceheartbeat type in the database.
	Label = "device_heartbeat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldHeartbeatAt holds the string denoting the heartbeat_at field in the database.
	FieldHeartbeatAt = "heartbeat_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldBatteryLevel holds the string denoting the battery_level field in the database.
	FieldBatteryLevel = "battery_level"
	// FieldSignalStrength holds the string denoting the signal_strength field in the database.
	FieldSignalStrength = "signal_strength"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// EdgeDevice holds the string denoting the device edge name in mutations.
	EdgeDevice = "device"
	// Table holds the table name of the deviceheartbeat in the database.
	Table = "device_heartbeats"
	// DeviceTable is the table that holds the device relation/edge.
	DeviceTable = "device_heartbeats"
	// DeviceInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DeviceInverseTable = "devices"
	// DeviceColumn is the table column denoting the device relation/edge.
	DeviceColumn = "device_id"
)

// Columns holds all SQL columns for deviceheartbeat fields.
var Columns = []string{
	FieldID,
	FieldDeviceID,
	FieldHeartbeatAt,
	FieldStatus,
	FieldBatteryLevel,
	FieldSignalStrength,
	FieldMetadata,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultHeartbeatAt holds the default value on creation for the "heartbeat_at" field.
	DefaultHeartbeatAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the DeviceHeartbeat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByHeartbeatAt orders the results by the heartbeat_at field.
func ByHeartbeatAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeartbeatAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByBatteryLevel orders the results by the battery_level field.
func ByBatteryLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatteryLevel, opts...).ToFunc()
}

// BySignalStrength orders the results by the signal_strength field.
func BySignalStrength(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignalStrength, opts...).ToFunc()
}

// ByDeviceField orders the results by device field.
func ByDeviceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeviceStep(), sql.OrderByField(field, opts...))
	}
}
func newDeviceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeviceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
	)
}
