// Code generated by ent, DO NOT EDIT.

package deviceheartbeat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldLTE(FieldID, id))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEQ(FieldDeviceID, v))
}

// HeartbeatAt applies equality check predicate on the "heartbeat_at" field. It's identical to HeartbeatAtEQ.
func HeartbeatAt(v time.Time) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEQ(FieldHeartbeatAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEQ(FieldStatus, v))
}

// BatteryLevel applies equality check predicate on the "battery_level" field. It's identical to BatteryLevelEQ.
func BatteryLevel(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEQ(FieldBatteryLevel, v))
}

// SignalStrength applies equality check predicate on the "signal_strength" field. It's identical to SignalStrengthEQ.
func SignalStrength(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEQ(FieldSignalStrength, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...uuid.UUID) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNotIn(FieldDeviceID, vs...))
}

// HeartbeatAtEQ applies the EQ predicate on the "heartbeat_at" field.
func HeartbeatAtEQ(v time.Time) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEQ(FieldHeartbeatAt, v))
}

// HeartbeatAtNEQ applies the NEQ predicate on the "heartbeat_at" field.
func HeartbeatAtNEQ(v time.Time) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNEQ(FieldHeartbeatAt, v))
}

// HeartbeatAtIn applies the In predicate on the "heartbeat_at" field.
func HeartbeatAtIn(vs ...time.Time) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldIn(FieldHeartbeatAt, vs...))
}

// HeartbeatAtNotIn applies the NotIn predicate on the "heartbeat_at" field.
func HeartbeatAtNotIn(vs ...time.Time) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNotIn(FieldHeartbeatAt, vs...))
}

// HeartbeatAtGT applies the GT predicate on the "heartbeat_at" field.
func HeartbeatAtGT(v time.Time) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldGT(FieldHeartbeatAt, v))
}

// HeartbeatAtGTE applies the GTE predicate on the "heartbeat_at" field.
func HeartbeatAtGTE(v time.Time) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldGTE(FieldHeartbeatAt, v))
}

// HeartbeatAtLT applies the LT predicate on the "heartbeat_at" field.
func HeartbeatAtLT(v time.Time) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldLT(FieldHeartbeatAt, v))
}

// HeartbeatAtLTE applies the LTE predicate on the "heartbeat_at" field.
func HeartbeatAtLTE(v time.Time) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldLTE(FieldHeartbeatAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldContainsFold(FieldStatus, v))
}

// BatteryLevelEQ applies the EQ predicate on the "battery_level" field.
func BatteryLevelEQ(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEQ(FieldBatteryLevel, v))
}

// BatteryLevelNEQ applies the NEQ predicate on the "battery_level" field.
func BatteryLevelNEQ(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNEQ(FieldBatteryLevel, v))
}

// BatteryLevelIn applies the In predicate on the "battery_level" field.
func BatteryLevelIn(vs ...int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldIn(FieldBatteryLevel, vs...))
}

// BatteryLevelNotIn applies the NotIn predicate on the "battery_level" field.
func BatteryLevelNotIn(vs ...int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNotIn(FieldBatteryLevel, vs...))
}

// BatteryLevelGT applies the GT predicate on the "battery_level" field.
func BatteryLevelGT(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldGT(FieldBatteryLevel, v))
}

// BatteryLevelGTE applies the GTE predicate on the "battery_level" field.
func BatteryLevelGTE(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldGTE(FieldBatteryLevel, v))
}

// BatteryLevelLT applies the LT predicate on the "battery_level" field.
func BatteryLevelLT(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldLT(FieldBatteryLevel, v))
}

// BatteryLevelLTE applies the LTE predicate on the "battery_level" field.
func BatteryLevelLTE(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldLTE(FieldBatteryLevel, v))
}

// BatteryLevelIsNil applies the IsNil predicate on the "battery_level" field.
func BatteryLevelIsNil() predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldIsNull(FieldBatteryLevel))
}

// BatteryLevelNotNil applies the NotNil predicate on the "battery_level" field.
func BatteryLevelNotNil() predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNotNull(FieldBatteryLevel))
}

// SignalStrengthEQ applies the EQ predicate on the "signal_strength" field.
func SignalStrengthEQ(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldEQ(FieldSignalStrength, v))
}

// SignalStrengthNEQ applies the NEQ predicate on the "signal_strength" field.
func SignalStrengthNEQ(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNEQ(FieldSignalStrength, v))
}

// SignalStrengthIn applies the In predicate on the "signal_strength" field.
func SignalStrengthIn(vs ...int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldIn(FieldSignalStrength, vs...))
}

// SignalStrengthNotIn applies the NotIn predicate on the "signal_strength" field.
func SignalStrengthNotIn(vs ...int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNotIn(FieldSignalStrength, vs...))
}

// SignalStrengthGT applies the GT predicate on the "signal_strength" field.
func SignalStrengthGT(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldGT(FieldSignalStrength, v))
}

// SignalStrengthGTE applies the GTE predicate on the "signal_strength" field.
func SignalStrengthGTE(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldGTE(FieldSignalStrength, v))
}

// SignalStrengthLT applies the LT predicate on the "signal_strength" field.
func SignalStrengthLT(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldLT(FieldSignalStrength, v))
}

// SignalStrengthLTE applies the LTE predicate on the "signal_strength" field.
func SignalStrengthLTE(v int) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldLTE(FieldSignalStrength, v))
}

// SignalStrengthIsNil applies the IsNil predicate on the "signal_strength" field.
func SignalStrengthIsNil() predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldIsNull(FieldSignalStrength))
}

// SignalStrengthNotNil applies the NotNil predicate on the "signal_strength" field.
func SignalStrengthNotNil() predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNotNull(FieldSignalStrength))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.FieldNotNull(FieldMetadata))
}

// HasDevice applies the HasEdge predicate on the "device" edge.
func HasDevice() predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceWith applies the HasEdge predicate on the "device" edge with a given conditions (other predicates).
func HasDeviceWith(preds ...predicate.Device) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(func(s *sql.Selector) {
		step := newDeviceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeviceHeartbeat) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeviceHeartbeat) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeviceHeartbeat) predicate.DeviceHeartbeat {
	return predicate.DeviceHeartbeat(sql.NotPredicates(p))
}
