// Code generated by ent, DO NOT EDIT.

package ruleexecution

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the ruleexecution type in the database.
	Label = "rule_execution"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRuleID holds the string denoting the rule_id field in the database.
	FieldRuleID = "rule_id"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldTriggeredAt holds the string denoting the triggered_at field in the database.
	FieldTriggeredAt = "triggered_at"
	// FieldExecutionStatus holds the string denoting the execution_status field in the database.
	FieldExecutionStatus = "execution_status"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// EdgeRule holds the string denoting the rule edge name in mutations.
	EdgeRule = "rule"
	// Table holds the table name of the ruleexecution in the database.
	Table = "rule_executions"
	// RuleTable is the table that holds the rule relation/edge.
	RuleTable = "rule_executions"
	// RuleInverseTable is the table name for the DeviceRule entity.
	// It exists in this package in order to avoid circular dependency with the "devicerule" package.
	RuleInverseTable = "device_rules"
	// RuleColumn is the table column denoting the rule relation/edge.
	RuleColumn = "rule_id"
)

// Columns holds all SQL columns for ruleexecution fields.
var Columns = []string{
	FieldID,
	FieldRuleID,
	FieldDeviceID,
	FieldTriggeredAt,
	FieldExecutionStatus,
	FieldResult,
	FieldErrorMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTriggeredAt holds the default value on creation for the "triggered_at" field.
	DefaultTriggeredAt func() time.Time
	// DefaultExecutionStatus holds the default value on creation for the "execution_status" field.
	DefaultExecutionStatus string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the RuleExecution queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRuleID orders the results by the rule_id field.
func ByRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleID, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByTriggeredAt orders the results by the triggered_at field.
func ByTriggeredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggeredAt, opts...).ToFunc()
}

// ByExecutionStatus orders the results by the execution_status field.
func ByExecutionStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutionStatus, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByRuleField orders the results by rule field.
func ByRuleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRuleStep(), sql.OrderByField(field, opts...))
	}
}
func newRuleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RuleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RuleTable, RuleColumn),
	)
}
