// Code generated by ent, DO NOT EDIT.

package ruleexecution

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLTE(FieldID, id))
}

// RuleID applies equality check predicate on the "rule_id" field. It's identical to RuleIDEQ.
func RuleID(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldRuleID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldDeviceID, v))
}

// TriggeredAt applies equality check predicate on the "triggered_at" field. It's identical to TriggeredAtEQ.
func TriggeredAt(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldTriggeredAt, v))
}

// ExecutionStatus applies equality check predicate on the "execution_status" field. It's identical to ExecutionStatusEQ.
func ExecutionStatus(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldExecutionStatus, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldErrorMessage, v))
}

// RuleIDEQ applies the EQ predicate on the "rule_id" field.
func RuleIDEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldRuleID, v))
}

// RuleIDNEQ applies the NEQ predicate on the "rule_id" field.
func RuleIDNEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldRuleID, v))
}

// RuleIDIn applies the In predicate on the "rule_id" field.
func RuleIDIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldRuleID, vs...))
}

// RuleIDNotIn applies the NotIn predicate on the "rule_id" field.
func RuleIDNotIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldRuleID, vs...))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v uuid.UUID) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDIsNil applies the IsNil predicate on the "device_id" field.
func DeviceIDIsNil() predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIsNull(FieldDeviceID))
}

// DeviceIDNotNil applies the NotNil predicate on the "device_id" field.
func DeviceIDNotNil() predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotNull(FieldDeviceID))
}

// TriggeredAtEQ applies the EQ predicate on the "triggered_at" field.
func TriggeredAtEQ(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldTriggeredAt, v))
}

// TriggeredAtNEQ applies the NEQ predicate on the "triggered_at" field.
func TriggeredAtNEQ(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldTriggeredAt, v))
}

// TriggeredAtIn applies the In predicate on the "triggered_at" field.
func TriggeredAtIn(vs ...time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldTriggeredAt, vs...))
}

// TriggeredAtNotIn applies the NotIn predicate on the "triggered_at" field.
func TriggeredAtNotIn(vs ...time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldTriggeredAt, vs...))
}

// TriggeredAtGT applies the GT predicate on the "triggered_at" field.
func TriggeredAtGT(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGT(FieldTriggeredAt, v))
}

// TriggeredAtGTE applies the GTE predicate on the "triggered_at" field.
func TriggeredAtGTE(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGTE(FieldTriggeredAt, v))
}

// TriggeredAtLT applies the LT predicate on the "triggered_at" field.
func TriggeredAtLT(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLT(FieldTriggeredAt, v))
}

// TriggeredAtLTE applies the LTE predicate on the "triggered_at" field.
func TriggeredAtLTE(v time.Time) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLTE(FieldTriggeredAt, v))
}

// ExecutionStatusEQ applies the EQ predicate on the "execution_status" field.
func ExecutionStatusEQ(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldExecutionStatus, v))
}

// ExecutionStatusNEQ applies the NEQ predicate on the "execution_status" field.
func ExecutionStatusNEQ(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldExecutionStatus, v))
}

// ExecutionStatusIn applies the In predicate on the "execution_status" field.
func ExecutionStatusIn(vs ...string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldExecutionStatus, vs...))
}

// ExecutionStatusNotIn applies the NotIn predicate on the "execution_status" field.
func ExecutionStatusNotIn(vs ...string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldExecutionStatus, vs...))
}

// ExecutionStatusGT applies the GT predicate on the "execution_status" field.
func ExecutionStatusGT(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGT(FieldExecutionStatus, v))
}

// ExecutionStatusGTE applies the GTE predicate on the "execution_status" field.
func ExecutionStatusGTE(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGTE(FieldExecutionStatus, v))
}

// ExecutionStatusLT applies the LT predicate on the "execution_status" field.
func ExecutionStatusLT(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLT(FieldExecutionStatus, v))
}

// ExecutionStatusLTE applies the LTE predicate on the "execution_status" field.
func ExecutionStatusLTE(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLTE(FieldExecutionStatus, v))
}

// ExecutionStatusContains applies the Contains predicate on the "execution_status" field.
func ExecutionStatusContains(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldContains(FieldExecutionStatus, v))
}

// ExecutionStatusHasPrefix applies the HasPrefix predicate on the "execution_status" field.
func ExecutionStatusHasPrefix(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldHasPrefix(FieldExecutionStatus, v))
}

// ExecutionStatusHasSuffix applies the HasSuffix predicate on the "execution_status" field.
func ExecutionStatusHasSuffix(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldHasSuffix(FieldExecutionStatus, v))
}

// ExecutionStatusEqualFold applies the EqualFold predicate on the "execution_status" field.
func ExecutionStatusEqualFold(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEqualFold(FieldExecutionStatus, v))
}

// ExecutionStatusContainsFold applies the ContainsFold predicate on the "execution_status" field.
func ExecutionStatusContainsFold(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldContainsFold(FieldExecutionStatus, v))
}

// ResultIsNil applies the IsNil predicate on the "result" field.
func ResultIsNil() predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIsNull(FieldResult))
}

// ResultNotNil applies the NotNil predicate on the "result" field.
func ResultNotNil() predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotNull(FieldResult))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.RuleExecution {
	return predicate.RuleExecution(sql.FieldContainsFold(FieldErrorMessage, v))
}

// HasRule applies the HasEdge predicate on the "rule" edge.
func HasRule() predicate.RuleExecution {
	return predicate.RuleExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RuleTable, RuleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRuleWith applies the HasEdge predicate on the "rule" edge with a given conditions (other predicates).
func HasRuleWith(preds ...predicate.DeviceRule) predicate.RuleExecution {
	return predicate.RuleExecution(func(s *sql.Selector) {
		step := newRuleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RuleExecution) predicate.RuleExecution {
	return predicate.RuleExecution(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RuleExecution) predicate.RuleExecution {
	return predicate.RuleExecution(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RuleExecution) predicate.RuleExecution {
	return predicate.RuleExecution(sql.NotPredicates(p))
}
