// Code generated by ent, DO NOT EDIT.

package telemetrydata

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/iot-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldTenantID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldDeviceID, v))
}

// MetricName applies equality check predicate on the "metric_name" field. It's identical to MetricNameEQ.
func MetricName(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldMetricName, v))
}

// MetricValue applies equality check predicate on the "metric_value" field. It's identical to MetricValueEQ.
func MetricValue(v float64) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldMetricValue, v))
}

// Unit applies equality check predicate on the "unit" field. It's identical to UnitEQ.
func Unit(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldUnit, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldTimestamp, v))
}

// GeoPoint applies equality check predicate on the "geo_point" field. It's identical to GeoPointEQ.
func GeoPoint(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldGeoPoint, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldCreatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLTE(FieldTenantID, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...uuid.UUID) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNotIn(FieldDeviceID, vs...))
}

// MetricNameEQ applies the EQ predicate on the "metric_name" field.
func MetricNameEQ(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldMetricName, v))
}

// MetricNameNEQ applies the NEQ predicate on the "metric_name" field.
func MetricNameNEQ(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNEQ(FieldMetricName, v))
}

// MetricNameIn applies the In predicate on the "metric_name" field.
func MetricNameIn(vs ...string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldIn(FieldMetricName, vs...))
}

// MetricNameNotIn applies the NotIn predicate on the "metric_name" field.
func MetricNameNotIn(vs ...string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNotIn(FieldMetricName, vs...))
}

// MetricNameGT applies the GT predicate on the "metric_name" field.
func MetricNameGT(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGT(FieldMetricName, v))
}

// MetricNameGTE applies the GTE predicate on the "metric_name" field.
func MetricNameGTE(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGTE(FieldMetricName, v))
}

// MetricNameLT applies the LT predicate on the "metric_name" field.
func MetricNameLT(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLT(FieldMetricName, v))
}

// MetricNameLTE applies the LTE predicate on the "metric_name" field.
func MetricNameLTE(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLTE(FieldMetricName, v))
}

// MetricNameContains applies the Contains predicate on the "metric_name" field.
func MetricNameContains(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldContains(FieldMetricName, v))
}

// MetricNameHasPrefix applies the HasPrefix predicate on the "metric_name" field.
func MetricNameHasPrefix(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldHasPrefix(FieldMetricName, v))
}

// MetricNameHasSuffix applies the HasSuffix predicate on the "metric_name" field.
func MetricNameHasSuffix(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldHasSuffix(FieldMetricName, v))
}

// MetricNameEqualFold applies the EqualFold predicate on the "metric_name" field.
func MetricNameEqualFold(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEqualFold(FieldMetricName, v))
}

// MetricNameContainsFold applies the ContainsFold predicate on the "metric_name" field.
func MetricNameContainsFold(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldContainsFold(FieldMetricName, v))
}

// MetricValueEQ applies the EQ predicate on the "metric_value" field.
func MetricValueEQ(v float64) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldMetricValue, v))
}

// MetricValueNEQ applies the NEQ predicate on the "metric_value" field.
func MetricValueNEQ(v float64) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNEQ(FieldMetricValue, v))
}

// MetricValueIn applies the In predicate on the "metric_value" field.
func MetricValueIn(vs ...float64) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldIn(FieldMetricValue, vs...))
}

// MetricValueNotIn applies the NotIn predicate on the "metric_value" field.
func MetricValueNotIn(vs ...float64) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNotIn(FieldMetricValue, vs...))
}

// MetricValueGT applies the GT predicate on the "metric_value" field.
func MetricValueGT(v float64) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGT(FieldMetricValue, v))
}

// MetricValueGTE applies the GTE predicate on the "metric_value" field.
func MetricValueGTE(v float64) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGTE(FieldMetricValue, v))
}

// MetricValueLT applies the LT predicate on the "metric_value" field.
func MetricValueLT(v float64) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLT(FieldMetricValue, v))
}

// MetricValueLTE applies the LTE predicate on the "metric_value" field.
func MetricValueLTE(v float64) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLTE(FieldMetricValue, v))
}

// UnitEQ applies the EQ predicate on the "unit" field.
func UnitEQ(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldUnit, v))
}

// UnitNEQ applies the NEQ predicate on the "unit" field.
func UnitNEQ(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNEQ(FieldUnit, v))
}

// UnitIn applies the In predicate on the "unit" field.
func UnitIn(vs ...string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldIn(FieldUnit, vs...))
}

// UnitNotIn applies the NotIn predicate on the "unit" field.
func UnitNotIn(vs ...string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNotIn(FieldUnit, vs...))
}

// UnitGT applies the GT predicate on the "unit" field.
func UnitGT(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGT(FieldUnit, v))
}

// UnitGTE applies the GTE predicate on the "unit" field.
func UnitGTE(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGTE(FieldUnit, v))
}

// UnitLT applies the LT predicate on the "unit" field.
func UnitLT(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLT(FieldUnit, v))
}

// UnitLTE applies the LTE predicate on the "unit" field.
func UnitLTE(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLTE(FieldUnit, v))
}

// UnitContains applies the Contains predicate on the "unit" field.
func UnitContains(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldContains(FieldUnit, v))
}

// UnitHasPrefix applies the HasPrefix predicate on the "unit" field.
func UnitHasPrefix(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldHasPrefix(FieldUnit, v))
}

// UnitHasSuffix applies the HasSuffix predicate on the "unit" field.
func UnitHasSuffix(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldHasSuffix(FieldUnit, v))
}

// UnitIsNil applies the IsNil predicate on the "unit" field.
func UnitIsNil() predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldIsNull(FieldUnit))
}

// UnitNotNil applies the NotNil predicate on the "unit" field.
func UnitNotNil() predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNotNull(FieldUnit))
}

// UnitEqualFold applies the EqualFold predicate on the "unit" field.
func UnitEqualFold(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEqualFold(FieldUnit, v))
}

// UnitContainsFold applies the ContainsFold predicate on the "unit" field.
func UnitContainsFold(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldContainsFold(FieldUnit, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLTE(FieldTimestamp, v))
}

// GeoPointEQ applies the EQ predicate on the "geo_point" field.
func GeoPointEQ(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldGeoPoint, v))
}

// GeoPointNEQ applies the NEQ predicate on the "geo_point" field.
func GeoPointNEQ(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNEQ(FieldGeoPoint, v))
}

// GeoPointIn applies the In predicate on the "geo_point" field.
func GeoPointIn(vs ...string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldIn(FieldGeoPoint, vs...))
}

// GeoPointNotIn applies the NotIn predicate on the "geo_point" field.
func GeoPointNotIn(vs ...string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNotIn(FieldGeoPoint, vs...))
}

// GeoPointGT applies the GT predicate on the "geo_point" field.
func GeoPointGT(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGT(FieldGeoPoint, v))
}

// GeoPointGTE applies the GTE predicate on the "geo_point" field.
func GeoPointGTE(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGTE(FieldGeoPoint, v))
}

// GeoPointLT applies the LT predicate on the "geo_point" field.
func GeoPointLT(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLT(FieldGeoPoint, v))
}

// GeoPointLTE applies the LTE predicate on the "geo_point" field.
func GeoPointLTE(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLTE(FieldGeoPoint, v))
}

// GeoPointContains applies the Contains predicate on the "geo_point" field.
func GeoPointContains(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldContains(FieldGeoPoint, v))
}

// GeoPointHasPrefix applies the HasPrefix predicate on the "geo_point" field.
func GeoPointHasPrefix(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldHasPrefix(FieldGeoPoint, v))
}

// GeoPointHasSuffix applies the HasSuffix predicate on the "geo_point" field.
func GeoPointHasSuffix(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldHasSuffix(FieldGeoPoint, v))
}

// GeoPointIsNil applies the IsNil predicate on the "geo_point" field.
func GeoPointIsNil() predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldIsNull(FieldGeoPoint))
}

// GeoPointNotNil applies the NotNil predicate on the "geo_point" field.
func GeoPointNotNil() predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNotNull(FieldGeoPoint))
}

// GeoPointEqualFold applies the EqualFold predicate on the "geo_point" field.
func GeoPointEqualFold(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEqualFold(FieldGeoPoint, v))
}

// GeoPointContainsFold applies the ContainsFold predicate on the "geo_point" field.
func GeoPointContainsFold(v string) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldContainsFold(FieldGeoPoint, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TelemetryData {
	return predicate.TelemetryData(sql.FieldLTE(FieldCreatedAt, v))
}

// HasDevice applies the HasEdge predicate on the "device" edge.
func HasDevice() predicate.TelemetryData {
	return predicate.TelemetryData(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceWith applies the HasEdge predicate on the "device" edge with a given conditions (other predicates).
func HasDeviceWith(preds ...predicate.Device) predicate.TelemetryData {
	return predicate.TelemetryData(func(s *sql.Selector) {
		step := newDeviceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TelemetryData) predicate.TelemetryData {
	return predicate.TelemetryData(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TelemetryData) predicate.TelemetryData {
	return predicate.TelemetryData(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TelemetryData) predicate.TelemetryData {
	return predicate.TelemetryData(sql.NotPredicates(p))
}
